[package]
name = "ic-certification-test-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
ic-crypto-internal-seed = { path = "../../crypto/internal/crypto_lib/seed" }
ic-crypto-internal-threshold-sig-bls12381 = { path = "../../crypto/internal/crypto_lib/threshold_sig/bls12_381" }
ic-crypto-internal-types = { path = "../../crypto/internal/crypto_lib/types" }
ic-crypto-tree-hash = { path = "../../crypto/tree_hash" }
ic-crypto-utils-threshold-sig-der = { path = "../../crypto/utils/threshold_sig_der" }
ic-types = { path = "../../types/types" }
leb128 = "0.2.4"
rand = "0.8.3"
serde = { version = "1.0.99", features = [ "derive" ] }
serde_cbor = "0.11.1"
