[package]
name = "ic-crypto-test-utils-ni-dkg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ic-crypto-internal-bls12-381-type = { path = "../../internal/crypto_lib/bls12_381/type" }
ic-crypto-internal-types = { path = "../../internal/crypto_lib/types" }
ic-crypto-internal-csp = { path = "../../internal/crypto_service_provider" }
ic-crypto-temp-crypto = { path = "../../temp_crypto" }
ic-crypto-test-utils-reproducible-rng = { path = "../../test_utils/reproducible_rng" }
ic-interfaces = { path = "../../../interfaces" }
ic-interfaces-registry = { path = "../../../interfaces/registry" }
ic-protobuf = { path = "../../../protobuf" }
ic-registry-client-fake = { path = "../../../registry/fake" }
ic-registry-client-helpers = { path = "../../../registry/helpers" }
ic-registry-keys = { path = "../../../registry/keys" }
ic-registry-proto-data-provider = { path = "../../../registry/proto_data_provider" }
ic-types = { path = "../../../types/types" }
rand = "0.8"
rand_chacha = "0.3"
serde = { version = "1.0.99", features = [ "derive" ] }

[dev-dependencies]
hex = "0.4.2"
ic-crypto-test-utils = { path = "../../test_utils" }
ic-types-test-utils = { path = "../../../types/types_test_utils" }
