[package]
name = "ic-registry-common-proto"
version = "0.8.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
prost = { workspace = true }

[dev-dependencies]
ic-registry-common-proto-generator = { path = "./generator" }
ic-test-utilities-compare-dirs = { path = "../../test_utilities/compare_dirs" }
tempfile = "3.1.0"
