[package]
name = "ic-admin"
version = "0.8.0"
edition = "2021"

[dependencies]
anyhow = "1.0.31"
ic-prep = { path = "../../prep" }
async-trait = "0.1.51"
regex = "1.3.9"
bytes = "1.0.1"
base64 = "0.13.0"
clap = { version = "3.1.6", features = ["derive"] }
futures = "0.3.8"
hex = "0.4"
lazy_static = "1.4.0"
cycles-minting-canister = { path ="../../nns/cmc" }
ic-admin-derive = { path = "../admin-derive"}
ic-nns-init = { path="../../nns/init" }
ic-base-types = { path="../../types/base_types" }
ic-canister-client = { path = "../../canister_client" }
ic-canister-client-sender = { path = "../../canister_client/sender" }
ic-config = { path = "../../config" }
ic-crypto-utils-threshold-sig-der = { path = "../../crypto/utils/threshold_sig_der" }
ic-crypto-internal-types = { path = "../../crypto/internal/crypto_lib/types" }
ic-crypto-sha = {path = "../../crypto/sha/" }
ic-http-utils = { path = "../../http_utils" }
ic-ic00-types = { path = "../../types/ic00_types" }
ic-interfaces-registry = { path = "../../interfaces/registry" }
ic-protobuf = { path = "../../protobuf" }
ic-registry-client = { path = "../client" }
ic-registry-client-helpers = { path = "../helpers" }
ic-registry-keys = { path = "../keys" }
ic-registry-local-store = { path = "../local_store" }
ic-registry-nns-data-provider = { path = "../nns_data_provider" }
ic-registry-provisional-whitelist = { path = "../provisional_whitelist" }
ic-registry-subnet-features = { path = "../subnet_features" }
ic-registry-subnet-type = { path = "../subnet_type" }
ic-registry-transport = { path = "../transport" }
ic-types = { path = "../../types/types" }
ic-nervous-system-common-test-keys = { path = "../../nervous_system/common/test_keys" }
ic-nervous-system-root = { path = "../../nervous_system/root" }
ic-nns-common = { path = "../../nns/common" }
ic-nns-constants = { path = "../../nns/constants" }
ic-nns-governance = { path = "../../nns/governance" }
ic-nns-handler-root = { path = "../../nns/handlers/root" }
ic-nns-test-utils = { path = "../../nns/test_utils" }
ic-registry-routing-table = { path = "../routing_table" }
ic-sns-wasm = { path = "../../nns/sns-wasm" }
ic-sns-swap = { path = "../../sns/swap" }
on_wire = { path = "../../rust_canisters/on_wire" }
prost = "0.11.0"
registry-canister = { path = "../canister" }
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11.1"
serde_json = "1.0.40"
serde-bytes-repr = "0.1.5"
tokio = { version = "1.24.2", features = ["full"] }
walkdir = "2.3.1"
candid = "0.8.1"
reqwest = { version = "0.11.1", features = [ "native-tls" ] }
tempfile = "3.1.0"
url = { version = "2.1.1", features = ["serde"] }
strum = "0.23.0"
strum_macros = "0.23.0"
chrono = "0.4"

[dev-dependencies]
assert_matches = "1.4.0"

[[bin]]
name = "ic-admin"
path = "src/main.rs"
