[package]
name = "ic-admin"
version = "0.8.0"
edition = "2021"

[dependencies]
anyhow = "1.0.31"
ic-prep = { path = "../../prep" }
async-trait = "0.1.51"
bytes = { workspace = true }
base64 = "0.13.0"
clap = { version = "3.1.6", features = ["derive"] }
futures = { workspace = true }
hex = "0.4"
humantime = "2.1.0"
cycles-minting-canister = { path = "../../nns/cmc" }
ic-admin-derive = { path = "../admin-derive" }
ic-btc-interface = { workspace = true }
ic-nns-init = { path = "../../nns/init" }
ic-base-types = { path = "../../types/base_types" }
ic-canister-client = { path = "../../canister_client" }
ic-canister-client-sender = { path = "../../canister_client/sender" }
ic-config = { path = "../../config" }
ic-crypto-utils-threshold-sig-der = { path = "../../crypto/utils/threshold_sig_der" }
ic-crypto-internal-types = { path = "../../crypto/internal/crypto_lib/types" }
ic-http-utils = { path = "../../http_utils" }
ic-ic00-types = { path = "../../types/ic00_types" }
ic-interfaces-registry = { path = "../../interfaces/registry" }
ic-nns-handler-lifeline-interface = { path = "../../nns/handlers/lifeline/interface" }
ic-protobuf = { path = "../../protobuf" }
ic-registry-client = { path = "../client" }
ic-registry-client-helpers = { path = "../helpers" }
ic-registry-keys = { path = "../keys" }
ic-registry-local-store = { path = "../local_store" }
ic-registry-nns-data-provider = { path = "../nns_data_provider" }
ic-registry-nns-data-provider-wrappers = { path = "../nns_data_provider_wrappers" }
ic-registry-provisional-whitelist = { path = "../provisional_whitelist" }
ic-registry-subnet-features = { path = "../subnet_features" }
ic-registry-subnet-type = { path = "../subnet_type" }
ic-registry-transport = { path = "../transport" }
ic-types = { path = "../../types/types" }
ic-nervous-system-clients = { path = "../../nervous_system/clients" }
ic-nervous-system-common = { path = "../../nervous_system/common" }
ic-nervous-system-humanize = { path = "../../nervous_system/humanize" }
ic-nervous-system-proto = { path = "../../nervous_system/proto" }
ic-nervous-system-common-test-keys = { path = "../../nervous_system/common/test_keys" }
ic-nervous-system-root = { path = "../../nervous_system/root" }
ic-nns-common = { path = "../../nns/common" }
ic-nns-constants = { path = "../../nns/constants" }
ic-nns-governance = { path = "../../nns/governance" }
ic-nns-handler-root = { path = "../../nns/handlers/root/impl" }
ic-nns-test-utils = { path = "../../nns/test_utils" }
ic-registry-routing-table = { path = "../routing_table" }
ic-sns-init = { path = "../../sns/init" }
ic-sns-wasm = { path = "../../nns/sns-wasm" }
ic-sns-swap = { path = "../../sns/swap" }
itertools = "0.10.0"
maplit = "1.0.2"
on_wire = { path = "../../rust_canisters/on_wire" }
pretty_assertions = "0.6.1"
prost = { workspace = true }
registry-canister = { path = "../canister" }
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11.1"
serde_json = "1.0.40"
serde-bytes-repr = "0.1.5"
tokio = { version = "1.32.0", features = ["full"] }
candid = { workspace = true }
reqwest = { version = "0.11.1", features = ["native-tls"] }
tempfile = "3.1.0"
url = { version = "2.1.1", features = ["serde"] }
strum = "0.23.0"
strum_macros = "0.23.0"
chrono = "0.4"

[dev-dependencies]
assert_matches = "1.4.0"

[[bin]]
name = "ic-admin"
path = "src/main.rs"
