[package]
name = "ic-ledger-canister-core"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
async-trait = "0.1.53"
candid = { workspace = true }
ic-base-types = { path = "../../types/base_types" }
ic-constants = { path = "../../constants" }
ic-ic00-types = { path = "../../types/ic00_types" }
ic-canister-log = { path = "../../rust_canisters/canister_log" }
ic-ledger-core = { path = "../ledger_core" }
ic-utils = { path = "../../utils" }
ic-ledger-hash-of = { path = "../../../packages/ic-ledger-hash-of" }
num-traits = "0.2.12"
serde = { workspace = true }
