[package]
name = "pocket-ic"
version = "0.0.1"
edition = "2021"

[dependencies]
candid = "^0.9"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "^1.0"
serde_bytes = "^0.11"
ic-cdk = "0.10"
base64 = "0.11.0"
hex = "^0.4.2"
async-trait = "^0.1.73"


[dev-dependencies]
flate2 = "1.0.27"
