[package]
name = "pocket-ic"
version = "2.0.1"
license = "Apache-2.0"
description = "PocketIC: A Canister Smart Contract Testing Platform"
repository = "https://github.com/dfinity/ic"
readme = "README.md"
categories = ["emulators", "development-tools::testing", "wasm"]
keywords = ["icp", "canister", "testing", "smart-contract", "internet-computer"]
include = [
    "src",
    "Cargo.toml",
    "CHANGELOG.md",
    "README.md",
    "HOWTO.md",
    "LICENSE",
]
authors.workspace = true
edition.workspace = true
documentation.workspace = true

[dependencies]
candid = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_bytes = { workspace = true }
ic-cdk = "0.10"
base64 = { workspace = true }
hex = "^0.4.2"
async-trait = "^0.1.73"
tracing = "0.1"
tracing-appender = "^0.2.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
schemars = "0.8.16"

[dev-dependencies]
flate2 = "1.0.27"
ic-universal-canister = { path = "../../rs/universal_canister/lib" }
ic-base-types = { path = "../../rs/types/base_types" }
icp-ledger = { path = "../../rs/rosetta-api/icp_ledger" }
