[package]
name = "pocket-ic"
version = "0.0.1"
edition = "2021"

[dependencies]
candid = "^0.9"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "^1.0"
serde_bytes = "^0.11"
ic-cdk = "0.10"
base64 = "*"

[dev-dependencies]
