[package]
name = "systemd-journal-gatewayd-shim"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
anyhow = "1.0.75"
async-trait = "0.1.73"
axum = "0.6.20"
clap = { version = "4.4.0", features = ["derive"] }
http = "0.2.9"
itertools = { workspace = true }
reqwest = { workspace = true }
thiserror = "1.0.47"
tokio = { workspace = true }
url = "2.4.0"
