[package]
name = "systemd-journal-gatewayd-shim"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
async-trait = "0.1.73"
axum = "0.6.20"
clap = { version = "4.4.0", features = ["derive"] }
http = "0.2.9"
itertools = "0.11.0"
reqwest = { version = "0.11.20", features = ["stream"] }
thiserror = "1.0.47"
tokio = { version = "1.32.0", features = ["full"] }
url = "2.4.0"
