[package]
name = "ic-icrc-rosetta-runner"
version = "0.1.0"
authors = ["The Internet Computer Project Developers"]
description = "Build Once. Integrate Your Blockchain Everywhere. "
edition = "2021"

[dependencies]
tempfile = "3.1.0"
candid = { workspace = true }
tokio = { version = "1.32.0", features = ["full"] }
