[package]
name = "ic-crypto-internal-csp-test-utils"
version = "0.8.0"
authors = ["The Internet Computer Project Developers"]
edition = "2021"

[dependencies]
ic-crypto-internal-csp = { path = "../crypto_service_provider" }
ic-crypto-internal-logmon = { path = "../logmon" }
ic-crypto-internal-test-vectors = { path = "../test_vectors" }
ic-crypto-internal-types = { path = "../crypto_lib/types" }
ic-logger = { path = "../../../monitoring/logger" }
ic-protobuf = { path = "../../../protobuf" }
ic-types = { path = "../../../types/types" } # Would like to get rid of this but as long as the CSP depends on ic-types we can't really.
ic-types-test-utils = { path = "../../../types/types_test_utils" }
serde = { version = "1.0.99", features = ["derive"] }
serde_bytes = "0.11"
# No other ic-dependencies are allowed.

mockall = "0.7.2"
proptest = "1.0"
rand = "0.8"
rand_chacha = "0.3"
tempfile = "3.1.0"
tokio = { version = "1.23.1", features = ["full"] }
