[package]
name = "ic-http-endpoints-metrics"
version = "0.8.0"
edition = "2021"

[dependencies]
hyper = { version = "0.14.18", features = ["full"] }
ic-async-utils = { path = "../../async_utils" }
ic-config = { path = "../../config" }
ic-crypto-tls-interfaces = { path = "../../crypto/tls_interfaces" }
ic-interfaces-registry = { path = "../../interfaces/registry" }
ic-metrics = { path = "../../monitoring/metrics" }
ic-types = { path = "../../types/types" }
prometheus = { version = "0.12.0", features = [ "process" ] }
serde = { version = "1.0.99", features = [ "derive" ] }
slog = { version = "2.5.2", features = ["nested-values", "release_max_level_debug"] }
thiserror = "1.0.37"
tokio = "1.23.1"
tokio-io-timeout = "1.2.0"
tower = "0.4.13"

[dev-dependencies]
ic-test-utilities-logger = { path = "../../test_utilities/logger" }
