[package]
name = "ic-https-outcalls-consensus"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
ic-config = { path = "../../config" }
ic-consensus-utils = { path = "../../consensus/utils" }
ic-error-types = { path = "../../types/error_types" }
ic-interfaces = { path = "../../interfaces" }
ic-interfaces-adapter-client = { path = "../../interfaces/adapter_client" }
ic-interfaces-registry = { path = "../../interfaces/registry" }
ic-interfaces-state-manager = { path = "../../interfaces/state_manager" }
ic-logger = { path = "../../monitoring/logger" }
ic-metrics = { path = "../../monitoring/metrics" }
ic-protobuf = { path = "../../protobuf" }
ic-registry-client-helpers = { path = "../../registry/helpers" }
ic-replicated-state = { path = "../../replicated_state" }
ic-types = { path = "../../types/types" }
prometheus = { workspace = true }
prost = { workspace = true }
slog = { version = "2.5.2", features = [
    "nested-values",
    "release_max_level_debug",
] }

[dev-dependencies]
ic-artifact-pool = { path = "../../artifact_pool" }
ic-error-types = { path = "../../types/error_types" }
ic-consensus-mocks = { path = "../../consensus/mocks" }
ic-registry-subnet-type = { path = "../../registry/subnet_type" }
ic-test-utilities = { path = "../../test_utilities" }
ic-test-utilities-logger = { path = "../../test_utilities/logger" }
ic-test-utilities-registry = { path = "../../test_utilities/registry" }
mockall = "0.7.2"
proptest = "1.0"
