[package]
name = "ic-icrc1"
version = "0.8.0"
authors = ["The Internet Computer Project Developers"]
description = "ICRC-1 compliant ledger library."
edition = "2021"

[dependencies]
candid = { workspace = true }
ciborium = { workspace = true }
hex = "0.4.2"
ic-base-types = { path = "../../types/base_types" }
ic-crypto-sha2 = { path = "../../crypto/sha2" }
ic-ledger-canister-core = { path = "../ledger_canister_core" }
ic-ledger-core = { path = "../ledger_core" }
icrc-ledger-types = { path = "../../../packages/icrc-ledger-types", features = ["experimental-api"] }
ic-ledger-hash-of = { path = "../../../packages/ic-ledger-hash-of" }
num-traits = "0.2.12"
num-bigint = "0.4"
serde = "1.0"
serde_bytes = "0.11"
tempfile = "3.1.0"
thiserror = "1.0"

[dev-dependencies]
ic-icrc1-test-utils = { path = "test_utils" }
ic-icrc1-tokens-u64 = { path = "tokens_u64" }
ic-icrc1-tokens-u256 = { path = "tokens_u256" }
leb128 = "0.2.4"
proptest = "1.0"
rand = "0.8"
