[package]
name = "create_acme_account"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
clap = { version = "4.0.18", features = ["derive"] }
instant-acme = "0.1.0"
serde = { version = "1.0.147", features = ["serde_derive"] }
serde_json = "1.0.87"
tokio = { version = "1.32.0", features = ["full"] }
