[package]
name = "ic-state-tool"
version = "0.8.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "state-tool"
path = "src/main.rs"

[dependencies]
clap = { version = "3.1.6", features = ["derive"] }
hex = "0.4.2"
ic-config = { path = "../config" }
ic-logger = { path = "../monitoring/logger" }
ic-metrics = { path = "../monitoring/metrics" }
ic-protobuf = { path = "../protobuf" }
ic-registry-routing-table = { path = "../registry/routing_table" }
ic-registry-subnet-type = { path = "../registry/subnet_type" }
ic-replicated-state = { path = "../replicated_state" }
ic-state-layout = { path = "../state_layout" }
ic-state-manager = { path = "../state_manager" }
ic-crypto-sha2 = { path = "../crypto/sha2" }
ic-sys = { path = "../sys" }
ic-types = { path = "../types/types" }
ic-utils = { path = "../utils" }
prost = { workspace = true }
scoped_threadpool = "0.1.*"

[dev-dependencies]
tempfile = "3.1.0"
