[package]
name = "ic-https-outcalls-adapter-client"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

candid = { workspace = true }
futures = { workspace = true }
ic-adapter-metrics = { path = "../../monitoring/adapter_metrics" }
ic-async-utils = { path = "../../async_utils" }
ic-config = { path = "../../config" }
ic-error-types = { path = "../../types/error_types" }
ic-https-outcalls-service = { path = "../service" }
ic-ic00-types = { path = "../../types/ic00_types" }
ic-interfaces = { path = "../../interfaces" }
ic-interfaces-adapter-client = { path = "../../interfaces/adapter_client" }
ic-logger = { path = "../../monitoring/logger" }
ic-metrics = { path = "../../monitoring/metrics" }
ic-protobuf = { path = "../../protobuf" }
ic-registry-subnet-type = { path = "../../registry/subnet_type" }
ic-types = { path = "../../types/types" }
prometheus = { version = "0.12.0", features = ["process"] }
slog = "2.7.0"
tokio = { version = "1.32.0", features = ["full"] }
tonic = { workspace = true }
tower = { workspace = true }

[dev-dependencies]
tower-test = "0.4.0"
ic-test-utilities = { path = "../../test_utilities" }
