[package]
name = "ic-crypto-test-utils-root-of-trust"
version = "0.8.0"
edition = "2021"
description = "Test utilities for providing the root of trust"

[dependencies]
ic-types = { path = "../../../types/types" }
mockall = "0.11.4"
thiserror = "1.0"
