[package]
name = "ic-registry-client"
version = "0.8.0"
edition = "2021"

[dependencies]
crossbeam-channel = "0.5.5"
ic-interfaces-registry = { path = "../../interfaces/registry" }
ic-metrics = { path = "../../monitoring/metrics" }
ic-registry-common-proto = { path = "../proto" }
ic-registry-client-helpers = { path = "../helpers" }
ic-registry-keys = { path = "../keys" }
ic-types = { path = "../../types/types" }
ic-utils = { path = "../../utils" }
prometheus = { version = "0.12.0", features = ["process"] }

[dev-dependencies]
assert_matches = "1.3.0"
ic-registry-proto-data-provider = { path = "../proto_data_provider" }
ic-test-utilities-metrics = { path = "../../test_utilities/metrics" }
