[package]
name = "ic-validator"
version = "0.8.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
hex = "0.4.2"
ic-constants = { path = "../constants" }
ic-interfaces = { path = "../interfaces" }
ic-types = { path = "../types/types" }
ic-crypto-sha2 = { path = "../crypto/sha2" }
ic-crypto-standalone-sig-verifier = { path = "../crypto/standalone-sig-verifier" }
ic-crypto-tree-hash = { path = "../crypto/tree_hash" }
thiserror = "1.0"

[dev-dependencies]
assert_matches = "1.3.0"
base64 = "0.11.0"
hex = "0.4.2"
ic-crypto-test-utils-reproducible-rng = { path = "../crypto/test_utils/reproducible_rng" }
ic-crypto-test-utils-root-of-trust = { path = "../crypto/test_utils/root_of_trust" }
ic-test-utilities = { path = "../test_utilities" }
mockall = "0.11.4"
rand = "0.8"

[features]
malicious_code = []
