[package]
name = "ic-sys"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
hex = "0.4.2"
ic-crypto-sha2 = { path = "../crypto/sha2" }
lazy_static = "1.4.0"
libc = "0.2.91"
nix = { workspace = true }
wsl = "0.1.0"
phantom_newtype = { path = "../phantom_newtype" }

[dev-dependencies]
tempfile = "3.1.0"
