[package]
name = "ic-ledger-canister-blocks-synchronizer"
version = "0.1.0"
authors = ["The Internet Computer Project Developers"]
edition = "2021"
description = "Synchronizes a local copy of the ledger blocks with the ledger"

[dependencies]
async-trait = "0.1.41"
candid = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
dfn_protobuf = {path = "../../rust_canisters/dfn_protobuf"}
ic-agent = { workspace = true }
ic-certification = { path = "../../certification" }
ic-ledger-canister-core = { path = "../ledger_canister_core" }
ic-ledger-core = { path = "../ledger_core" }
ic-types = { path = "../../types/types" }
icp-ledger = { path = "../icp_ledger" }
ic-ledger-hash-of = { path = "../../../packages/ic-ledger-hash-of" }
log = "0.4.14"
log4rs = "1.1.1"
on_wire = {path = "../../rust_canisters/on_wire"}
rusqlite = { version = "~0.28.0", features = ["bundled"] }
serde = { workspace = true }
tokio = { workspace = true }
url = "2.2.1"

[dev-dependencies]
actix-rt = "2.2.0"
actix-web = { version = "4.0.1", default-features = false, features = ["macros", "compress-brotli", "compress-gzip", "cookies"] }
ic-ledger-canister-blocks-synchronizer-test-utils = { path = "test_utils" }
serde_bytes = { workspace = true }

[lib]
path = "src/lib.rs"

