[package]
name = "canister_sandbox"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[build-dependencies]
cc = "1.0"

[dependencies]
cc = "1.0"
ic-canister-sandbox-backend-lib = { path = "backend_lib" }
libc = "0.2.119"

[dev-dependencies]
# This makes the dependencies of the binary more consistent
# with the dependencies of execution environment tests and
# allows the binary to reuse most of the build artifacts
# produced by `cargo test`.
ic-test-utilities = { path = "../test_utilities" }

[features]
sigsegv_handler_checksum = [ "ic-canister-sandbox-backend-lib/sigsegv_handler_checksum" ]
