[package]
name = "ic-adapter-metrics-server"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = { workspace = true }
ic-adapter-metrics-service = { path = "../adapter_metrics_service" }
ic-async-utils = { path = "../../async_utils" }
ic-logger = { path = "../logger" }
ic-metrics = { path = "../metrics" }
prometheus = "0.12.0"
protobuf = "2.27.1"
slog = "2.7.0"
tokio = { version = "1.32.0", features = ["full"] }
tonic = { workspace = true }
