[package]
name = "ic-adapter-metrics-server"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = { workspace = true }
ic-adapter-metrics-service = { path = "../adapter_metrics_service" }
ic-async-utils = { path = "../../async_utils" }
ic-logger = { path = "../logger" }
ic-metrics = { path = "../metrics" }
prometheus = { workspace = true }
protobuf = "2.27.1"
slog = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
