[package]
name = "ic-crypto-internal-seed"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
ic-crypto-sha2 = { path = "../../../sha2" }
ic-types = { path = "../../../../types/types" }
hex = "0.4"
rand = "0.8"
rand_chacha = "0.3"
serde = { workspace = true }
zeroize = { version = "1.4.3", features = ["zeroize_derive"] }
