[workspace]

members = [
  "packages/icrc-ledger-agent",
  "packages/icrc-ledger-types",
  "packages/ic-ledger-hash-of",
  "packages/ic-starter-tests",
  "packages/pocket-ic",
  "packages/ic-vetkd-utils",
  "rs/artifact_manager",
  "rs/artifact_pool",
  "rs/async_utils",
  "rs/backup",
  "rs/bazelifier",
  "rs/bitcoin/adapter",
  "rs/bitcoin/client",
  "rs/bitcoin/service",
  "rs/bitcoin/ckbtc/agent",
  "rs/bitcoin/ckbtc/minter",
  "rs/bitcoin/ckbtc/kyt",
  "rs/bitcoin/consensus",
  "rs/bitcoin/mock",
  "rs/bitcoin/types/internal",
  "rs/boundary_node/certificate_issuance/certificate_issuer",
  "rs/boundary_node/certificate_issuance/certificate_orchestrator",
  "rs/boundary_node/certificate_issuance/certificate_syncer",
  "rs/boundary_node/control_plane",
  "rs/boundary_node/denylist_updater",
  "rs/boundary_node/ic_balance_exporter",
  "rs/boundary_node/ic_boundary",
  "rs/boundary_node/icx_proxy",
  "rs/boundary_node/prober",
  "rs/canister_client",
  "rs/canister_client/sender",
  "rs/ethereum/cketh/minter",
  "rs/cycles_account_manager",
  "rs/https_outcalls/adapter",
  "rs/https_outcalls/client",
  "rs/https_outcalls/consensus",
  "rs/https_outcalls/service",
  "rs/canister_sandbox",
  "rs/canister_sandbox/backend_lib",
  "rs/canister_sandbox/common",
  "rs/canister_sandbox/replica_controller",
  "rs/canister_sandbox/sandbox_launcher",
  "rs/canonical_state",
  "rs/canonical_state/tree_hash",
  "rs/canonical_state/tree_hash/test_utils",
  "rs/certification",
  "rs/certification/test-utils",
  "rs/config",
  "rs/consensus",
  "rs/consensus/mocks",
  "rs/consensus/utils",
  "rs/constants",
  "rs/criterion_time",
  "rs/crypto",
  "rs/crypto/ecdsa_secp256k1",
  "rs/crypto/ecdsa_secp256r1",
  "rs/crypto/extended_bip32",
  "rs/crypto/for_verification_only",
  "rs/crypto/iccsa",
  "rs/crypto/internal/crypto_lib/basic_sig/der_utils",
  "rs/crypto/internal/crypto_lib/basic_sig/ecdsa_secp256k1",
  "rs/crypto/internal/crypto_lib/basic_sig/ecdsa_secp256r1",
  "rs/crypto/internal/crypto_lib/basic_sig/ed25519",
  "rs/crypto/internal/crypto_lib/basic_sig/iccsa",
  "rs/crypto/internal/crypto_lib/basic_sig/iccsa/test_utils",
  "rs/crypto/internal/crypto_lib/basic_sig/rsa_pkcs1",
  "rs/crypto/internal/crypto_lib/bls12_381/type",
  "rs/crypto/internal/crypto_lib/bls12_381/vetkd",
  "rs/crypto/internal/crypto_lib/hmac",
  "rs/crypto/internal/crypto_lib/multi_sig/bls12_381",
  "rs/crypto/internal/crypto_lib/seed",
  "rs/crypto/internal/crypto_lib/sha2",
  "rs/crypto/secrets_containers",
  "rs/crypto/internal/crypto_lib/threshold_sig/bls12_381",
  "rs/crypto/internal/crypto_lib/threshold_sig/bls12_381/der_utils",
  "rs/crypto/internal/crypto_lib/threshold_sig/tecdsa",
  "rs/crypto/internal/crypto_lib/tls",
  "rs/crypto/internal/crypto_lib/types",
  "rs/crypto/internal/crypto_service_provider",
  "rs/crypto/internal/crypto_service_provider/protobuf_generator",
  "rs/crypto/internal/csp_test_utils",
  "rs/crypto/internal/logmon",
  "rs/crypto/test_utils/reproducible_rng",
  "rs/crypto/internal/test_vectors",
  "rs/crypto/node_key_generation",
  "rs/crypto/node_key_validation",
  "rs/crypto/getrandom_for_wasm",
  "rs/crypto/prng",
  "rs/crypto/sha2",
  "rs/crypto/tecdsa",
  "rs/crypto/temp_crypto",
  "rs/crypto/test_utils",
  "rs/crypto/test_utils/canister_sigs",
  "rs/crypto/test_utils/canister_threshold_sigs",
  "rs/crypto/test_utils/metrics",
  "rs/crypto/test_utils/ni-dkg",
  "rs/crypto/tls_interfaces",
  "rs/crypto/tls_interfaces/mocks",
  "rs/crypto/tree_hash",
  "rs/crypto/tree_hash/test_utils",
  "rs/crypto/utils/basic_sig",
  "rs/crypto/utils/threshold_sig",
  "rs/crypto/utils/threshold_sig_der",
  "rs/crypto/utils/tls",
  "rs/cup_explorer",
  "rs/depcheck",
  "rs/drun",
  "rs/recovery",
  "rs/recovery/subnet_splitting",
  "rs/replay",
  "rs/elastic_common_schema",
  "rs/embedders",
  "rs/execution_environment",
  "rs/execution_environment/benches/lib",
  "rs/http_endpoints/public",
  "rs/http_endpoints/metrics",
  "rs/http_utils",
  "rs/ic_os/launch-single-vm",
  "rs/ic_os/deterministic_ips",
  "rs/ic_os/sev",
  "rs/ic_os/sev_interfaces",
  "rs/ic_os/sevctl",
  "rs/ic_os/vsock/guest",
  "rs/ic_os/vsock/host",
  "rs/ic_os/vsock/vsock_lib",
  "rs/ic_p8s_service_discovery",
  "rs/ic_p8s_service_discovery/log",
  "rs/identity",
  "rs/ingress_manager",
  "rs/interfaces",
  "rs/interfaces/adapter_client",
  "rs/interfaces/state_manager",
  "rs/interfaces/state_manager/mocks",
  "rs/interfaces/registry",
  "rs/interfaces/registry/mocks",
  "rs/interfaces/transport",
  "rs/interfaces/transport/mocks",
  "rs/memory_tracker",
  "rs/messaging",
  "rs/monitoring/adapter_metrics",
  "rs/monitoring/adapter_metrics_service",
  "rs/monitoring/backtrace",
  "rs/monitoring/context_logger",
  "rs/monitoring/logger",
  "rs/monitoring/metrics",
  "rs/monitoring/pprof",
  "rs/nervous_system/clients",
  "rs/nervous_system/common",
  "rs/nervous_system/common/build_metadata",
  "rs/nervous_system/common/test_canister",
  "rs/nervous_system/common/test_keys",
  "rs/nervous_system/common/test_utils",
  "rs/nervous_system/humanize",
  "rs/nervous_system/proto",
  "rs/nervous_system/proto/protobuf_generator",
  "rs/nervous_system/proxied_canister_calls_tracker",
  "rs/nervous_system/root",
  "rs/nervous_system/runtime",
  "rs/nns/constants",
  "rs/nns/common",
  "rs/nns/common/protobuf_generator",
  "rs/nns/cmc",
  "rs/nns/governance",
  "rs/nns/governance/protobuf_generator",
  "rs/nns/handlers/lifeline/impl",
  "rs/nns/handlers/lifeline/interface",
  "rs/nns/handlers/root/impl",
  "rs/nns/handlers/root/impl/protobuf_generator",
  "rs/nns/handlers/root/interface",
  "rs/nns/identity",
  "rs/nns/init",
  "rs/nns/inspector",
  "rs/nns/integration_tests",
  "rs/nns/nns-ui",
  "rs/nns/test_utils",
  "rs/nns/test_utils_macros",
  "rs/nns/gtc",
  "rs/nns/gtc/protobuf_generator",
  "rs/nns/gtc_accounts",
  "rs/nns/sns-wasm",
  "rs/nns/sns-wasm/protobuf_generator",
  "rs/determinism_test",
  "rs/observability/log_vector_config_generator",
  "rs/observability/service_discovery",
  "rs/observability/config_writer_common",
  "rs/observability/vector_config_generator",
  "rs/observability/prometheus_config_updater",
  "rs/orchestrator",
  "rs/orchestrator/dashboard",
  "rs/orchestrator/registry_replicator",
  "rs/p2p",
  "rs/p2p/peer_manager",
  "rs/p2p/memory_transport",
  "rs/p2p/quic_transport",
  "rs/p2p/state_sync_manager",
  "rs/p2p/test_utils",
  "rs/p2p/experimental/prototype",
  "rs/replica/setup_ic_network",
  "rs/phantom_newtype",
  "rs/prep",
  "rs/protobuf",
  "rs/protobuf/generator",
  "rs/pocket_ic_backend",
  "rs/registry/admin",
  "rs/registry/admin-derive",
  "rs/registry/canister",
  "rs/registry/canister/protobuf_generator",
  "rs/registry/client",
  "rs/registry/fake",
  "rs/registry/helpers",
  "rs/registry/local_registry",
  "rs/registry/local_store",
  "rs/registry/local_store/artifacts",
  "rs/registry/keys",
  "rs/registry/proto",
  "rs/registry/proto/generator",
  "rs/registry/proto_data_provider",
  "rs/registry/provisional_whitelist",
  "rs/registry/regedit",
  "rs/registry/nns_data_provider",
  "rs/registry/nns_data_provider_wrappers",
  "rs/registry/routing_table",
  "rs/registry/subnet_features",
  "rs/registry/subnet_type",
  "rs/registry/transport",
  "rs/registry/transport/protobuf_generator",
  "rs/replica",
  "rs/replica_tests",
  "rs/replicated_state",
  "rs/rosetta-api",
  "rs/rosetta-api/icp_ledger",
  "rs/rosetta-api/icp_ledger/archive",
  "rs/rosetta-api/icp_ledger/ledger",
  "rs/rosetta-api/icp_ledger/protobuf_generator",
  "rs/rosetta-api/icp_ledger/index",
  "rs/rosetta-api/ledger_core",
  "rs/rosetta-api/ledger_canister_core",
  "rs/rosetta-api/ledger_canister_blocks_synchronizer",
  "rs/rosetta-api/ledger_canister_blocks_synchronizer/test_utils",
  "rs/rosetta-api/icrc1",
  "rs/rosetta-api/icrc1/benchmark/generator",
  "rs/rosetta-api/icrc1/benchmark/worker",
  "rs/rosetta-api/icrc1/client",
  "rs/rosetta-api/icrc1/client/cdk",
  "rs/rosetta-api/icrc1/index",
  "rs/rosetta-api/icrc1/index-ng",
  "rs/rosetta-api/icrc1/ledger",
  "rs/rosetta-api/icrc1/rosetta",
  "rs/rosetta-api/icrc1/rosetta/client",
  "rs/rosetta-api/icrc1/rosetta/runner",
  "rs/rosetta-api/icrc1/ledger/sm-tests",
  "rs/rosetta-api/icrc1/archive",
  "rs/rosetta-api/icrc1/test_utils",
  "rs/rosetta-api/icrc1/tokens_u64",
  "rs/rosetta-api/icrc1/tokens_u256",
  "rs/rosetta-api/hardware_wallet_tests",
  "rs/rosetta-api/test_utils",
  "rs/rosetta-api/tvl",
  "rs/rosetta-api/tvl/xrc_mock",
  "rs/rust_canisters/call_tree_test",
  "rs/rust_canisters/canister_creator",
  "rs/rust_canisters/canister_log",
  "rs/rust_canisters/canister_serve",
  "rs/rust_canisters/canister_test",
  "rs/rust_canisters/dfn_core",
  "rs/rust_canisters/dfn_candid",
  "rs/rust_canisters/dfn_http",
  "rs/rust_canisters/dfn_http_metrics",
  "rs/rust_canisters/dfn_json",
  "rs/rust_canisters/dfn_macro",
  "rs/rust_canisters/dfn_protobuf",
  "rs/rust_canisters/ecdsa",
  "rs/rust_canisters/http_types",
  "rs/rust_canisters/memory_test",
  "rs/rust_canisters/on_wire",
  "rs/rust_canisters/pmap",
  "rs/rust_canisters/proxy_canister",
  "rs/rust_canisters/response_payload_test",
  "rs/rust_canisters/stable_reader",
  "rs/rust_canisters/stable_structures",
  "rs/rust_canisters/statesync_test",
  "rs/rust_canisters/tests",
  "rs/rust_canisters/xnet_test",
  "rs/scenario_tests",
  "rs/sns/cli",
  "rs/sns/governance",
  "rs/sns/governance/protobuf_generator",
  "rs/sns/init",
  "rs/sns/init/protobuf_generator",
  "rs/sns/integration_tests",
  "rs/sns/root",
  "rs/sns/root/protobuf_generator",
  "rs/sns/swap",
  "rs/sns/test_utils",
  "rs/starter",
  "rs/state_manager",
  "rs/state_machine_tests",
  "rs/state_layout",
  "rs/state_tool",
  "rs/sys",
  "rs/system_api",
  "rs/test_utilities",
  "rs/test_utilities/artifact_pool",
  "rs/test_utilities/execution_environment",
  "rs/test_utilities/load_wasm",
  "rs/test_utilities/compare_dirs",
  "rs/test_utilities/logger",
  "rs/test_utilities/metrics",
  "rs/test_utilities/serialization",
  "rs/test_utilities/tmpdir",
  "rs/tests",
  "rs/tests/httpbin-rs",
  "rs/tests/nns/sns",
  "rs/tests/nns/ic_mainnet_nns_recovery",
  "rs/tests/test_canisters/http_counter",
  "rs/tests/test_canisters/kv_store",
  "rs/tests/test_canisters/message",
  "rs/tests/testing_verification/wabt-tests",
  "rs/tests/testing_verification/testnets",
  "rs/transport",
  "rs/transport/test_utils",
  "rs/tree_deserializer",
  "rs/types/types",
  "rs/types/types_test_utils",
  "rs/types/base_types",
  "rs/types/base_types/protobuf_generator",
  "rs/types/error_types",
  "rs/types/ic00_types",
  "rs/types/wasm_types",
  "rs/universal_canister/lib",
  "rs/utils",
  "rs/utils/lru_cache",
  "rs/utils/rustfmt",
  "rs/validator",
  "rs/validator/ingress_message",
  "rs/workload_generator",
  "rs/xnet/endpoint",
  "rs/xnet/hyper",
  "rs/xnet/payload_builder",
  "rs/xnet/uri",
]

resolver = "2"

exclude = ["universal_canister/impl", "typescript/service-worker/test_utils"]

[profile.release]
# Add debug information to the release build (does NOT reduce the level of optimization!)
# Makes flamegraphs more readable.
# https://doc.rust-lang.org/cargo/reference/manifest.html#the-profile-sections
debug = true

[profile.release-stripped]
inherits = "release"
lto = "thin"
debug = false

[profile.release-lto]
inherits = "release"
# Enable "thin" LTO to reduce both the compilation time and the binary size.
# See: https://doc.rust-lang.org/cargo/reference/profiles.html#lto
lto = "thin"

[profile.canister-release]
inherits = "release"
debug = false
lto = true
opt-level = 'z'

[profile.dev.package.ic_bls12_381]
opt-level = 3

[patch.crates-io]
# Current jsonrpc version (0.12.1) does not support ipv6 addressing. When new version is
# released this can be removed.
jsonrpc = { git = "https://github.com/apoelstra/rust-jsonrpc", rev = "e42044d" }
# This version pins prost 0.11. Please remove after the next pprof release.
pprof = { git = "https://github.com/tikv/pprof-rs", rev = "059d3c80395c74e9f82ca1f9cbb3c013acfffb75" }

[workspace.dependencies]
candid = "0.8.4"
ethnum = { version = "1.3.2", features = ["serde"] }
ciborium = "0.2.1"
ic-cdk = "0.7.4"
ic-cdk-macros = "0.6.10"
ic-cdk-timers = "0.1.2"
ic-agent = "0.24.1"
ic-btc-interface = { git = "https://github.com/dfinity/bitcoin-canister", rev = "b1693619e3d4dbc00d8c79e9b6886e1db48b21f7" }
ic-utils = "0.24.1"
k256 = { version = "0.13", default_features = false, features = [
  "arithmetic",
  "ecdsa",
  "pkcs8",
] }
p256 = { version = "0.13", default_features = false, features = [
  "arithmetic",
  "ecdsa",
  "pem",
  "pkcs8",
] }
ic-stable-structures = "0.5.4"
