[package]
name = "embedders_bench"
version = "0.8.0"
edition = "2021"

[dependencies]
candid = { workspace = true }
canister-test = { path = "../../../rust_canisters/canister_test" }
criterion = { version = "0.5", features = ["html_reports"] }
ic-test-utilities = { path = "../../../test_utilities" }
ic-test-utilities-execution-environment = { path = "../../../test_utilities/execution_environment" }
ic-types = { path = "../../../types/types" }
