[package]
name = "ic-transport"
version = "0.8.0"
edition = "2021"

[dependencies]
async-trait = "0.1.36"
bytes = "1.2.0"
ic-async-utils = { path = "../async_utils" }
ic-base-types = { path = "../types/base_types" }
ic-config = { path = "../config" }
ic-crypto-tls-interfaces = { path = "../crypto/tls_interfaces" }
ic-interfaces-transport = { path = "../interfaces/transport" }
ic-logger = { path = "../monitoring/logger" }
ic-metrics = { path = "../monitoring/metrics" }
futures = "0.3.25"
h2 = "0.3.14"
http = "0.2.8"
prometheus = { version = "0.12.0", features = [ "process" ] }
serde = { version = "1.0.99", features = [ "derive" ] }
slog = { version = "2.5.2", features = ["nested-values", "release_max_level_debug"] }
strum = { version = "0.24", features = ["derive"] }
tokio = { version = "1.23.1", features = ["full"] }
tower = "0.4.12"

[dev-dependencies]
ic-crypto-tls-interfaces-mocks = { path = "../crypto/tls_interfaces/mocks" }
ic-test-utilities-logger = { path = "../test_utilities/logger" }
ic-transport-test-utils = { path = "./test_utils" }
