[package]
name = "ic-utils"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
hex = "0.4.2"
prost = { workspace = true }
scoped_threadpool = "0.1.*"
serde = { workspace = true }

[target.'cfg(target_family = "unix")'.dependencies]
rand = "0.8.3"

[target.'cfg(target_os = "linux")'.dependencies]
cvt = "0.1.1"
ic-sys = { path = "../sys" }
libc = "0.2.91"
nix = { workspace = true }
thiserror = "1.0"

[dev-dependencies]
assert_matches = "1.5.0"
tempfile = "3.1.0"
serde = { workspace = true }
