[package]
name = "icrc-ledger-types"
authors = ["The Internet Computer Project Developers"]
version = "0.1.2"
edition = "2021"
description = "Types for interacting with DFINITY's implementation of the ICRC-1 fungible token standard."
license = "Apache-2.0"
readme = "README.md"
include = ["src", "Cargo.toml", "CHANGELOG.md", "LICENSE", "README.md"]
repository = "https://github.com/dfinity/ic"

[dependencies]
base32 = "0.4.0"
candid = { workspace = true }
crc32fast = "1.2.0"
hex = "0.4.2"
serde_bytes = "0.11"
serde = "1"
sha2 = "0.10"
num-traits = "0.2.12"

[dev-dependencies]
assert_matches = "1.5.0"
hex = "0.4"

[features]
experimental-api = []
