[package]
name = "icrc-ledger-types"
authors = ["The Internet Computer Project Developers"]
version = "0.1.0"
edition = "2021"
description = "Types for interacting with DFINITY's implementation of the ICRC-1 fungible token standard."
license = "Apache-2.0"
readme = "README.md"
include = ["src", "Cargo.toml", "CHANGELOG.md", "LICENSE", "README.md"]
repository = "https://github.com/dfinity/ic"

[dependencies]
candid = { workspace = true }
hex = "0.4.2"
serde_bytes = "0.11"
serde = "1"
sha2 = "0.10"
num-traits = { version = "0.2.12", optional = true }

[dev-dependencies]
hex = "0.4"

[features]
experimental-api = ["dep:num-traits"]
