[package]
name = "ic-canister-profiler"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
ic0 = "0.18.9"
ic-metrics-encoder = "1.1.0"
