[package]
name = "ic-context-logger"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
slog = { workspace = true }