[package]
name = "ic-cketh-minter"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ic-cketh-minter"
path = "src/main.rs"

[[bin]]
name = "cketh-principal-to-hex"
path = "bin/principal_to_hex.rs"

[dependencies]
askama = { workspace = true }
candid = { workspace = true }
ethnum = { workspace = true }
futures = { workspace = true }
hex = "0.4"
hex-literal = "0.4.1"
ic-canister-log = "0.2.0"
ic-canisters-http-types = { path = "../../../rust_canisters/http_types" }
ic-cdk = { workspace = true }
ic-cdk-macros = { workspace = true }
ic-cdk-timers = { workspace = true }
ic-crypto-ecdsa-secp256k1 = { path = "../../../crypto/ecdsa_secp256k1" }
ic-crypto-sha3 = { path = "../../../crypto/sha3" }
ic-ic00-types = { path = "../../../types/ic00_types" }
icrc-ledger-client-cdk = { path = "../../../../packages/icrc-ledger-client-cdk" }
ic-metrics-encoder = "1"
ic-stable-structures = { workspace = true }
ic-utils-ensure = { path = "../../../utils/ensure" }
icrc-ledger-types = { path = "../../../../packages/icrc-ledger-types" }
minicbor = { workspace = true }
minicbor-derive = { workspace = true }
num-bigint = "0.4.3"
num-traits = "0.2.14"
phantom_newtype = { path = "../../../phantom_newtype" }
rlp = "0.5.2"
serde = { workspace = true }
serde_bytes = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
time = { workspace = true }
thiserror = "1.0"
thousands = "0.2"

[dev-dependencies]
assert_matches = "1.5.0"
ethers-core = "2.0.8"
ic-base-types = { path = "../../../types/base_types" }
ic-config = { path = "../../../config" }
ic-crypto-test-utils-reproducible-rng = { path = "../../../crypto/test_utils/reproducible_rng" }
ic-icrc1-ledger = { path = "../../../rosetta-api/icrc1/ledger" }
ic-state-machine-tests = { path = "../../../state_machine_tests" }
ic-test-utilities-load-wasm = { path = "../../../test_utilities/load_wasm" }
maplit = "1"
proptest = "1.0"
rand = "0.8"
scraper = "0.17.1"
