[package]
name = "ic-crypto-node-key-generation"
version = "0.1.0"
edition = "2021"

[dependencies]
ic-config = { path = "../../config" }
ic-crypto-internal-csp = { path = "../internal/crypto_service_provider" }
ic-crypto-internal-logmon = { path = "../internal/logmon" }
ic-crypto-internal-threshold-sig-ecdsa = { path = "../internal/crypto_lib/threshold_sig/tecdsa" }
ic-crypto-internal-types = { path = "../internal/crypto_lib/types" }
ic-crypto-node-key-validation = { path = "../node_key_validation"}
ic-crypto-tls-interfaces = { path = "../tls_interfaces" }
ic-crypto-utils-basic-sig = { path = "../utils/basic_sig" }
ic-interfaces = { path = "../../interfaces" }
ic-interfaces-registry = { path = "../../interfaces/registry" }
ic-protobuf = { path = "../../protobuf" }
ic-types = { path = "../../types/types" }
tokio = { version = "1.32.0", features = ["full"] }

[dev-dependencies]
assert_matches = "1.5.0"
hex = "0.4.2"
ic-base-types = { path = "../../types/base_types" }
ic-crypto = { path = ".." }
ic-crypto-internal-csp-test-utils = { path = "../internal/csp_test_utils" }
ic-crypto-temp-crypto = { path = "../temp_crypto" }
ic-crypto-test-utils = { path = "../test_utils" }
ic-crypto-test-utils-csp = {path = "../test_utils/csp" }
ic-crypto-test-utils-keys = { path = "../test_utils/keys" }
ic-logger = { path = "../../monitoring/logger" }
ic-metrics = { path = "../../monitoring/metrics" }
ic-registry-client-fake = { path = "../../registry/fake" }
ic-registry-proto-data-provider = { path = "../../registry/proto_data_provider" }
ic-test-utilities = { path = "../../test_utilities" }
ic-types-test-utils = { path = "../../types/types_test_utils" }
openssl = "0.10.55"
tempfile = "3.1.0"
