[package]
name = "ic-p8s-service-discovery"
version = "0.8.0"
edition = "2021"

[dependencies]
anyhow = "1.0.31"
clap = { version = "3.1.6", features = ["derive"] }
crossbeam = "0.8.0"
crossbeam-channel = "0.5.5"
elastic_common_schema = { path = "../elastic_common_schema" }
erased-serde = "0.3.11"
futures-util = "0.3.5"
gflags = "0.3.7"
gflags-derive = "0.1"
humantime = "2.0"
humantime-serde = "1.0"
hyper = { version ="0.14.18", features = ["full"] }
ic-async-utils = { path = "../async_utils" }
ic-config = { path = "../config" }
ic-interfaces = { path = "../interfaces" }
ic-interfaces-registry = { path = "../interfaces/registry" }
ic-p8s-service-discovery-log = { path = "./log" }
ic-metrics = { path = "../monitoring/metrics" }
ic-http-endpoints-metrics = { path = "../http_endpoints/metrics" }
ic-protobuf = { path = "../protobuf" }
ic-registry-local-registry = { path = "../registry/local_registry" }
ic-registry-client = { path = "../registry/client" }
ic-registry-client-helpers = { path = "../registry/helpers" }
ic-registry-nns-data-provider = { path = "../registry/nns_data_provider" }
ic-registry-local-store = { path = "../registry/local_store" }
ic-registry-local-store-artifacts = { path = "../registry/local_store/artifacts" }
ic-types = { path = "../types/types" }
ic-utils = { path = "../utils/" }
lazy_static = "1.4.0"
parse_int = "0.4.0"
prometheus = { version = "0.12.0", features = [ "process" ] }
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0.54"
tempfile = "3.1.0"
slog = { version = "2.5.2", features = ["nested-values"] }
slog-async = { version = "2.5", features = ["nested-values"] }
slog-term = "2.6.0"
slog_derive = "0.2.0"
strum = "0.23.0"
strum_macros = "0.23.0"
thiserror = "1.0"
tokio = { version = "1.24.2", features = ["full"] }
url = { version = "2.1.1", features = ["serde"] }
ic-crypto-utils-threshold-sig-der = { path = "../crypto/utils/threshold_sig_der" }

[dev-dependencies]
ic-test-utilities = { path = "../test_utilities" }
itertools = "0.10.0"


[[bin]]
name = "ic-p8s-sd"
path = "src/titanium/main.rs"
