[package]
name = "ledger-canister"
version = "0.8.0"
authors = ["The Internet Computer Project Developers"]
edition = "2021"

[[bin]]
name = "ledger-canister"
path = "src/main.rs"

[dependencies]
async-trait = "0.1.57"
candid = { workspace = true }
ciborium = { workspace = true }
dfn_candid = { path = "../../../rust_canisters/dfn_candid" }
dfn_core = { path = "../../../rust_canisters/dfn_core" }
dfn_protobuf = { path = "../../../rust_canisters/dfn_protobuf" }
dfn_http_metrics = { path = "../../../rust_canisters/dfn_http_metrics" }
ic-base-types = { path = "../../../types/base_types" }
ic-canister-log = { path = "../../../rust_canisters/canister_log" }
ic-constants = { path = "../../../constants" }
ic-ledger-canister-core = { path = "../../ledger_canister_core" }
ic-ledger-hash-of = { path = "../../../../packages/ic-ledger-hash-of" }
ic-ledger-core = { path = "../../ledger_core" }
ic-metrics-encoder = "1"
icp-ledger = { path = "../" }
intmap = { version = "1.1.0", features = ["serde"] }
lazy_static = "1.4.0"
on_wire = { path = "../../../rust_canisters/on_wire" }
serde = "1.0"
serde_bytes = "0.11.5"
serde_cbor = "0.11.2"
ic-icrc1 = { path = "../../icrc1" }
icrc-ledger-types = { path = "../../../../packages/icrc-ledger-types" }
num-traits = {version = "0.2.15"}


[dev-dependencies]
hex = "0.4.2"
ic-icrc1-ledger-sm-tests = { path = "../../icrc1/ledger/sm-tests" }
ic-state-machine-tests = { path = "../../../state_machine_tests" }
ic-test-utilities-load-wasm = { path = "../../../test_utilities/load_wasm" }

[features]
notify-method = []
