[package]
name = "ic-canister-client"
version = "0.8.0"
edition = "2021"

[dependencies]
backoff = "0.3.0"
ic-crypto-ecdsa-secp256k1 = { path = "../crypto/ecdsa_secp256k1" }
ic-canister-client-sender = { path = "./sender" }
ic-certification = { path = "../certification" }
ic-crypto-tree-hash = { path = "../crypto/tree_hash" }
ic-crypto-utils-threshold-sig-der = { path = "../crypto/utils/threshold_sig_der" }
ic-protobuf = { path = "../protobuf" }
ic-ic00-types = { path = "../types/ic00_types" }
ic-types = { path = "../types/types" }
async-trait = "0.1.36"
futures-util = "0.3.21"
hyper = { version = "0.14.18", features = ["client", "tcp", "http1", "http2"] }
hyper-tls = "0.5.0"
itertools = "0.10.3"
native-tls = { version = "0.2.7", features = ["alpn"] }
prost = "0.11.0"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
serde_cbor = "0.11.1"
tokio = { version = "1.24.2", features = [ "macros", "time" ] }
tree-deserializer = { path = "../tree_deserializer" }
url = "2.1.1"

[dev-dependencies]
hex = "0.4.2"
ic-crypto-test-utils = { path = "../crypto/test_utils" }
ic-certification-test-utils = { path = "../certification/test-utils" }
ic-test-utilities = { path = "../test_utilities" }
ic-validator = { path = "../validator" }
openssl = "0.10.29"
rand = "0.8"
rand_chacha = "0.3"
tokio-test = "0.4.0"
