[package]
name = "ic-canister-client"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
backoff = { workspace = true }
ic-crypto-ecdsa-secp256k1 = { path = "../crypto/ecdsa_secp256k1" }
ic-canister-client-sender = { path = "./sender" }
ic-canonical-state = { path = "../canonical_state" }
ic-certification = { path = "../certification" }
ic-crypto-tree-hash = { path = "../crypto/tree_hash" }
ic-crypto-utils-threshold-sig-der = { path = "../crypto/utils/threshold_sig_der" }
ic-protobuf = { path = "../protobuf" }
ic-ic00-types = { path = "../types/ic00_types" }
ic-types = { path = "../types/types" }
async-trait = "0.1.36"
futures-util = "0.3.21"
hyper = { version = "0.14.18", features = ["client", "tcp", "http1", "http2"] }
hyper-rustls = { version = "0.24.0", features = ["http2"] }
itertools = { workspace = true }
prost = { workspace = true }
rustls = { version = "^0.21.0", features = ["dangerous_configuration"] }
serde = { workspace = true }
serde_bytes = { workspace = true }
serde_cbor = { workspace = true }
tokio = { workspace = true }
tree-deserializer = { path = "../tree_deserializer" }
url = "2.1.1"

[dev-dependencies]
hex = "0.4.2"
ic-certification-test-utils = { path = "../certification/test-utils" }
ic-crypto-test-utils-reproducible-rng = { path = "../crypto/test_utils/reproducible_rng" }
ic-crypto-test-utils-root-of-trust = { path = "../crypto/test_utils/root_of_trust" }
ic-crypto-test-utils-tls = { path = "../crypto/test_utils/tls" }
ic-test-utilities = { path = "../test_utilities" }
ic-validator = { path = "../validator" }
rand = "0.8"
rand_chacha = "0.3"
tokio-test = "0.4.0"
