[package]
name = "ic-crypto-test-utils-canister-sigs"
version = "0.8.0"
edition = "2021"

[dependencies]
ic-certification-test-utils = { path = "../../../certification/test-utils" }
ic-crypto-internal-basic-sig-iccsa = { path = "../../internal/crypto_lib/basic_sig/iccsa" }
ic-crypto-internal-basic-sig-iccsa-test-utils = { path = "../../internal/crypto_lib/basic_sig/iccsa/test_utils" }
ic-crypto-internal-types = { path= "../../../crypto/internal/crypto_lib/types" }
ic-crypto-temp-crypto = { path = "../../temp_crypto" }
ic-crypto-test-utils = { path = ".." }
ic-interfaces-registry = { path = "../../../interfaces/registry" }
ic-protobuf = { path = "../../../protobuf" }
ic-registry-client-fake = { path = "../../../registry/fake" }
ic-registry-keys = { path = "../../../registry/keys" }
ic-registry-proto-data-provider = { path = "../../../registry/proto_data_provider" }
ic-types = { path = "../../../types/types" }
ic-types-test-utils = { path = "../../../types/types_test_utils" }
rand = "0.8.3"
rand_chacha = "0.3"
serde = { version = "1.0.99", features = [ "derive" ] }
serde_cbor = "0.11.1"
