[package]
name = "ic-canister-http-adapter"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-socks5 = "0.5.1"
async-stream = "0.3.2"
byte-unit = "4.0.14"
clap = { version = "3.1.6", features = ["derive"] }
futures = "0.3.17"
futures-core = "0.3.21"
http = "0.2"
hyper = { version = "0.14.18", features = ["full"] }
hyper-socks2 = "0.6.0"
hyper-tls = "0.5.0"
ic-adapter-metrics-server = { path = "../../monitoring/adapter_metrics_server" }
ic-async-utils = { path = "../../async_utils" }
ic-canister-http-service = { path = "../service" }
ic-config = { path = "../../config" }
ic-logger = { path = "../../monitoring/logger" }
ic-metrics = { path = "../../monitoring/metrics" }
itertools = "0.10.3"
prometheus = { version = "0.12.0", features = [ "process" ] }
prost = "0.11.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
slog = "2.7.0"
slog-async = "2.7.0"
thiserror = "1.0.26"
tokio = { version = "1.23.1", features = ["full"] }
tonic = "0.8.2"
tower =  { version = "0.4.8", features = ["load-shed", "limit", "steer"] }

[dev-dependencies]
once_cell = "1.13.1"
rand = "0.8.4"
warp = { version = "0.3.2", features = ["tls"] }
uuid = { version = "0.8.2", features = ["v4"] }
tempfile = "3.3.0"
