[package]
name = "ic-crypto-tree-hash-test-utils"
version = "0.8.0"
edition = "2021"

[dependencies]
assert_matches = "1.5.0"
ic-crypto-tree-hash = { path = ".." }
proptest = "1.0"
rand = "0.8.4"
thiserror = "1.0"

[dev-dependencies]
ic-crypto-test-utils-reproducible-rng = { path = "../../test_utils/reproducible_rng" }