[package]
name = "ic-icos-sev-interfaces"
version = "0.8.0"
edition = "2021"

[dependencies]
async-trait = "0.1.41"
ic-types = { path = "../../types/types" }
thiserror = "1"
tokio = { version = "1.32.0", features = ["full"] }
