prod-nightly-pipeline:
  extends: .rules-rollout-pipeline-auto
  variables:
    CD_ENV: "NIGHTLY"
    TESTNET1: "cdnightly"
    TESTNET2: "cdrc01"
    TESTNET3: "cdrc02"
    TESTNET4: "cdrc03"
    TESTNET5: "cdrc04"
    DISKIMG_BRANCH: "${CI_COMMIT_SHA}"
    PARENT_PIPELINE_ID: "${CI_PIPELINE_ID}"
  trigger:
    include:
      - local: gitlab-ci/config/child-pipeline--prod.yml
    strategy: depend

prod-nightly-triggered:
  # Support running a nightly test in a "triggered" pipeline
  # https://docs.gitlab.com/ee/api/pipeline_triggers.html
  extends: .rules-rollout-pipeline-run-on-trigger
  needs: []
  variables:
    CD_ENV: "NIGHTLY"
    TESTNET1: "cdnightly"
    TESTNET2: "cdrc01"
    TESTNET3: "cdrc02"
    TESTNET4: "cdrc03"
    TESTNET5: "cdrc04"
    DISKIMG_BRANCH: "${CI_COMMIT_SHA}"
    PARENT_PIPELINE_ID: "${CI_PIPELINE_ID}"
  trigger:
    include:
      - local: gitlab-ci/config/child-pipeline--prod.yml
    strategy: depend
