[package]
name = "denylist-updater"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.58"
async-trait = "0.1.56"
axum = "0.6.1"
chacha20poly1305 = "0.10.0"
clap = { version = "3.2.6", features = ["derive"] }
flate2 = "1.0.24"
futures = "0.3.21"
httptest = "0.15.4"
mockall = "0.11.1"
nix = { version = "0.24.2", features = ["signal"] }
opentelemetry = { version = "0.20", features = ["metrics"] }
opentelemetry-prometheus = "0.13.0"
prometheus = "0.13.3"
reqwest = { version = "0.11.11", features = ["json"] }
rsa = "0.9.2"
serde = { version = "1.0.139", features = ["serde_derive"] }
serde_json = "1.0.82"
sha2 = "0.10.2"
tar = "0.4.38"
tempfile = "3.3.0"
tokio = { version = "1.19.2", features = ["full"] }
tracing = "0.1.35"
tracing-subscriber = { version = "0.3.11", features = ["json"] }
