[package]
name = "ic-nervous-system-common-test-keys"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
ic-canister-client-sender = { path = "../../../canister_client/sender" }
ic-base-types = { path = "../../../types/base_types" }
ic-types = { path = "../../../types/types" }
lazy_static = "1.4.0"
rand = "0.8"
rand_chacha = "0.3"
url = "2.3.1"