[package]
name = "ic-interfaces-transport-mocks"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
ic-interfaces-transport = { path = "../" }
ic-base-types = { path = "../../../types/base_types" }
mockall = "0.11.2"
