[package]
name = "ic-nns-integration-tests"
version = "0.8.0"
edition = "2021"

[[bin]]
name = "mem-utils-test-canister"
path = "test_canisters/mem_utils_test.rs"

[[bin]]
name = "governance-mem-test-canister"
path = "test_canisters/governance_mem_test_canister.rs"

[[bin]]
name = "governance-memory-migration-test-canister"
path = "test_canisters/governance_memory_migration_test_canister.rs"

# Dependencies required to compile the test canisters.
[dependencies]
async-trait = "0.1.42"
assert_matches = "1.4.0"
bytes = "1.0.1"
candid = { workspace = true }
cycles-minting-canister = {path = "../../nns/cmc"}
dfn_candid = { path = "../../rust_canisters/dfn_candid" }
dfn_protobuf = { path = "../../rust_canisters/dfn_protobuf" }
dfn_core = { path = "../../rust_canisters/dfn_core" }
dfn_json = { path = "../../rust_canisters/dfn_json" }
futures = "0.3.8"
ic-base-types = { path = "../../types/base_types" }
ic-ledger-core = { path = "../../rosetta-api/ledger_core" }
ic-nervous-system-clients = { path = "../../nervous_system/clients" }
ic-nervous-system-common = { path = "../../nervous_system/common" }
ic-nns-common = { path = "../common" }
ic-nns-governance = { path = "../governance" }
ic-sns-swap = { path = "../../sns/swap" }
ic-stable-structures = { workspace = true }
icp-ledger = { path = "../../rosetta-api/icp_ledger" }
lifeline = { path = "../handlers/lifeline/impl" }
prost = "0.11.0"
strum = "0.23.0"
lazy_static = "1.4.0"

# Dependencies required to compile the tests.
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
canister-test = { path = "../../rust_canisters/canister_test" }
crossbeam = "0.8.0"
crossbeam-channel = "0.5.5"
futures-util = "0.3.8"
hex = "0.4.2"
ic-canister-client-sender = { path = "../../canister_client/sender" }
ic-config = { path = "../../config" }
ic-crypto = { path = "../../crypto" }
ic-crypto-sha2 = { path = "../../crypto/sha2" }
ic-error-types = {path="../../types/error_types"}
ic-ic00-types = {path="../../types/ic00_types"}
ic-nervous-system-common-test-keys = { path = "../../nervous_system/common/test_keys" }
ic-nervous-system-root = { path = "../../nervous_system/root" }
ic-nns-constants = { path = "../constants" }
ic-nns-handler-root = { path = "../handlers/root/impl" }
ic-nns-gtc = { path = "../gtc" }
ic-nns-test-utils = { path = "../../nns/test_utils" }
ic-nns-test-utils-macros = { path = "../../nns/test_utils_macros" }
ic-sns-wasm = { path = "../sns-wasm" }
ic-sns-init = { path = "../../sns/init" }
ic-protobuf = { path = "../../protobuf" }
ic-registry-keys = { path = "../../registry/keys" }
ic-registry-routing-table = { path = "../../registry/routing_table" }
ic-registry-subnet-type = { path = "../../registry/subnet_type" }
ic-registry-transport = { path = "../../registry/transport" }
ic-state-machine-tests = { path = "../../state_machine_tests" }
ic-test-utilities = { path = "../../test_utilities" }
ic-types = { path = "../../types/types" }
ic-types-test-utils = { path = "../../types/types_test_utils" }
ic-xrc-types = "1.0.0"
libsecp256k1 = "0.5.0"
maplit = "1.0.2"
on_wire = { path = "../../rust_canisters/on_wire" }
phantom_newtype = { path = "../../phantom_newtype" }
rand = "0.8"
registry-canister = { path = "../../registry/canister" }
rustc-hash = "1.1.0"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.15.0", features = ["full"] }
wat = "1.0.52"
assert_matches = "1.3.0"
xrc-mock = { path = "../../rosetta-api/tvl/xrc_mock" }
