[package]
name = "memory_tracker"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-vec = "0.6.3"
ic-logger = { path = "../monitoring/logger" }
ic-config = { path = "../config" }
ic-replicated-state = { path = "../replicated_state" }
ic-sys = { path = "../sys" }
ic-utils = { path = "../utils" }
libc = "0.2.91"
nix = { workspace = true }
slog = { workspace = true }
lazy_static = "1.4.0"

[features]
default = []
sigsegv_handler_checksum = []

[dev-dependencies]
ic-types = { path = "../types/types" }
tempfile = "3.1.0"
criterion = "0.5"
proptest = "1.0"

[[bench]]
name = "traps"
harness = false
