[package]
name = "ic-sns-swap"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "sns-swap-canister"
path = "canister/canister.rs"

[lib]
path = "src/lib.rs"

[[test]]
name = "swap-test"
path = "tests/swap.rs"

[dependencies]
# This MUST be kept in sync with build-info-build in the [build-dependencies] section!
build-info = { version = "0.0.26", default-features = false, features = [] }

async-trait = "0.1.42"
bytes = "1.0.1"
candid = "0.8.1"
comparable = { version = "0.5.1", features = ["derive"] }
dfn_candid = { path = "../../rust_canisters/dfn_candid" }
dfn_core = { path = "../../rust_canisters/dfn_core" }
dfn_http_metrics = { path = "../../rust_canisters/dfn_http_metrics" }
dfn_protobuf = { path = "../../rust_canisters/dfn_protobuf" }
hex = "0.4.3"
ic-base-types = { path = "../../types/base_types" }
ic-crypto-sha = { path = "../../crypto/sha/" }
ic-ic00-types = { path = "../../types/ic00_types" }
ic-icrc1 = { path = "../../rosetta-api/icrc1" }
ic-ledger-core = { path = "../../rosetta-api/ledger_core" }
ic-metrics-encoder = "1"
ic-nervous-system-common = { path = "../../nervous_system/common" }
ic-nervous-system-root = { path = "../../nervous_system/root" }
ic-protobuf = { path = "../../protobuf" }
ic-sns-governance = { path = "../governance" }
# TODO(NNS1-1589): Delete hack, and uncomment this.
# ic-sns-root = { path = "../root" }
icp-ledger = { path = "../../rosetta-api/icp_ledger" }
itertools = "0.10.5"
lazy_static = "1.4.0"
on_wire = { path = "../../rust_canisters/on_wire" }
prost = "0.11.0"
rand = "0.8"
rand_chacha = "0.3"
registry-canister = { path = "../../registry/canister" }
rust_decimal = "1.25"
serde = { version = "1.0", features = ["derive"] }
strum = "0.18.0"
strum_macros = "0.18.0"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
assert_matches = "1.3.0"
ic-types = { path = "../../types/types" }
maplit = "1.0.2"


[build-dependencies]
# This MUST be kept in sync with build-info in the [dependencies] section!
build-info-build = { version = "0.0.26", default-features = false, features = [
] }

ic-base-types = { path = "../../types/base_types" }
prost-build = "0.11.0"

[dev-dependencies]
criterion = "0.3"
ic-config = { path = "../../config" }
proptest = "1.0"
pretty_assertions = "1.0"
ic-base-types = { path = "../../types/base_types" }
ic-nns-common = { path = "../../nns/common" }
ic-nervous-system-common-test-keys = { path = "../../nervous_system/common/test_keys" }
ic-nervous-system-common-test-utils = { path = "../../nervous_system/common/test_utils" }
ic-sns-swap-protobuf-generator = { path = "./protobuf_generator" }
ic-test-utilities-compare-dirs = { path = "../../test_utilities/compare_dirs" }
futures = "0.3.13"
maplit = "1.0.2"
tempfile = "3.1.0"
tokio = { version = "1.23.1", features = ["full"] }
tokio-test = "0.4.2"

[features]
test = [
    # TODO(NNS1-1589): Uncomment.
    # "ic-sns-root/test",
]
