[package]
name = "ic-nns-gtc"
version = "0.8.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[[bin]]
name = "genesis-token-canister"
path = "canister/canister.rs"

[dependencies]
# This MUST be kept in sync with build-info-build in the [build-dependencies] section!
build-info = { version = "0.0.26", default-features = false, features = [] }

candid = "0.7.4"
dfn_candid = { path = "../../rust_canisters/dfn_candid" }
dfn_core = { path = "../../rust_canisters/dfn_core" }
hex = "0.4.2"
hex-literal = "0.3.1"
ic-base-types = { path = "../../types/base_types" }
ic-crypto-sha = {path = "../../crypto/sha/"}
ic-nervous-system-common-build-metadata = { path = "../../nervous_system/common/build_metadata" }
ic-nns-governance = { path = "../governance" }
ic-nns-common = { path = "../common" }
ic-nns-constants = { path = "../constants" }
ic-nns-gtc-accounts = { path = "../gtc_accounts" }
lazy_static = "1.4.0"
ledger-canister = { path = "../../rosetta-api/ledger_canister" }
libsecp256k1 = "0.5.0"
prost = "0.10.4"
rand = "0.7.3"
rand_core = "0.5.1"
serde = { version = "1.0", features = ["derive"] }
sha3 = "0.9.1"
simple_asn1 = "0.6.1"

[dev-dependencies]
ic-nns-gtc-protobuf-generator = { path = "./protobuf_generator" }
ic-test-utilities-compare-dirs = { path = "../../test_utilities/compare_dirs" }
tempfile = "3.1.0"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
canister-test = { path = "../../rust_canisters/canister_test" }
ic-nns-test-utils = { path = "../../nns/test_utils" }
ic-nns-test-utils-macros = { path="../../nns/test_utils_macros" }

[build-dependencies]
# This MUST be kept in sync with build-info in the [dependencies] section!
build-info-build = { version="0.0.26", default-features = false, features = [] }
