title = "Motoko QR workload"
description = "Motoko's QR benchmark from: https://github.com/dfinity/motoko/blob/master/test/perf/qr.mo"

[[workload]]
canister = "qr#1"
raw_payload = "4449444C0000"
method = "Update"
call_method = "go"
rps_ratio = 0.1

[[workload]]
canister = "qr#2"
raw_payload = "4449444C0000"
method = "Update"
call_method = "go"
rps = 1                      # Constant 1 rps for the second qr code canister

# https://fxa77-fiaaa-aaaae-aaana-cai.raw.ic0.app/explain shows
#
# 44 49 44 4c: magic header
# 00: type table of size 0
# 00: arg count of 0
