title = "Exchange rate canister benchmark"
description = "Stress the exchange rate canister from a variety of other canisters via canister calls"

# The xrc canister only needs to be installed. It is not directly stressed, but via the xrc_demo canister.
install_canisters = ["xrc"]

[[workload]]
canister = "xrc_demo"
rate = 0.333
call_method = "get_exchange_rate"
method = "Update"
raw_payload = "4449444c00027171034943500455534454"
subnet = 1

[[workload]]
canister = "xrc_demo#2"
rate = 0.333
call_method = "get_exchange_rate"
method = "Update"
raw_payload = "4449444c0002717103534f4c0455534454"
subnet = 2

[[workload]]
canister = "xrc_demo#3"
rate = 0.333
call_method = "get_exchange_rate"
method = "Update"
raw_payload = "4449444c0002717103534f4c03494350"
subnet = 3

# XDR demo code as well as XDR canister wasm is here:
# https://github.com/DFINITY-skaestle/xrc_benchmark
#
# Payload is:
# $ didc encode '( "ICP", "USDT" )'
# 4449444c00027171034943500455534454
#
# $ didc encode '( "SOL", "USDT" )'
# 4449444c0002717103534f4c0455534454
#
# $ didc encode '( "SOL", "ICP" )'
# 4449444c0002717103534f4c03494350
