[package]
name = "ic-icrc1-client-cdk"
version = "0.8.0"
authors = ["The Internet Computer Project Developers"]
description = "ICRC-1 compliant client library."
edition = "2021"

[dependencies]
async-trait = "0.1.53"
ic-cdk = { workspace = true }
ic-icrc1-client = { path = ".." }
candid = { workspace = true }
