[package]
name = "ic-wasm-types"
version = "0.8.0"
edition = "2021"

[dependencies]
ic-crypto-sha2 = { path = "../../crypto/sha2" }
ic-protobuf = { path = "../../protobuf" }
ic-sys = { path = "../../sys" }
ic-types = { path = "../types" }
ic-utils = { path = "../../utils" }
serde = { version = "1.0.99", features = ["derive"] }
