[package]
name = "ic-canister-sandbox-backend-lib"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
ic-base-types = { path = "../../types/base_types" }
ic-canister-sandbox-common  = { path = "../common" }
ic-cycles-account-manager = { path = "../../cycles_account_manager" }
ic-config = { path = "../../config" }
ic-constants = { path = "../../constants" }
ic-embedders = { path = "../../embedders" }
ic-logger = { path = "../../monitoring/logger" }
ic-types = { path = "../../types/types" }
ic-replicated-state = { path = "../../replicated_state"}
ic-interfaces = { path = "../../interfaces" }
ic-wasm-types = { path = "../../types/wasm_types" }
ic-utils = { path = "../../utils"}
ic-sys = { path = "../../sys"}
ic-system-api = { path = "../../system_api" }
libc = "0.2.119"
libflate = "1.1.2"
memory_tracker = { path = "../../memory_tracker" }
nix = { workspace = true }
serde_json = { workspace = true }
slog = { workspace = true }
threadpool = "1.8.1"
rayon = "1.5.1"

[dev-dependencies]
ic-registry-routing-table = { path = "../../registry/routing_table" }
ic-registry-subnet-type = { path = "../../registry/subnet_type" }
ic-test-utilities = { path = "../../test_utilities" }
mockall = { workspace = true }
wat = "1.0.52"

[features]
sigsegv_handler_checksum = [ "memory_tracker/sigsegv_handler_checksum" ]
