[package]
name = "certificate_orchestrator"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "certificate_orchestrator"
path = "src/main.rs"

[dependencies.certificate_orchestrator_interface]
path = "../certificate_orchestrator_interface"

[dependencies]
anyhow = "1.0.66"
bincode = "1.3.3"
candid = { workspace = true }
cfg-if = "1.0.0"
hex = "0.4.3"
ic-cdk = { workspace = true }
ic-cdk-timers = { workspace = true }
ic-cdk-macros = { workspace = true }
ic-certified-map = "0.3.2"
ic-stable-structures = { workspace = true }
mockall = "0.11.3"
priority-queue = { version = "1.3.0", features = ["serde"] }
prometheus = "0.13.3"
publicsuffix = "2.2.3"
serde = "1.0.147"
serde_cbor = "0.11.2"
sha2 = "0.10.6"
thiserror = "1.0.37"
