[package]
name = "ic-test-identity"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
ic-canister-client-sender = { path = "../../canister_client/sender" }
ic-types = { path = "../../types/types" }
ic-crypto-utils-basic-sig = { path = "../../crypto/utils/basic_sig" }
ic-crypto-internal-types = { path = "../../crypto/internal/crypto_lib/types" }
lazy_static = "1.4.0"
rand = "0.8"
rand_chacha = "0.3"