[package]
name = "ic-peer-manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ic-interfaces = { path = "../../interfaces" }
ic-interfaces-registry = { path = "../../interfaces/registry" }
ic-base-types = { path = "../../types/base_types" }
ic-logger = { path = "../../monitoring/logger" }
ic-metrics = { path = "../../monitoring/metrics" }
ic-registry-client-helpers = { path = "../../registry/helpers" }
prometheus = { version = "0.12.0", features = [ "process" ] }
serde = { version = "1.0.99", features = [ "derive" ] }
slog = { version = "2.5.2", features = ["nested-values", "release_max_level_debug"] }
tokio = { version = "1.32.0", features = ["full"] }

[dev-dependencies]
ic-p2p-test-utils = { path = "../test_utils" }
ic-types-test-utils = { path = "../../types/types_test_utils" }
ic-test-utilities-logger = { path = "../../test_utilities/logger" }
