[package]
name = "ic-rosetta-test-utils"
version = "0.8.0"
authors = ["The Internet Computer Project Developers"]
edition = "2021"

[dependencies]
base64 = "0.11"
hex = "0.4.2"
ic-canister-client-sender = { path = "../../canister_client/sender" }
ic-rosetta-api = { path = "../" }
ic-types = { path = "../../types/types" }
icp-ledger = { path = "../icp_ledger" }
log = "0.4.14"
nix = "0.23.0"
rand = "0.8"
serde = { version = "1.0.99", features = ["derive"] }
serde_json = "1.0"
slog = { version = "2.5.2", features = ["release_max_level_trace"] }
tempfile = "3.1.0"
reqwest = "0.11.1"
tokio = { version = "1.32.0", features = ["full"] }
url = "2.1.1"
