[package]
name = "ic-transport-test-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.2.0"
futures = "0.3.25"
ic-base-types = { path = "../../types/base_types" }
ic-config = { path = "../../config" }
ic-crypto-temp-crypto = { path = "../../crypto/temp_crypto" }
ic-crypto-tls-interfaces = { path = "../../crypto/tls_interfaces" }
ic-interfaces-transport = { path = "../../interfaces/transport" }
ic-logger = { path = "../../monitoring/logger" }
ic-metrics = { path = "../../monitoring/metrics" }
ic-registry-client-fake = { path = "../../registry/fake" }
ic-registry-keys = { path = "../../registry/keys" }
ic-registry-proto-data-provider = { path = "../../registry/proto_data_provider" }
ic-test-utilities-logger = { path = "../../test_utilities/logger" }
ic-transport = { path = "../../transport" }
ic-types-test-utils = { path = "../../types/types_test_utils"}
mockall = "0.11.2"
tokio = { version = "1.23.1", features = ["full"] }
tower = "0.4.12"
tower-test = "0.4.0"
