[package]
name = "vector_config_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.31"
clap = { version = "4.3.0", features = ["derive"] }
crossbeam = "0.8.0"
crossbeam-channel = "0.5.5"
futures-util = "0.3.5"
humantime = "2.0"
ic-async-utils = { path = "../../async_utils" }
ic-metrics = { path = "../../monitoring/metrics" }
ic-types = { path = "../../types/types" }
ic-utils = { path = "../../utils/" }
ic-registry-local-registry = { path = "../../registry/local_registry" }
ic-interfaces-registry = { path = "../../interfaces/registry" }
ic-registry-nns-data-provider = { path = "../../registry/nns_data_provider" }
regex = "1.7.0"
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0.54"
service-discovery = { path = "../service_discovery" }
slog = { version = "2.5.2", features = ["nested-values"] }
slog-async = { version = "2.5", features = ["nested-values"] }
slog-term = "2.6.0"
tokio = { version = "1.15.0", features = ["full"] }
url = { version = "2.1.1", features = ["serde"] }
config_writer_common = { path = "../config_writer_common" }
ic-http-endpoints-metrics = { path = "../../http_endpoints/metrics" }
ic-config = { path = "../../config" }

[[bin]]
name = "vector_config_generator"
path = "src/main.rs"
