[package]
name = "ic-icp-index"
version = "0.8.0"
authors = ["The Internet Computer Project Developers"]
description = "Index canister for the ICP Ledger"
edition = "2018"

[[bin]]
name = "ic-icp-index"
path = "src/main.rs"

[dependencies]
candid = { workspace = true }
ciborium = { workspace = true }
ic-cdk = { workspace = true }
ic-cdk-macros = { workspace = true }
ic-cdk-timers = { workspace = true }
ic-ledger-core = { path = "../../ledger_core" }
ic-stable-structures = { workspace = true }
icrc-ledger-types = { path = "../../../../packages/icrc-ledger-types" }
icp-ledger = { path = "../" }
num-traits = "0.2.14"
scopeguard = "1.1.0"
serde = "1.0"
ic-canisters-http-types = { path = "../../../rust_canisters/http_types" }
ic-metrics-encoder = "1.1"
ic-canister-log = { path = "../../../rust_canisters/canister_log" }
serde_json = "1.0.40"
ic-icrc1-index-ng = {path ="../../icrc1/index-ng"}

[dev-dependencies]
ic-base-types = { path = "../../../types/base_types" }
ic-ledger-canister-core = { path = "../../ledger_canister_core" }
ic-state-machine-tests = { path = "../../../state_machine_tests" }
ic-test-utilities-load-wasm = { path = "../../../test_utilities/load_wasm" }
ic-icrc1 = { path = "../../icrc1" }
ic-icp-index = { path = "./" }
serde_bytes = "0.11"

