[package]
name = "ic-artifact-pool"
version = "0.8.0"
authors = ["The Internet Computer Project Developers"]
edition = "2021"

[dependencies]
bincode = "1.2.1"
byteorder = "1.3.4"
clap = { version = "3.1.6", features = ["derive"] }
ic-config = { path = "../config" }
ic-constants = { path = "../constants" }
ic-interfaces = { path = "../interfaces" }
ic-logger = { path = "../monitoring/logger" }
ic-metrics = { path = "../monitoring/metrics" }
ic-protobuf = { path = "../protobuf" }
ic-types = { path = "../types/types" }
ic-utils = { path = "../utils" }
prometheus = { version = "0.12.0", features = ["process"] }
lmdb-rkv = { git = "https://github.com/dfinity-lab/lmdb-rs", rev = "1cf86b5cc09947e94a787065cadd163a42ef7f18" }
prost = "0.11.0"
rocksdb = { version = "0.15.0", optional = true }
serde = { version = "1.0.99", features = ["derive"] }
serde_json = "1.0.40"
serde-bytes-repr = "0.1.5"
slog = { version = "2.5.2", features = [
    "nested-values",
    "release_max_level_debug",
] }
strum = "0.23.0"
tempfile = "3.1.0"
lmdb-rkv-sys = { git = "https://github.com/dfinity-lab/lmdb-rs", rev = "1cf86b5cc09947e94a787065cadd163a42ef7f18" }
nix = "0.23.0"

[dev-dependencies]
criterion = "0.5"
ic-crypto-test-utils-canister-threshold-sigs = { path = "../crypto/test_utils/canister_threshold_sigs" }
ic-ic00-types = { path = "../types/ic00_types" }
ic-test-artifact-pool = { path = "../test_utilities/artifact_pool" }
ic-test-utilities = { path = "../test_utilities" }
ic-test-utilities-logger = { path = "../test_utilities/logger" }
ic-test-utilities-registry = { path = "../test_utilities/registry" }
slog-term = "2.6.0"
slog-envlogger = "2.2.0"
slog-async = "2.5.0"
tempfile = "3.1.0"
rand = "0.8"

[[bench]]
name = "load_blocks"
harness = false

[features]
default = ["rocksdb_backend"]
rocksdb_backend = ["rocksdb"]

[[bin]]
name = "ic-consensus-pool-util"
path = "src/bin/consensus_pool_util.rs"
