[package]
name = "ic-adapter-metrics"
version = "0.8.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ic-adapter-metrics-service = { path = "../adapter_metrics_service" }
ic-async-utils = { path = "../../async_utils" }
prometheus = "0.12.0"
protobuf = "2.27.1"
slog = "2.7.0"
slog-async = "2.7.0"
tokio = { version = "1.32.0", features = ["full"] }
tonic = { workspace = true }
tower = { workspace = true }
