[package]
name = "ic-crypto-internal-basic-sig-iccsa"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
hex = "0.4.2"
base64 = { workspace = true }
ic-certification = { path = "../../../../../certification" }
ic-crypto-internal-basic-sig-der-utils = { path = "../der_utils" }
ic-crypto-internal-types = { path = "../../../crypto_lib/types" }
ic-crypto-tree-hash = { path = "../../../../tree_hash" }
ic-crypto-sha2 = { path = "../../../../sha2" }
ic-types = { path = "../../../../../types/types" }
serde = { workspace = true }
serde_bytes = { workspace = true }
serde_cbor = { workspace = true }
simple_asn1 = { workspace = true }

[dev-dependencies]
# TODO (CRP-912) Replace ic-crypto with ic-crypto-utils-threshold-sig
assert_matches = "1.5.0"
ic-certification-test-utils = { path = "../../../../../certification/test-utils" }
ic-crypto-internal-basic-sig-iccsa-test-utils = { path = "test_utils" }
ic-crypto-test-utils-reproducible-rng = { path = "../../../../../crypto/test_utils/reproducible_rng" }
ic-crypto = { path = "../../../../../crypto" }
ic-crypto-internal-test-vectors = { path = "../../../test_vectors" }
ic-crypto-test-utils = { path = "../../../../test_utils" }
ic-interfaces = { path = "../../../../../interfaces" }
rand = "0.8.3"
