[package]
name = "ic-embedders"
version = "0.8.0"
edition = "2021"

[dependencies]
anyhow = "1.0.31"
ic-config = { path = "../config" }
ic-cycles-account-manager = { path = "../cycles_account_manager" }
ic-interfaces = { path = "../interfaces" }
ic-logger = { path = "../monitoring/logger" }
ic-registry-subnet-type = { path = "../registry/subnet_type" }
ic-replicated-state = { path = "../replicated_state" }
ic-sys = { path = "../sys" }
ic-system-api = { path = "../system_api" }
ic-metrics = { path = "../monitoring/metrics" }
ic-types = { path = "../types/types" }
ic-utils = { path = "../utils" }
ic-wasm-types = { path = "../types/wasm_types" }
libc = "0.2.91"
libflate = "1.1.2"
memory_tracker = { path = "../memory_tracker" }
nix = "0.23.0"
prometheus = { version = "0.12.0", features = [ "process" ] }
serde = { version = "1.0.99", features = [ "derive" ] }
serde_bytes = "0.11"
slog = { version = "2.5.2", features = ["nested-values", "release_max_level_debug"] }
slog-term = "2.6.0"
wasmtime = { version = "4.0.1", default_features = false, features = ['cranelift', 'parallel-compilation', 'posix-signals-on-macos'] }
wasmtime-environ = "4.0.0"
wasmtime-runtime =  "4.0.0"
wasm-encoder = "0.20.0"
wasmparser = "0.95.0"
rayon = "1.5.1"


[dev-dependencies]
embedders_bench = { path = "benches/embedders_bench" }
candid = "0.8.1"
canister-test = { path = "../rust_canisters/canister_test" }
criterion = { version = "0.3", features = ["html_reports"] }
ic-registry-routing-table = { path = "../registry/routing_table" }
ic-system-api = { path = "../system_api" }
ic-test-utilities = { path = "../test_utilities" }
ic-test-utilities-logger = { path = "../test_utilities/logger" }
ic-test-utilities-execution-environment = { path = "../test_utilities/execution_environment" }
lazy_static = "1.4.0"
maplit = "1.0.2"
proptest = "1.0"
slog = { version = "2.5.2", features = ["nested-values", "release_max_level_debug"] }
assert_matches = "1.3.0"
insta = "1.8.0"
pretty_assertions = "0.6.1"
wasmprinter = "0.2.45"
wast = "48.0.0"
wat = "1.0.52"


[[bin]]
name = "instrument-wasm"
path = "src/wasm_utils/instrument_wasm.rs"

[[bench]]
name = "compilation"
harness = false
