[package]
name = "ic-canister-sandbox-launcher"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[build-dependencies]
cc = "1.0"

[dependencies]
ic-canister-sandbox-common = { path = "../common" }
ic-types = { path = "../../types/types" }
nix = { workspace = true }

[dev-dependencies]
# This makes the dependencies of the binary more consistent
# with the dependencies of execution environment tests and
# allows the binary to reuse most of the build artifacts
# produced by `cargo test`.
ic-test-utilities = { path = "../../test_utilities" }

[[bin]]
name = "sandbox_launcher"
path = "bin/sandbox_launcher.rs"

# This feature doesn't actually do anything. It is just convenient because it
# allows us to use the same cargo flags for building sandbox_launcher as we have
# for canister_sandbox.
[features]
sigsegv_handler_checksum = []
