[package]
name = "ic-ckbtc-minter"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ic-ckbtc-minter"
path = "src/main.rs"

[dependencies]
async-trait = "0.1.53"
bech32 = "0.9.0"
bs58 = "0.4.0"
candid = { workspace = true }
ciborium = { workspace = true }
hex = "0.4.3"
ic0 = "0.18.9"
ic-base-types = { path = "../../../types/base_types" }
ic-btc-interface = { workspace = true }
ic-canisters-http-types = { path = "../../../rust_canisters/http_types" }
ic-canister-log = { path = "../../../rust_canisters/canister_log" }
ic-cdk = { workspace = true }
ic-cdk-macros = { workspace = true }
ic-ckbtc-kyt = { path = "../kyt" }
ic-crypto-extended-bip32 = { path = "../../../crypto/extended_bip32" }
ic-crypto-getrandom-for-wasm = { path = "../../../crypto/getrandom_for_wasm" }
ic-crypto-sha2 = { path = "../../../crypto/sha2" }
ic-ic00-types = { path = "../../../types/ic00_types" }
ic-icrc1 = { path = "../../../rosetta-api/icrc1" }
ic-icrc1-client-cdk = { path = "../../../rosetta-api/icrc1/client/cdk" }
ic-ledger-core = { path = "../../../rosetta-api/ledger_core" }
ic-metrics-encoder = "1"
ic-stable-structures = { workspace = true }
icrc-ledger-types = { path = "../../../../packages/icrc-ledger-types" }
lazy_static = "1.4.0"
minicbor = { version = "0.19.1", features = ["alloc", "derive"] }
minicbor-derive = "0.13.0"
num-traits = "0.2.14"
ripemd = "0.1.1"
scopeguard = "1.1.0"
serde = "1.0.136"
serde_bytes = "0.11"
serde_json = "1.0.96"

[dev-dependencies]
assert_matches = "1.5.0"
bitcoin = "0.28.1"
canister-test = { path = "../../../rust_canisters/canister_test" }
ic-config = { path = "../../../config" }
ic-icrc1-ledger = { path = "../../../rosetta-api/icrc1/ledger" }
ic-state-machine-tests = { path = "../../../state_machine_tests" }
ic-test-utilities-load-wasm = { path = "../../../test_utilities/load_wasm" }
ic-bitcoin-canister-mock = { path = "../../mock" }
proptest = "1.0"
simple_asn1 = "0.6.1"
