[package]
name = "ic-crypto-tree-hash-fuzz-check-witness-equality-utils"
version = "0.8.0"
publish = false
edition = "2021"

[dependencies]
ic-canonical-state-tree-hash = { path = "../../../../canonical_state/tree_hash" }
ic-canonical-state-tree-hash-test-utils = { path = "../../../../canonical_state/tree_hash/test_utils" }
ic-crypto-test-utils-reproducible-rng = { path = "../../../test_utils/reproducible_rng" }
ic-crypto-tree-hash = { path = "../.." }
ic-crypto-tree-hash-test-utils = { path = "../../test_utils" }
rand = "0.8"
rand_chacha = "0.3"
