[package]
name = "ic-replica-tests"
version = "0.8.0"
edition = "2021"

[dependencies]
futures = "0.3.13"
ic-async-utils = { path = "../async_utils" }
ic-btc-service = { path = "../bitcoin/service" }
ic-btc-types = { path = "../bitcoin/types/public" }
ic-btc-types-internal = { path = "../bitcoin/types/internal" }
ic-config = { path = "../config" }
ic-canister-client-sender = { path = "../canister_client/sender" }
ic-error-types = { path = "../types/error_types" }
ic-execution-environment = { path = "../execution_environment" }
ic-ic00-types = { path = "../types/ic00_types" }
ic-replica = { path = "../replica" }
ic-registry-client-fake = { path = "../registry/fake" }
ic-registry-client-helpers = { path = "../registry/helpers" }
ic-registry-keys = { path = "../registry/keys" }
ic-registry-proto-data-provider = { path = "../registry/proto_data_provider" }
ic-registry-provisional-whitelist = { path = "../registry/provisional_whitelist" }
ic-registry-subnet-type = { path = "../registry/subnet_type" }
ic-interfaces = { path = "../interfaces" }
ic-interfaces-p2p = { path = "../interfaces/p2p" }
ic-interfaces-registry = { path = "../interfaces/registry" }
ic-interfaces-state-manager = { path = "../interfaces/state_manager" }
ic-logger = { path = "../monitoring/logger" }
ic-metrics = { path = "../monitoring/metrics" }
ic-prep = { path = "../prep" }
ic-protobuf = { path = "../protobuf" }
ic-replicated-state = { path = "../replicated_state" }
ic-state-machine-tests = { path = "../state_machine_tests" }
ic-state-manager = { path = "../state_manager" }
ic-test-utilities = { path = "../test_utilities" }
ic-test-utilities-logger = { path = "../test_utilities/logger" }
ic-crypto = { path = "../crypto" }
ic-types = { path = "../types/types" }
ic-utils = { path = "../utils" }
ic-base-types = { path = "../types/base_types" }
rand = "0.8.4"
slog = { version = "2.5.2", features = ["nested-values", "release_max_level_debug"] }
slog-scope = "4.1.2"
tempfile = "3.3.0"
tonic = "0.8.2"
tokio = { version = "1.23.1", features = ["full"] }
prometheus = { version = "0.12.0", features = [ "process" ] }
prost = "0.11.0"
tower = { version = "0.4.11", features = ["util"] }
wabt = { git = "https://github.com/dfinity-lab/wabt-rs", tag = "0.10.0-dfinity" }

[dev-dependencies]
assert_matches = "1.3.0"
candid = "0.8.1"
canister-test = { path = "../rust_canisters/canister_test" }
ic-crypto-sha = { path = "../crypto/sha" }
ic-registry-provisional-whitelist = { path = "../registry/provisional_whitelist" }
ic-sys = { path = "../sys" }
ic-test-utilities = { path = "../test_utilities" }
maplit = "1.0.2"
predicates = "1.0.1"
