[package]
name = "phantom_newtype"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
candid = { workspace = true }
serde = { workspace = true }
slog = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
