[package]
name = "ic-nervous-system-common"
version = "0.8.0"
edition = "2021"

[lib]
name = "ic_nervous_system_common"
path = "src/lib.rs"

[dependencies]
# This MUST be kept in sync with build-info-build in the [build-dependencies] section!
build-info = { version = "0.0.26", default-features = false, features = [] }

anyhow = "1.0.57"
bytes = { workspace = true }
by_address = "1.1.0"
candid = { workspace = true }
async-trait = "0.1.42"
dfn_core = { path = "../../rust_canisters/dfn_core" }
dfn_candid = { path = "../../rust_canisters/dfn_candid" }
dfn_protobuf = { path = "../../rust_canisters/dfn_protobuf" }
ic-base-types = { path = "../../types/base_types" }
ic-canister-log = { path = "../../rust_canisters/canister_log" }
ic-canisters-http-types = { path = "../../rust_canisters/http_types" }
ic-crypto-sha2 = { path = "../../crypto/sha2" }
ic-ic00-types = { path = "../../types/ic00_types" }
ic-icrc1 = { path = "../../rosetta-api/icrc1" }
ic-ledger-core = { path = "../../rosetta-api/ledger_core" }
ic-metrics-encoder = "1"
ic-nervous-system-runtime = { path = "../runtime" }
icp-ledger = { path = "../../rosetta-api/icp_ledger" }
icrc-ledger-types = { path = "../../../packages/icrc-ledger-types" }
ic-nns-constants = { path = "../../nns/constants" }
ic-stable-structures = { workspace = true }
json5 = "0.4.1"
maplit = "1.0.2"
mockall = "0.11.1"
priority-queue = "1.3.1"
prost = { workspace = true }
rust_decimal = "1.25"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.40"

[build-dependencies]
# This MUST be kept in sync with build-info in the [dependencies] section!
build-info-build = { version = "0.0.26", default-features = false, features = [
] }

[dev-dependencies]
ic-nns-governance = { path = "../../nns/governance" }
proptest = "1.0"
serde_bytes = "0.11"
serde_derive = "1.0"
