[package]
name = "ic-ic00-types"
version = "0.8.0"
edition = "2021"

[dependencies]
arbitrary = { version = "=1.3.0", optional = true }
candid = { workspace = true }
ic-base-types = { path = "../base_types" }
ic-btc-interface = { workspace = true }
ic-btc-types-internal = { path = "../../bitcoin/types/internal" }
ic-error-types = { path = "../error_types" }
ic-protobuf = { path = "../../protobuf" }
num-traits = "0.2.12"
serde = { version = "1.0.99", features = ["derive"] }
serde_bytes = "0.11"
serde_cbor = "0.11.1"
strum = "0.23.0"
strum_macros = "0.23.0"

[features]
fuzzing_code = ["dep:arbitrary"]
