[package]
name = "ic-sns-integration-tests"
version = "0.8.0"
edition = "2021"

[features]
# swap_load_test takes a very long time to run, so to run it you have to pass `--features long_bench`.
long_bench = []


[[bin]]
name = "sns-test-dapp-canister"
path = "test_canisters/test_dapp_canister.rs"

[[bin]]
name = "sns-governance-mem-test-canister"
path = "test_canisters/sns_governance_mem_test_canister.rs"

# Dependencies required to compile the test canisters.
[dependencies]
async-trait = "0.1.42"
byteorder = "1.4.3"
candid = "0.8.1"
dfn_candid = { path = "../../rust_canisters/dfn_candid" }
dfn_core = { path = "../../rust_canisters/dfn_core" }
dfn_json = { path = "../../rust_canisters/dfn_json" }
dfn_protobuf = { path = "../../rust_canisters/dfn_protobuf" }
hex = "0.4.3"
ic-base-types = { path = "../../types/base_types" }
ic-ic00-types = { path = "../../types/ic00_types" }
ic-icrc1 = { path = "../../rosetta-api/icrc1" }
ic-ledger-core = { path = "../../rosetta-api/ledger_core" }
ic-nervous-system-common = { path = "../../nervous_system/common/" }
ic-nns-constants = { path = "../../nns/constants/" }
ic-sns-governance = { path = "../governance" }
ic-sns-init = { path = "../init" }
maplit = "1.0.2"
num-traits = "0.2.14"
pretty-bytes = "0.2.2"
prost = "0.11.0"
rand = "0.8.4"
serde_yaml = "0.8.24"

# Dependencies required to compile the tests.
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
assert_matches = "1.3.0"
canister-test = { path = "../../rust_canisters/canister_test" }
ic-base-types={ path = "../../types/base_types" }
ic-canister-client-sender = { path = "../../canister_client/sender" }
ic-crypto = { path = "../../crypto" }
ic-crypto-sha = { path = "../../crypto/sha" }
ic-nervous-system-common = { path = "../../nervous_system/common" }
ic-nervous-system-common-test-keys = { path = "../../nervous_system/common/test_keys" }
ic-nervous-system-root = { path = "../../nervous_system/root" }
ic-nns-common = { path = "../../nns/common" }
ic-nns-governance = { path = "../../nns/governance" }
ic-nns-test-utils = { path = "../../nns/test_utils/" }
ic-sns-cli = { path = "../cli" }
ic-sns-governance = { path = "../governance", features = ["test"] }
ic-sns-root = { path = "../root" }
ic-sns-swap = { path = "../swap" }
ic-sns-test-utils = { path = "../test_utils" }
ic-sns-wasm = { path = "../../nns/sns-wasm" }
ic-state-machine-tests = { path = "../../state_machine_tests" }
ic-types = { path = "../../types/types" }
itertools = "0.10.3"
lazy_static = "1.4.0"
icp-ledger = { path = "../../rosetta-api/icp_ledger" }
pretty_assertions = "1.0"
on_wire = { path = "../../rust_canisters/on_wire" }
tokio = { version = "1.23.1", features = ["time"] }
wabt = { git = "https://github.com/dfinity-lab/wabt-rs", tag = "0.10.0-dfinity" }
rust_decimal = "1.25"
rust_decimal_macros = "1.25"
rand_chacha = "0.3"
