[package]
name = "ic-pprof"
version = "0.8.0"
edition = "2021"

[dependencies]
async-trait = "0.1.68"
lazy_static = "1.4.0"
pprof = { version = "0.10.1", default-features = false, features = [
    "flamegraph",
    "prost-codec",
] }
prost = { workspace = true }
regex = "1.3.9"
thiserror = "1.0"
tokio = { version = "1.32.0", features = ["full"] }
