[package]
name = "ic-scenario-tests"
version = "0.8.0"
edition = "2021"
autotests = false

[dependencies]
candid = { workspace = true }
canister-test = { path = "../rust_canisters/canister_test" }
chrono = "0.4.19"
clap = { version = "3.1.6", features = ["derive"] }
colored = "2.0.0"
crossbeam-channel = "0.5.5"
dfn_candid = { path = "../rust_canisters/dfn_candid" }
dfn_core = { path = "../rust_canisters/dfn_core" }
dfn_json = { path = "../rust_canisters/dfn_json" }
futures = "0.3.6"
hex = "0.4.2"
ic-base-types = { path = "../types/base_types"}
ic-canister-client = { path = "../canister_client" }
ic-config = { path = "../config" }
ic-crypto = { path = "../crypto" }
ic-crypto-sha2 = { path = "../crypto/sha2" }
ic-interfaces = { path = "../interfaces" }
ic-logger = { path = "../monitoring/logger" }
ic-metrics = { path = "../monitoring/metrics" }
ic-nns-common = { path = "../nns/common" }
ic-nns-constants = { path = "../nns/constants" }
ic-nns-governance = { path = "../nns/governance" }
ic-nns-test-utils = { path = "../nns/test_utils" }
ic-prep = { path = "../prep" }
ic-protobuf = { path = "../protobuf" }
ic-registry-client = { path = "../registry/client" }
ic-registry-client-helpers = { path = "../registry/helpers" }
ic-registry-nns-data-provider-wrappers = { path = "../registry/nns_data_provider_wrappers" }
ic-registry-keys = { path = "../registry/keys" }
ic-registry-provisional-whitelist = { path = "../registry/provisional_whitelist" }
ic-registry-routing-table = { path = "../registry/routing_table" }
ic-registry-subnet-type = { path = "../registry/subnet_type" }
ic-state-manager = { path = "../state_manager" }
ic-test-identity = { path = "../test_utilities/identity" }
ic-test-utilities = { path = "../test_utilities" }
ic-types = { path = "../types/types" }
ic-utils = { path = "../utils" }
lazy_static = "1.4.0"
nix = "0.23.0"
on_wire = { path = "../rust_canisters/on_wire" }
prost = "0.11.0"
registry-canister = { path = "../registry/canister" }
reqwest = "0.11.1"
serde = { version = "1.0.99", features = [ "derive" ] }
serde_json = "1.0"
slog = { version = "2.5.2", features = ["nested-values", "release_max_level_debug"] }
tempfile = "3.1.0"
tester = "0.7.0"
tokio = {version = "1.15.0", features = ["full"]}
url = "2.1.1"
xnet-test = { path = "../rust_canisters/xnet_test" }
ic-nns-handler-root = {path="../nns/handlers/root/impl"}
ic-crypto-internal-types = { path = "../crypto/internal/crypto_lib/types" }
ic-crypto-utils-basic-sig = { path = "../crypto/utils/basic_sig" }
ic-crypto-utils-threshold-sig-der = { path = "../crypto/utils/threshold_sig_der" }

[[bin]]
name = "e2e-test-driver"
path = "src/main.rs"
