[package]
edition = "2021"
name = "ic-execution-environment"
version = "0.8.0"

[dependencies]
candid = { workspace = true }
hex = "0.4.2"
ic-base-types = { path = "../types/base_types" }
ic-btc-interface = { workspace = true }
ic-canister-sandbox-replica-controller = { path = "../canister_sandbox/replica_controller" }
ic-config = { path = "../config" }
ic-constants = { path = "../constants" }
ic-crypto-prng = { path = "../crypto/prng" }
ic-crypto-tecdsa = { path = "../crypto/tecdsa" }
ic-crypto-tree-hash = { path = "../crypto/tree_hash" }
ic-cycles-account-manager = { path = "../cycles_account_manager" }
ic-embedders = { path = "../embedders" }
ic-error-types = { path = "../types/error_types" }
ic-ic00-types = { path = "../types/ic00_types" }
ic-interfaces = { path = "../interfaces" }
ic-interfaces-state-manager = { path = "../interfaces/state_manager" }
ic-logger = { path = "../monitoring/logger" }
ic-metrics = { path = "../monitoring/metrics" }
ic-nns-constants = { path = "../nns/constants" }
ic-registry-provisional-whitelist = { path = "../registry/provisional_whitelist" }
ic-registry-routing-table = { path = "../registry/routing_table" }
ic-registry-subnet-features = { path = "../registry/subnet_features" }
ic-registry-subnet-type = { path = "../registry/subnet_type" }
ic-replicated-state = { path = "../replicated_state" }
ic-state-layout = { path = "../state_layout" }
ic-sys = { path = "../sys" }
ic-system-api = { path = "../system_api" }
ic-types = { path = "../types/types" }
ic-utils = { path = "../utils" }
ic-utils-lru-cache = { path = "../utils/lru_cache" }
ic-wasm-types = { path = "../types/wasm_types" }
lazy_static = "1.4.0"
memory_tracker = { path = "../memory_tracker" }
nix = "0.23.0"
num-rational = "0.2.2"
num-traits = "0.2.12"
phantom_newtype = { path = "../phantom_newtype" }
prometheus = { version = "0.12.0", features = ["process"] }
rand = "0.8"
scoped_threadpool = "0.1.*"
serde = { version = "1.0.99", features = ["derive"] }
serde_cbor = "0.11.1"
slog = { version = "2.5.2", features = ["nested-values", "release_max_level_debug"] }
strum = "0.23.0"
threadpool = "1.8.1"
tokio = { version = "1.17.0", features = ["rt", "sync"] }
tower = { version = "0.4.11", features = ["buffer", "limit", "timeout"] }
wasmparser = "0.100.0"

[dev-dependencies]
assert_matches = "1.3.0"
canister-test = { path = "../rust_canisters/canister_test" }
criterion = { version = "0.5", features = ["html_reports"] }
execution-environment-bench = { path = "benches/lib" }
iai = "0.1"
ic-btc-test-utils = { git = "https://github.com/dfinity/bitcoin-canister", rev = "b1693619e3d4dbc00d8c79e9b6886e1db48b21f7" }
ic-crypto-sha2 = { path = "../crypto/sha2" }
ic-interfaces-state-manager-mocks = { path = "../interfaces/state_manager/mocks" }
ic-state-machine-tests = { path = "../state_machine_tests" }
ic-test-utilities = { path = "../test_utilities" }
ic-test-utilities-execution-environment = { path = "../test_utilities/execution_environment" }
ic-test-utilities-logger = { path = "../test_utilities/logger" }
ic-test-utilities-metrics = { path = "../test_utilities/metrics" }
ic-types-test-utils = { path = "../types/types_test_utils" }
ic-universal-canister = { path = "../universal_canister/lib" }
ic-wasm-types = { path = "../types/wasm_types" }
libflate = "1.1.2"
maplit = "1.0.2"
mockall = "0.7.2"
proptest = "1.0"
tempfile = "3.1.0"
test-strategy = "0.2"
tokio = "1.15.0"
wat = "1.0.52"

[build-dependencies]
escargot = "0.5"

[features]
default = []
sigsegv_handler_checksum = [
	"ic-canister-sandbox-replica-controller/sigsegv_handler_checksum",
	"memory_tracker/sigsegv_handler_checksum",
]

[[bench]]
harness = false
name = "100k_canisters"

[[bench]]
harness = false
name = "execute_inspect_message"

[[bench]]
harness = false
name = "execute_query"

[[bench]]
harness = false
name = "execute_update"

[[bench]]
harness = false
name = "scheduler"
