[package]
name = "ecdsa-canister"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ecdsa-canister"
path = "src/main.rs"

[dependencies]
candid = { workspace = true }
dfn_core = { path = "../dfn_core" }
ic-cdk = { workspace = true }
ic-cdk-macros = { workspace = true }
ic-ic00-types = { path = "../../types/ic00_types" }
serde = "1.0"
serde_json = "1.0.54"
serde_bytes = "0.11"
