[package]
name = "ic-determinism-test"
version = "0.8.0"
edition = "2021"

[dependencies]
clap = "2.33.3"
hex = "0.4.2"
ic-config = { path = "../config" }
ic-cycles-account-manager = { path = "../cycles_account_manager" }
ic-execution-environment = { path = "../execution_environment" }
ic-ic00-types = { path = "../types/ic00_types" }
ic-interfaces = { path = "../interfaces" }
ic-interfaces-state-manager = { path = "../interfaces/state_manager" }
ic-messaging = { path = "../messaging" }
ic-metrics = { path = "../monitoring/metrics" }
ic-protobuf = { path = "../protobuf" }
ic-registry-client = { path = "../registry/client" }
ic-registry-keys = { path = "../registry/keys" }
ic-registry-proto-data-provider = { path = "../registry/proto_data_provider" }
ic-registry-provisional-whitelist = { path = "../registry/provisional_whitelist" }
ic-registry-routing-table = { path = "../registry/routing_table" }
ic-registry-subnet-type = { path = "../registry/subnet_type" }
ic-replicated-state = { path = "../replicated_state" }
ic-state-manager = { path = "../state_manager" }
ic-test-utilities = { path = "../test_utilities" }
ic-test-utilities-registry = { path = "../test_utilities/registry" }
ic-types = { path = "../types/types" }
slog = { version = "2.5.2", features = ["nested-values", "release_max_level_debug"] }
tokio = "1.23.1"
wabt = { git = "https://github.com/dfinity-lab/wabt-rs", tag = "0.10.0-dfinity" }

