[package]
name = "ic-crypto-test-utils-keys"
version = "0.8.0"
edition = "2021"
description = "Test utility containing hard-coded keys"

[dependencies]
hex = "0.4.2"
ic-protobuf = { path = "../../../protobuf" }
ic-types = { path = "../../../types/types" }
