[package]
name = "ic-crypto-internal-basic-sig-ecdsa-secp256k1"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
base64 = { workspace = true }
ic-crypto-ecdsa-secp256k1 = { path = "../../../../ecdsa_secp256k1" }
ic-crypto-internal-basic-sig-der-utils = { path = "../der_utils" }
ic-crypto-internal-types = { path = "../../../crypto_lib/types" }
ic-crypto-secrets-containers = { path = "../../../../secrets_containers" }
ic-types = { path = "../../../../../types/types" }
serde = { workspace = true }
serde_bytes = { workspace = true }
simple_asn1 = { workspace = true }
zeroize = { version = "1.4.3", features = ["zeroize_derive"] }

[dev-dependencies]
assert_matches = "1.5.0"
hex = "0.4.2"
ic-crypto-sha2 = { path = "../../../../sha2" }
ic-crypto-test-utils-reproducible-rng = { path = "../../../../test_utils/reproducible_rng" }
rand = "0.8"
wycheproof = "0.5"
