[package]
name = "ic-crypto-internal-basic-sig-ecdsa-secp256k1"
version = "0.8.0"
edition = "2021"

[dependencies]
base64 = "0.11.0"
ic-crypto-ecdsa-secp256k1 = { path = "../../../../ecdsa_secp256k1" }
ic-crypto-internal-basic-sig-der-utils = { path = "../der_utils" }
ic-crypto-internal-types = { path = "../../../crypto_lib/types" }
ic-crypto-secrets-containers = { path = "../../../../secrets_containers" }
ic-types = { path = "../../../../../types/types" }
serde = { version = "1.0.99", features = ["derive"] }
serde_bytes = "0.11"
simple_asn1 = "0.6.1"
zeroize = { version = "1.4.3", features = ["zeroize_derive"] }

[dev-dependencies]
assert_matches = "1.5.0"
hex = "0.4.2"
ic-crypto-sha2 = { path = "../../../../sha2" }
ic-crypto-test-utils-reproducible-rng = { path = "../../../../test_utils/reproducible_rng" }
rand = "0.8"
wycheproof = "0.5"
