[package]
name = "ic-canonical-state"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
ic-error-types = { path = "../types/error_types" }
ic-base-types = { path = "../types/base_types" }
ic-canonical-state-tree-hash = { path = "./tree_hash" }
ic-certification-version = { path = "./certification_version" }
ic-crypto-tree-hash = { path = "../crypto/tree_hash" }
ic-protobuf = { path = "../protobuf" }
ic-registry-routing-table = { path = "../registry/routing_table" }
ic-registry-subnet-type = { path = "../registry/subnet_type" }
ic-replicated-state = { path = "../replicated_state" }
ic-types = { path = "../types/types" }
itertools = { workspace = true }
leb128 = "0.2.1"
phantom_newtype = { path = "../phantom_newtype" }
scoped_threadpool = "0.1.*"
serde = { workspace = true }
serde_bytes = { workspace = true }
serde_cbor = { workspace = true }
thiserror = "1.0"

[dev-dependencies]
assert_matches = "1.3.0"
ic-canonical-state-tree-hash-test-utils = { path = "tree_hash/test_utils" }
ic-registry-subnet-features = { path = "../registry/subnet_features" }
ic-test-utilities = { path = "../test_utilities" }
ic-utils = { path = "../utils" }
ic-wasm-types = { path = "../types/wasm_types" }
ic-sys = {path = "../sys"}
hex = "0.4.2"
lazy_static = "1.4.0"
maplit = "1.0.2"
proptest = "1.0"
strum = { workspace = true }
strum_macros = { workspace = true }
tempfile = "3.1.0"
