[package]
name = "ic-drun"
version = "0.8.0"
edition = "2021"

[dependencies]
ic-canister-sandbox-backend-lib = { path = "../canister_sandbox/backend_lib" }
ic-canister-sandbox-launcher = { path = "../canister_sandbox/sandbox_launcher" }
ic-config = { path = "../config" }
ic-cycles-account-manager = { path = "../cycles_account_manager" }
ic-error-types = { path = "../types/error_types" }
ic-execution-environment = { path = "../execution_environment" }
ic-http-endpoints-metrics = { path = "../http_endpoints/metrics" }
ic-ic00-types = { path = "../types/ic00_types" }
ic-interfaces = { path = "../interfaces" }
ic-interfaces-state-manager = { path = "../interfaces/state_manager" }
ic-messaging = { path = "../messaging" }
ic-metrics = { path = "../monitoring/metrics" }
ic-protobuf = { path = "../protobuf" }
ic-registry-client = { path = "../registry/client" }
ic-registry-keys = { path = "../registry/keys" }
ic-registry-proto-data-provider = { path = "../registry/proto_data_provider" }
ic-registry-provisional-whitelist = { path = "../registry/provisional_whitelist" }
ic-registry-routing-table = { path = "../registry/routing_table" }
ic-registry-subnet-type = { path = "../registry/subnet_type" }
ic-state-manager = { path = "../state_manager" }
# This is usually supposed to be a dev-dependency. However, using it in `drun`
# greatly simplifies the code that parses input messages to `SignedIngress`
# messages that are delivered to Message Routing. `drun` is a tool that
# is meant to be used mostly for testing anyway, so this dependency
# should be fine.
ic-test-utilities = { path = "../test_utilities" }
ic-test-utilities-registry = { path = "../test_utilities/registry" }
ic-types = { path = "../types/types" }
clap = { version = "3.1.6", features = ["derive"] }
hex = "0.4.2"
slog = { version = "2.5.2", features = ["nested-values", "release_max_level_debug"] }
slog-term = "2.6.0"
tokio = { version = "1.23.1", features = ["full"] }

[[bin]]
name = "drun"
path = "src/main.rs"
