[package]
name = "registry-canister"
version = "0.8.0"
edition = "2021"

[[bin]]
name = "registry-canister"
path = "canister/canister.rs"

[dependencies]
# This MUST be kept in sync with build-info-build in the [build-dependencies] section!
build-info = { version = "0.0.26", default-features = false, features = [] }

candid = "0.8.1"
cycles-minting-canister = {path = "../../nns/cmc"}
dfn_candid = { path = "../../rust_canisters/dfn_candid" }
dfn_core = { path = "../../rust_canisters/dfn_core" }
dfn_http_metrics = { path = "../../rust_canisters/dfn_http_metrics" }
futures = "0.3.21"
ic-base-types = { path = "../../types/base_types/" }
ic-certified-map = "0.3.1"
ic-crypto-node-key-validation = { path = "../../crypto/node_key_validation" }
ic-crypto-sha = {path = "../../crypto/sha/"}
ic-crypto-utils-basic-sig = { path = "../../crypto/utils/basic_sig" }
ic-ic00-types = { path = "../../types/ic00_types" }
ic-metrics-encoder = "1"
ic-nervous-system-common = { path = "../../nervous_system/common" }
ic-nervous-system-common-build-metadata = { path = "../../nervous_system/common/build_metadata" }
ic-nns-common = { path = "../../nns/common" }
ic-nns-constants = { path = "../../nns/constants" }
ic-protobuf = { path = "../../protobuf" }
ic-registry-keys = { path = "../../registry/keys" }
ic-registry-routing-table = { path = "../../registry/routing_table" }
ic-registry-subnet-features = { path = "../../registry/subnet_features" }
ic-registry-subnet-type = { path = "../../registry/subnet_type" }
ic-registry-transport = { path = "../transport" }
ic-types = { path = "../../types/types" }
ipnet = "2.5.0"
leb128 = "0.2.4"
on_wire = { path = "../../rust_canisters/on_wire" }
prost = "0.11.0"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11.1"
url = "2"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
assert_matches = "1.3.0"
canister-test = { path = "../../rust_canisters/canister_test" }
ic-canister-client-sender = { path = "../../canister_client/sender" }
ic-config = { path = "../../config" }
ic-crypto-node-key-generation = { path = "../../crypto/node_key_generation" }
ic-interfaces-registry = { path = "../../interfaces/registry" }
ic-registry-nns-data-provider = { path = "../nns_data_provider" }
ic-replica-tests = { path = "../../replica_tests" }
ic-registry-client-fake = { path = "../fake" }
ic-registry-proto-data-provider = { path = "../proto_data_provider"}
ic-test-utilities = { path = "../../test_utilities" }
lazy_static = "1.4.0"
maplit = "1.0"
rand = { version = "0.8.4", features = ["small_rng"]}
rand_distr = "0.4.0"

[build-dependencies]
# This MUST be kept in sync with build-info in the [dependencies] section!
build-info-build = { version="0.0.26", default-features = false, features = [] }

[dev-dependencies]
ic-crypto-tree-hash = { path = "../../crypto/tree_hash" }
ic-nervous-system-common-test-keys = { path = "../../nervous_system/common/test_keys" }
ic-nns-test-utils = {path="../../nns/test_utils"}
ic-nns-test-utils-macros = {path="../../nns/test_utils_macros"}
ic-test-utilities-compare-dirs = { path = "../../test_utilities/compare_dirs" }
registry-canister-protobuf-generator = { path = "./protobuf_generator" }
tokio = { version = "1.23.1", features = [ "time" ] }
tempfile = "3.1.0"
itertools = "0.10.3"
