[package]
name = "governance_upgrader"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "governance_upgrader"
path = "src/main.rs"

[dependencies]
bytes = "1.0.1"
clap = { version = "3.1.6", features = ["derive"] }
garcon = "0.2"
ic-nns-init = { path="../../nns/init" }
ic-base-types = { path="../../types/base_types" }
ic-types = { path = "../../types/types" }
ic-nns-constants = { path = "../../nns/constants" }
on_wire = { path = "../../rust_canisters/on_wire" }
canister-test = { path = "../../rust_canisters/canister_test" }
dfn_candid={path="../../rust_canisters/dfn_candid"}
tokio = { version = "1.24.2", features = ["full"] }
candid = "0.8.1"
url = { version = "2.1.1", features = ["serde"] }

ic-identity-hsm = "=0.22.0"
ic-agent = "=0.22.0"
ic-utils = "=0.22.0"
