[package]
name = "service-discovery"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ic-interfaces-registry = { path = "../../interfaces/registry" }
ic-protobuf = { path = "../../protobuf" }
ic-registry-local-registry = { path = "../../registry/local_registry" }
ic-registry-client = { path = "../../registry/client" }
ic-registry-client-helpers = { path = "../../registry/helpers" }
ic-registry-nns-data-provider = { path = "../../registry/nns_data_provider" }
ic-registry-local-store = { path = "../../registry/local_store" }
ic-registry-local-store-artifacts = { path = "../../registry/local_store/artifacts" }
ic-types = { path = "../../types/types" }
thiserror = "1.0"
ic-metrics = { path = "../../monitoring/metrics" }
prometheus = { version = "0.12.0", features = ["process"] }
hyper = { version = "0.14.18", features = ["full"] }
anyhow = "1.0.31"
slog = { version = "2.5.2", features = ["nested-values"] }
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0.54"
ic-utils = { path = "../../utils/" }
ic-registry-keys = { path = "../../registry/keys" }
tokio = { version = "1.32.0", features = ["full"] }
crossbeam = "0.8.0"
crossbeam-channel = "0.5.5"
tempfile = "3.1.0"
url = "2.2.2"
ic-registry-client-fake = { path = "../../registry/fake" }
registry-canister = { path = "../../registry/canister" }
ic-registry-common-proto = { path = "../../registry/proto" }
futures = { workspace = true }
regex = "1.7.0"

[dev-dependencies]
itertools = "0.10.0"
