[package]
name = "ic-validator-ingress-message-test-canister"
version = "0.1.0"
edition = "2021"

[dependencies]
# This MUST be kept in sync with build-info-build in the [build-dependencies] section!
build-info = { version = "0.0.26", default-features = false, features = [] }

candid = { workspace = true }
ic-cdk = { workspace = true }
ic-cdk-macros = { workspace = true }
ic-types = { path = "../../../types/types" }
ic-validator-ingress-message = { path = ".." }

[build-dependencies]
# This MUST be kept in sync with build-info in the [dependencies] section!
build-info-build = { version="0.0.26", default-features = false, features = [] }

[dev-dependencies]
canister-test = { path = "../../../rust_canisters/canister_test" }
ic-state-machine-tests = { path = "../../../state_machine_tests" }
ic-types = { path = "../../../types/types" }
tokio = { version = "1.15.0", features = ["full"] }
