[package]
name = "ic-canonical-state-tree-hash"
version = "0.8.0"
edition = "2021"

[dependencies]
ic-crypto-tree-hash = { path = "../../crypto/tree_hash" }
itertools = "0.10.3"
leb128 = "0.2.1"
scoped_threadpool = "0.1.*"
thiserror = "1.0"

[dev-dependencies]
ic-canonical-state-tree-hash-test-utils = { path = "test_utils" }
ic-crypto-test-utils-reproducible-rng = { path = "../../crypto/test_utils/reproducible_rng" }
ic-crypto-tree-hash-test-utils = { path = "../../crypto/tree_hash/test_utils" }
assert_matches = "1.3.0"
proptest = "1.0"
rand = "0.8"
rand_chacha = "0.3"
