[package]
name = "ic-consensus"
version = "0.8.0"
edition = "2021"

[dependencies]
ic-artifact-pool = { path = "../artifact_pool" }
ic-config = { path = "../config" }
ic-constants = { path = "../constants" }
ic-crypto = { path = "../crypto" }
ic-crypto-prng = { path = "../crypto/prng" }
ic-crypto-test-utils-canister-threshold-sigs = { path = "../crypto/test_utils/canister_threshold_sigs", optional = true }
ic-error-types = { path = "../types/error_types" }
ic-ic00-types = { path = "../types/ic00_types" }
ic-interfaces = { path = "../interfaces" }
ic-interfaces-https-outcalls-adapter-client = { path = "../interfaces/https_outcalls_adapter_client" }
ic-interfaces-registry = { path = "../interfaces/registry" }
ic-interfaces-state-manager = { path = "../interfaces/state_manager" }
ic-registry-client-helpers = { path = "../registry/helpers" }
ic-registry-keys = { path = "../registry/keys" }
ic-replicated-state = { path = "../replicated_state" }
ic-logger = { path = "../monitoring/logger" }
ic-metrics = { path = "../monitoring/metrics" }
ic-registry-subnet-type = { path = "../registry/subnet_type" }
ic-registry-subnet-features = { path = "../registry/subnet_features" }
ic-protobuf = { path = "../protobuf" }
ic-types = { path = "../types/types" }
ic-utils = { path = "../utils" }
hex = "0.4.2"
num-integer = "0.1.41"
phantom_newtype = { path = "../phantom_newtype" }
prometheus = { version = "0.12.0", features = [ "process" ] }
proptest = { version = "1.0.0", optional = true }
rand = "0.8"
rand_chacha = "0.3"
rayon = "1.5.1"
slog = { version = "2.5.2", features = ["nested-values", "release_max_level_debug"] }
strum = "0.23.0"
strum_macros = "0.23.0"
bzb_execution_layer = { git="https://github.com/bzbyte/execution_layer", rev="a352408e82bb92957bb4c8793963023e0b61c8df"}

[dev-dependencies]
assert_matches = "1.3.0"
criterion = "0.3"
ic-artifact-pool = { path = "../artifact_pool" }
ic-btc-types-internal = { path = "../bitcoin/types/internal" }
ic-config = { path = "../config" }
ic-crypto-test-utils-canister-threshold-sigs = { path = "../crypto/test_utils/canister_threshold_sigs" }
ic-execution-environment = { path = "../execution_environment" }
ic-ingress-manager = { path = "../ingress_manager" }
ic-interfaces-certified-stream-store = { path = "../interfaces/certified_stream_store" }
ic-interfaces-state-manager-mocks = { path = "../interfaces/state_manager/mocks" }
ic-messaging = { path = "../messaging" }
ic-registry-client-fake = { path = "../registry/fake" }
ic-registry-proto-data-provider = { path = "../registry/proto_data_provider" }
ic-replicated-state = { path = "../replicated_state" }
ic-state-manager = { path = "../state_manager" }
ic-test-artifact-pool = { path = "../test_utilities/artifact_pool" }
ic-cycles-account-manager = { path = "../cycles_account_manager" }
ic-test-utilities = { path = "../test_utilities" }
ic-test-utilities-logger = { path = "../test_utilities/logger" }
ic-test-utilities-registry = { path = "../test_utilities/registry" }
mockall = "0.7.2"
slog-async = "2.5.0"
slog-envlogger = "2.2.0"
slog-term = "2.6.0"
tempfile = "3.1.0"
prost = "0.11.0"
serde_cbor = "0.11.1"

[[bench]]
name = "validate_payload"
harness = false

[features]
default = []
malicious_code = ["ic-crypto-test-utils-canister-threshold-sigs"]
