[package]
name = "ic-regedit"
version = "0.8.0"
edition = "2021"

[dependencies]
anyhow = "1.0.31"
base64 = "0.11"
clap = { version = "3.1.6", features = ["derive"] }
ic-crypto = { path = "../../crypto" }
ic-crypto-sha2 = { path = "../../crypto/sha2/" }
ic-protobuf = { path = "../../protobuf" }
ic-registry-client = { path = "../client" }
ic-registry-client-helpers = { path = "../helpers" }
ic-registry-nns-data-provider-wrappers = { path = "../nns_data_provider_wrappers" }
ic-registry-local-store = { path = "../local_store" }
ic-registry-keys = { path = "../keys" }
ic-registry-subnet-type = { path = "../subnet_type" }
ic-types = { path = "../../types/types" }
ic-base-types = { path = "../../types/base_types" }
prost = { workspace = true }
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0.54"
thiserror = "1.0"
tokio = { version = "1.32.0", features = ["full"] }
url = { version = "2.1.1", features = ["serde"] }

[dev-dependencies]
ic-prep = { path = "../../prep" }
ic-registry-provisional-whitelist = { path = "../provisional_whitelist" }
tempfile = "3.1.0"

[[bin]]
name = "ic-regedit"
path = "src/main.rs"
