[package]
name = "ic-regedit"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
anyhow = "1.0.31"
base64 = { workspace = true }
clap = { workspace = true }
ic-crypto-sha2 = { path = "../../crypto/sha2/" }
ic-crypto-utils-threshold-sig-der = { path = "../../crypto/utils/threshold_sig_der" }
ic-protobuf = { path = "../../protobuf" }
ic-registry-client = { path = "../client" }
ic-registry-client-helpers = { path = "../helpers" }
ic-registry-nns-data-provider-wrappers = { path = "../nns_data_provider_wrappers" }
ic-registry-local-store = { path = "../local_store" }
ic-registry-keys = { path = "../keys" }
ic-registry-subnet-type = { path = "../subnet_type" }
ic-types = { path = "../../types/types" }
ic-base-types = { path = "../../types/base_types" }
prost = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = "1.0"
tokio = { workspace = true }
url = { version = "2.1.1", features = ["serde"] }

[dev-dependencies]
ic-prep = { path = "../../prep" }
ic-registry-provisional-whitelist = { path = "../provisional_whitelist" }
tempfile = "3.1.0"

[[bin]]
name = "ic-regedit"
path = "src/main.rs"
