[package]
name = "icx-proxy"
version = "0.11.1"
authors = ["DFINITY Stiftung <sdk@dfinity.org>"]
edition = "2018"
description = "CLI tool to create an HTTP proxy to the Internet Computer."
homepage = "https://docs.rs/icx-proxy"
documentation = "https://docs.rs/icx-proxy"
license = "Apache-2.0"
readme = "README.md"
categories = ["command-line-interface", "web-programming::http-server"]
keywords = ["internet-computer", "agent", "icp", "dfinity", "proxy"]
include = ["src", "Cargo.toml", "../LICENSE", "README.md"]

[[bin]]
name = "icx-proxy"
path = "src/main.rs"

[dependencies]
anyhow = "1"
async-trait = "0.1"
axum = "0.6.1"
base64 = "0.11"
candid = { version = "0.8", features = ["mute_warnings"] }
clap = { version = "4", features = ["cargo", "derive"] }
flate2 = "1"
form_urlencoded = "1"
futures = "0.3"
h2 = "0.3.19"
hex = "0.4"
http-body = "0.4"
hyper = { version = "0.14.26", features = ["client", "http2", "http1"] }
hyper-rustls = { version = "0.24.0", features = ["http2"] }
itertools = "0.10"
ic-agent = { workspace = true, default-features = false, features = [
    "hyper",
    "reqwest",
] }
ic-utils = { workspace = true, features = ["raw"] }
opentelemetry = { version = "0.20", features = ["metrics"] }
opentelemetry-prometheus = "0.13.0"
prometheus = "0.13.3"
rustls = { version = "0.21", features = ["dangerous_configuration"] }
rustls-native-certs = "0.6.2"
rustls-pemfile = "1"
tower = "0.4"
tower-http = { version = "0.3", features = ["trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json"] }
serde = "1"
serde_cbor = "0.11"
serde_json = "1"
sha2 = "0.10"
tokio = { version = "1", features = ["full"] }
ic-response-verification = "1.0.2"
thiserror = "1.0.40"

[features]
skip_body_verification = []
dev_proxy = []

[dev-dependencies]
tokio-test = "0.4.2"
