[package]
name = "ic-crypto-internal-basic-sig-ed25519"
version = "0.8.0"
edition = "2018"

[dependencies]
base64 = "0.11.0"
curve25519-dalek = "3.0.2"
ed25519-consensus = "2.0.1"
hex = "0.4.2"
ic-crypto-secrets-containers = { path = "../../../../secrets_containers" }
ic-crypto-internal-types = { path = "../../../crypto_lib/types" }
ic-crypto-internal-basic-sig-der-utils = { path = "../der_utils" }
ic-protobuf = { path = "../../../../../protobuf" }
ic-types = { path = "../../../../../types/types" }
rand = "0.8"
rand_chacha = "0.3"
serde = { version = "1.0.99", features = [ "derive" ] }
simple_asn1 = "0.6.1"
zeroize = { version = "1.4.3", features = ["zeroize_derive"] }

[dev-dependencies]
ic-crypto-internal-test-vectors = { path = "../../../test_vectors" }
proptest = "0.9.4"
proptest-derive = "0.1.0"
serde_cbor = "0.11.1"
strum = "0.23.0"
wycheproof = "0.4"
