[package]
name = "ic-registry-local-store"
version = "0.8.0"
edition = "2021"

[dependencies]
ic-interfaces-registry = { path = "../../interfaces/registry" }
ic-registry-common-proto = { path = "../proto" }
ic-types = { path = "../../types/types" }
ic-utils = { path = "../../utils" }
prost = { workspace = true }

[dev-dependencies]
ic-registry-local-store-artifacts = { path = "./artifacts" }
rand = "0.8"
tempfile = "3.0"
