[package]
name = "xrc-mock"
version = "0.1.0"
edition = "2021"

[dependencies]
candid = { workspace = true }
ic-cdk-macros = { workspace = true }
ic-cdk = { workspace = true }
ic-xrc-types = "1.0.0"
serde = "1.0"
