[package]
name = "xnet-test"
version = "0.8.0"
edition = "2021"

[[bin]]
name = "xnet-test-canister"
path = "src/main.rs"

[dependencies]
candid = { workspace = true }
dfn_core = { path = "../dfn_core" }
rand = "0.8"
rand_pcg = "0.3"
serde = "1.0"
