[package]
name = "canister-test"
version = "0.8.0"
authors = ["The Internet Computer Project Developers"]
edition = "2021"

[dependencies]
backoff = "0.3.0"
candid = "0.8.1"
cargo_metadata = "0.14.2"
dfn_candid={path="../dfn_candid"}
ic-canister-client = { path = "../../canister_client" }
ic-config = { path = "../../config" }
ic-ic00-types = { path = "../../types/ic00_types" }
ic-registry-transport = { path = "../../registry/transport" }
ic-replica-tests = { path = "../../replica_tests" }
ic-types = { path = "../../types/types" }
escargot = "0.5.2"
on_wire = { path = "../on_wire" }
rand = "0.8"
reqwest = { version = "0.11.1", features = [ "native-tls" ] }
tokio = { version = "1.24.2", features = [ "full" ] }
wasmprinter = "0.2.45"
wat = "1.0.52"

