[package]
name = "ic-registry-subnet-features"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
candid = { workspace = true }
ic-protobuf = { path = "../../protobuf" }
ic-ic00-types = { path = "../../types/ic00_types" }
serde = { workspace = true }
