[package]
name = "ic-registry-proto-data-provider"
version = "0.8.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = { workspace = true }
ic-interfaces-registry = { path = "../../interfaces/registry" }
ic-registry-common-proto = { path = "../proto" }
ic-registry-transport = { path = "../transport" }
ic-types = { path = "../../types/types" }
ic-utils = { path = "../../utils" }
thiserror = "1.0"
