[package]
name = "dfn_protobuf"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
on_wire = { path = "../on_wire" }
dfn_core = { path = "../dfn_core" }
ic-base-types = { path = "../../types/base_types" }
prost = { workspace = true }
