[package]
name = "ic-sns-root"
version = "0.8.0"
edition = "2021"

[[bin]]
name = "sns-root-canister"
path = "canister/canister.rs"

[dependencies]
async-trait = "0.1.53"

# This MUST be kept in sync with build-info-build in the [build-dependencies] section!
build-info = { version = "0.0.26", default-features = false, features = [] }

candid = "0.8.1"
comparable = { version = "0.5.1", features = ["derive"] }
dfn_candid = { path = "../../rust_canisters/dfn_candid" }
dfn_core = { path = "../../rust_canisters/dfn_core" }
ic-base-types = { path = "../../types/base_types" }
ic-ic00-types = { path = "../../types/ic00_types" }
ic-icrc1 = { path = "../../rosetta-api/icrc1" }
ic-nervous-system-common = { path = "../../nervous_system/common" }
ic-nervous-system-common-build-metadata = { path = "../../nervous_system/common/build_metadata" }
ic-nervous-system-root = { path = "../../nervous_system/root" }
ic-sns-swap = { path = "../swap" }
num-traits = "0.2.12"
prost = "0.11.0"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
ic-sns-root-protobuf-generator = { path = "./protobuf_generator" }
ic-test-utilities-compare-dirs = { path = "../../test_utilities/compare_dirs" }
tempfile = "3.1.0"
tokio = { version = "1.23.1", features = [ "full" ] }

[build-dependencies]
# This MUST be kept in sync with build-info in the [dependencies] section!
build-info-build = { version = "0.0.26", default-features = false, features = [] }

[features]
test = []
