[package]
name = "ic-nervous-system-root"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.42"
candid = { workspace = true }
dfn_candid = { path = "../../rust_canisters/dfn_candid" }
dfn_core = { path = "../../rust_canisters/dfn_core" }
ic-base-types = { path = "../../types/base_types" }
ic-cdk = { workspace = true }
ic-crypto-sha2 = { path = "../../crypto/sha2" }
ic-nervous-system-clients = { path = "../clients" }
ic-nervous-system-common = { path = "../common" }
ic-nervous-system-proxied-canister-calls-tracker = { path = "../proxied_canister_calls_tracker" }
ic-nervous-system-runtime = { path = "../runtime" }
ic-nns-constants = { path = "../../nns/constants" }
ic-ic00-types = { path = "../../types/ic00_types" }
lazy_static = "1.4.0"
num-traits = "0.2.12"
serde = { version = "1.0.99", features = ["derive"] }
serde_bytes = "0.11"
