[package]
name = "ic-validator-fuzz"
version = "0.0.0"
publish = false
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[package.metadata]
cargo-fuzz = true

[dependencies]
arbitrary = "1.3.0"
assert_matches = "1.5.0"
ic-crypto-tree-hash = { path = "../../crypto/tree_hash" }
ic-base-types = { path = "../../types/base_types" }
ic-types = { path = "../../types/types" }
ic-validator-ingress-message = { path = "../ingress_message" }
lazy_static = "1.4.0"
libfuzzer-sys = "0.4"

[dependencies.ic-validator]
path = ".."

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[profile.release]
debug = 1

[[bin]]
name = "validate_request"
path = "fuzz_targets/validate_request.rs"
test = false
doc = false

[[bin]]
name = "signed_ingress"
path = "fuzz_targets/signed_ingress.rs"
test = false
doc = false
