[package]
name = "dfn_macro"
build = "build.rs"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[lib]
proc-macro = true
test = false

[dependencies]
rustversion = "1.0"
syn = { workspace = true }
quote = "1.0"
proc-macro2 = "1.0"

[features]
nightly_compiler = []

[build-dependencies]
rustversion = "1.0"
