[package]
name = "ic-registry-keys"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
candid = { workspace = true }
ic-base-types = { path = "../../types/base_types" }
ic-ic00-types = { path = "../../types/ic00_types" }
ic-types = { path = "../../types/types" }
serde = { workspace = true }

[dev-dependencies]
rand = "0.8"
