[package]
name = "ic-starter"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { workspace = true }
ic-config = { path = "../config" }
ic-logger = { path = "../monitoring/logger" }
ic-prep = { path = "../prep" }
ic-protobuf = { path = "../protobuf" }
ic-registry-provisional-whitelist = { path = "../registry/provisional_whitelist" }
ic-registry-subnet-type = { path = "../registry/subnet_type" }
ic-registry-subnet-features = { path = "../registry/subnet_features" }
ic-types = { path = "../types/types" }
ic-ic00-types = { path = "../types/ic00_types" }
serde = { workspace = true }
serde_json = { workspace = true }
slog = { workspace = true }
tempfile = "3.1.0"
url = "2.1.1"

[[bin]]
name = "ic-starter"
path = "src/main.rs"
