[package]
name = "certificate-issuer"
version = "0.1.0"
edition = "2021"

[dependencies.certificate_orchestrator_interface]
path = "../certificate_orchestrator_interface"

[dependencies]
anyhow = "1.0.66"
async-trait = "0.1.58"
axum = { version = "0.6.1", features = ["json"] }
candid = "0.8.4"
cfg-if = "1.0.0"
chacha20poly1305 = "0.10.0"
chrono = { version = "0.4.19", default-features = false, features = ["clock"] }
clap = { version = "4.0.18", features = ["derive"] }
cloudflare = "0.9.1"
futures = "0.3.25"
garcon = "0.2.3"
hyper = { version = "0.14.20", features = ["full"] }
hyper-rustls = "0.23.0"
ic-agent = "0.22.0"
ic-utils = { version = "0.22.0", features = ["raw"] }
instant-acme = "0.1.0"
mockall = "0.11.3"
opentelemetry = "0.18.0"
opentelemetry-prometheus = "0.11.0"
pem = "1.1.0"
prometheus = "0.13.3"
rcgen = "0.10.0"
reqwest = "0.11.13"
serde = { version = "1.0.147", features = ["serde_derive"] }
serde_bytes = "0.11.7"
serde_json = "1.0.87"
sha2 = "0.10.6"
thiserror = "1.0.37"
tokio = { version = "1.24.2", features = ["full"] }
tower = { version = "0.4.13", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["json"] }
trust-dns-resolver = "0.22.0"
