[package]
name = "certificate-issuer"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies.certificate_orchestrator_interface]
path = "../certificate_orchestrator_interface"

[dependencies]
anyhow = "1.0.66"
async-trait = "0.1.58"
axum = { version = "0.6.1", features = ["json"] }
candid = { workspace = true }
chacha20poly1305 = "0.10.0"
clap = { version = "4.0.18", features = ["derive"] }
cloudflare = { workspace = true }
flate2 = "1.0.22"
futures = { workspace = true }
ic-agent = { workspace = true }
ic-utils = { workspace = true, features = ["raw"] }
ic-response-verification = "1.2.0"
idna = "0.3.0"
instant-acme = "0.3.2"
leb128 = "0.2.5"
mockall = "0.11.3"
opentelemetry = { version = "0.20", features = ["metrics"] }
opentelemetry-prometheus = "0.13.0"
pem = "1.1.0"
prometheus = { workspace = true }
rcgen = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_cbor = { workspace = true }
serde_json = { workspace = true }
sha2 = "0.10.6"
thiserror = "1.0.37"
tokio = { workspace = true }
tower = { workspace = true }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["json"] }
trust-dns-resolver = "0.22.0"
