[package]
name = "pocket-ic-server"
version = "2.0.1"
edition = "2021"

[dependencies]
axum = { version = "^0.6.1", features = ["headers"] }
candid = { workspace = true }
rand = "^0.8.5"
itertools = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
pocket-ic = { path = "../../packages/pocket-ic" }
ic-state-machine-tests = { path = "../state_machine_tests" }
ic-ic00-types = { path = "../types/ic00_types" }
ic-interfaces-state-manager = { path = "../interfaces/state_manager" }
ic-config = { path = "../config" }
ic-registry-subnet-type = { path = "../registry/subnet_type" }
ic-types = { path = "../types/types" }
ic-crypto-iccsa = { path = "../crypto/iccsa" }
ic-cdk = { workspace = true }
ic-crypto-sha2 = { path = "../crypto/sha2" }
ic-utils = { path = "../utils" }
ic-registry-routing-table = { path = "../registry/routing_table" }
ic-test-utilities = { path = "../test_utilities" }
ic-registry-proto-data-provider = { path = "../registry/proto_data_provider" }
hex = "0.4.2"
ic-crypto-utils-threshold-sig-der = { path = "../crypto/utils/threshold_sig_der" }
clap = { workspace = true }
sha2 = "0.9.3"
time = "^0.3.20"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "^0.2.2"
tower-http = { version = "^0.4.4", features = ["trace", "request-id", "util"] }
tempfile = "*"
base64 = { workspace = true }
wat = "1.0.52"
flate2 = "1.0.27"
aide = { version = "0.12.0", features = ["axum"] }
schemars = "0.8.16"

[dev-dependencies]
reqwest = { workspace = true }
