[package]
name = "ic-prep"
version = "0.8.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
base64 = "0.11"
clap = { version = "3.1.6", features = ["derive"] }
chrono = "0.4.19"
fs_extra = "1.2.0"
ic-crypto = { path = "../crypto" }
ic-crypto-node-key-generation = { path = "../crypto/node_key_generation" }
ic-crypto-node-key-validation = { path = "../crypto/node_key_validation" }
ic-crypto-test-utils-ni-dkg = { path = "../crypto/test_utils/ni-dkg" }
ic-config = { path = "../config" }
ic-constants = { path = "../constants" }
ic-ic00-types = { path = "../types/ic00_types" }
ic-http-utils = { path = "../http_utils" }
ic-interfaces-registry = { path = "../interfaces/registry" }
ic-logger = { path = "../monitoring/logger" }
ic-protobuf = { path = "../protobuf" }
ic-registry-client = { path = "../registry/client" }
ic-registry-keys = { path = "../registry/keys" }
ic-registry-local-store = { path = "../registry/local_store" }
ic-registry-proto-data-provider = { path = "../registry/proto_data_provider" }
ic-registry-provisional-whitelist = { path = "../registry/provisional_whitelist" }
ic-registry-routing-table = { path = "../registry/routing_table" }
ic-registry-subnet-type = { path = "../registry/subnet_type" }
ic-registry-transport = { path = "../registry/transport" }
ic-types = { path = "../types/types" }
json5 = "0.4.1"
openssl = "0.10.48"
maplit = "1.0.2"
prost = "0.11.0"
rand = "0.8"
reqwest = { version = "0.11.1", features = ["blocking", "native-tls"] }
serde = { version = "1.0.99", features = ["derive"] }
serde_json = "1.0.40"
slog = { version = "2.5.2", features = [
    "nested-values",
    "release_max_level_debug",
] }
tempfile = "3.1.0"
thiserror = "1.0"
url = "2.1.1"

[dev-dependencies]
assert_matches = "1"
pretty_assertions = "0.6"

[lib]
name = "ic_prep_lib"
path = "src/lib.rs"

[[bin]]
name = "ic-prep"
path = "src/bin/prep.rs"

[[bin]]
name = "ic-principal-id"
path = "src/bin/principal_id.rs"
