[package]
name = "ic-types-test-utils"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
ic-certification-version = { path = "../../canonical_state/certification_version" }
ic-canonical-state = { path = "../../canonical_state" }
ic-types = { path = "../types" }
proptest = "1.0"
strum = { workspace = true }
