[package]
name = "ic-types-test-utils"
version = "0.8.0"
authors = ["The Internet Computer Project Developers"]
edition = "2021"

[dependencies]
ic-certification-version = { path = "../../canonical_state/certification_version" }
ic-canonical-state = { path = "../../canonical_state" }
ic-types = { path = "../types" }
proptest = "1.0"
strum = "0.23.0"
