[package]
name = "ic-nervous-system-proto"
version = "0.0.1"
edition = "2021"

[dependencies]
candid = { workspace = true }
comparable = { version = "0.5.1", features = ["derive"] }
ic-base-types = { path = "../../types/base_types" }
prost = { workspace = true }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
ic-nervous-system-proto-protobuf-generator = { path = "./protobuf_generator" }
ic-test-utilities-compare-dirs = { path = "../../test_utilities/compare_dirs" }
tempfile = "3.1.0"
