[package]
name = "ic-icrc1-index"
version = "0.8.0"
authors = ["The Internet Computer Project Developers"]
description = "Index canister for the ICRC1 Ledger"
edition = "2018"

[dependencies]
async-trait = "0.1.53"
candid = { workspace = true }
ciborium = { workspace = true }
ic-base-types = { path = "../../../types/base_types" }
ic-canister-profiler = { path = "../../../rust_canisters/canister_profiler" }
ic-canisters-http-types = { path = "../../../rust_canisters/http_types" }
ic-ledger-hash-of = { path = "../../../../packages/ic-ledger-hash-of" }
ic-cdk = { workspace = true }
ic-cdk-timers = { workspace = true }
ic-cdk-macros = { workspace = true }
ic-icrc1 = { path = ".." }
ic-icrc1-ledger = { path = "../ledger" }
ic-icrc1-tokens-u64 = { path = "../tokens_u64" }
ic-metrics-encoder = "1.1"
icrc-ledger-types = { path = "../../../../packages/icrc-ledger-types" }
num-traits = "0.2.14"
scopeguard = "1.1.0"
serde = "1.0.139"

[dev-dependencies]
assert_matches = "1.5.0"
ic-base-types = { path = "../../../types/base_types" }
ic-icrc1-ledger = { path = "../ledger" }
ic-state-machine-tests = { path = "../../../state_machine_tests" }
ic-test-utilities-load-wasm = { path = "../../../test_utilities/load_wasm" }
ic-ledger-core = { path = "../../ledger_core" }
ic-ledger-canister-core = { path = "../../ledger_canister_core" }
num-traits = "0.2.14"
proptest = "1.0"
serde_json = "1.0.54"

[[bin]]
name = "ic-icrc1-index"
path = "src/main.rs"
