[package]
name = "ic-icos-sev"
version = "0.8.0"
edition = "2021"

[dependencies]
async-trait = "0.1.41"
ic-types = { path = "../../types/types" }
ic-icos-sev-interfaces = { path = "../sev_interfaces" }
ic-interfaces-registry = { path = "../../interfaces/registry" }
ic-registry-client-helpers = { path = "../../registry/helpers" }
ic-registry-subnet-type = { path = "../../registry/subnet_type" }
ic-interfaces-transport = { path = "../../interfaces/transport" }
ic-registry-subnet-features = { path = "../../registry/subnet_features" }
serde_cbor = "0.11"
serde = { version = "1.0.99", features = ["derive"] }
sha2 = "0.9.1"
tokio = { version = "1.15.0", features = ["full"] }
openssl = "0.10.48"
[target.'cfg(all(target_os = "linux", target_arch = "x86_64"))'.dependencies]
sev = { version = "1.1", features = ["openssl"] }
