[package]
name = "ic-icos-sev"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
anyhow = "1.0.57"
async-trait = "0.1.41"
ic-types = { path = "../../types/types" }
ic-interfaces-registry = { path = "../../interfaces/registry" }
ic-logger = { path = "../../monitoring/logger" }
ic-registry-client-helpers = { path = "../../registry/helpers" }
ic-registry-subnet-type = { path = "../../registry/subnet_type" }
ic-registry-subnet-features = { path = "../../registry/subnet_features" }
ic-base-types = { path = "../../types/base_types" }
serde_cbor = { workspace = true }
serde = { workspace = true }
sha2 = "0.10.8"
thiserror = "1"
tokio = { workspace = true }
slog = { workspace = true }
[target.'cfg(all(target_os = "linux", target_arch = "x86_64"))'.dependencies]
sev = { version = "2.0.2", features = ["crypto_nossl"] }

[dev-dependencies]
assert_matches = "1.5.0"
tempfile = "3.3.0"
