[package]
name = "ic-sns-wasm"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "sns-wasm-canister"
path = "canister/canister.rs"

[lib]
path = "src/lib.rs"

[dependencies]
# This MUST be kept in sync with build-info-build in the [build-dependencies] section!
build-info = { version = "0.0.26", default-features = false, features = [] }

async-trait = "0.1.42"
candid = "0.8.1"
dfn_candid = { path = "../../rust_canisters/dfn_candid" }
dfn_core = { path = "../../rust_canisters/dfn_core" }
dfn_http_metrics = { path = "../../rust_canisters/dfn_http_metrics" }
futures = "0.3.21"
hex = "0.4.3"
ic-base-types = { path = "../../types/base_types" }
ic-cdk = "0.6.0"
ic-crypto-sha = {path = "../../crypto/sha/"}
ic-ic00-types = {path = "../../types/ic00_types"}
ic-metrics-encoder = "1"
ic-nervous-system-common = { path = "../../nervous_system/common" }
ic-nns-constants = { path = "../constants" }
ic-sns-governance = { path = "../../sns/governance" }
ic-sns-init = { path = "../../sns/init" }
ic-sns-root = { path = "../../sns/root" }
ic-types = { path = "../../types/types"}
maplit = "1.0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.85"
prost = "0.11.0"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
ic-protobuf = { path = "../../protobuf" }
registry-canister = { path = "../../registry/canister" }
ic-registry-keys = { path = "../../registry/keys" }
ic-interfaces-registry = { path = "../../interfaces/registry" }

[dev-dependencies]
ic-sns-wasm-protobuf-generator = { path = "./protobuf_generator" }
ic-test-utilities = { path = "../../test_utilities" }
ic-test-utilities-compare-dirs = { path = "../../test_utilities/compare_dirs" }
tempfile = "3.1.0"
tokio = { version = "1.24.2", features = ["full"] }
ic-state-machine-tests = { path = "../../state_machine_tests" }
canister-test = { path = "../../rust_canisters/canister_test" }
ic-icrc1 = { path = "../../rosetta-api/icrc1" }
ic-icrc1-ledger = { path = "../../rosetta-api/icrc1/ledger" }
ic-nervous-system-common = { path = "../../nervous_system/common" }
ic-nns-test-utils = { path = "../test_utils" }
ic-registry-client-helpers = { path = "../../registry/helpers" }
ic-sns-swap = { path = "../../sns/swap" }
ic-ic00-types = { path = "../../types/ic00_types" }
icp-ledger = { path = "../../rosetta-api/icp_ledger" }
pretty_assertions = "1.2.1"
on_wire = { path = "../../rust_canisters/on_wire" }

[features]
test = ["ic-sns-init/test"]
