[package]
name = "ic-system-api"
version = "0.8.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = { workspace = true }
ic-base-types = { path = "../types/base_types" }
ic-btc-interface = { workspace = true }
ic-config = { path = "../config" }
ic-constants = { path = "../constants" }
ic-cycles-account-manager = { path = "../cycles_account_manager" }
ic-error-types = { path = "../types/error_types" }
ic-ic00-types = { path = "../types/ic00_types" }
ic-interfaces = { path = "../interfaces" }
ic-logger = { path = "../monitoring/logger" }
ic-nns-constants = { path = "../nns/constants" }
ic-registry-routing-table = { path = "../registry/routing_table" }
ic-registry-subnet-type = { path = "../registry/subnet_type" }
ic-replicated-state = { path = "../replicated_state" }
ic-sys = { path = "../sys" }
ic-types = { path = "../types/types" }
ic-wasm-types = { path = "../types/wasm_types" }
ic-utils = { path = "../utils" }
prometheus = { version = "0.12.0", features = ["process"] }
serde = { version = "1.0.99", features = ["derive"] }
serde_bytes = "0.11"
slog = { version = "2.5.2", features = [
    "nested-values",
    "release_max_level_debug",
] }

[dev-dependencies]
assert_matches = "1.0.0"
ic-registry-subnet-features = { path = "../registry/subnet_features" }
ic-test-utilities = { path = "../test_utilities" }
maplit = "1.0.2"
ic-nns-constants = { path = "../nns/constants" }
