[package]
name = "ic-system-api"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = { workspace = true }
ic-base-types = { path = "../types/base_types" }
ic-btc-interface = { workspace = true }
ic-config = { path = "../config" }
ic-constants = { path = "../constants" }
ic-cycles-account-manager = { path = "../cycles_account_manager" }
ic-error-types = { path = "../types/error_types" }
ic-ic00-types = { path = "../types/ic00_types" }
ic-interfaces = { path = "../interfaces" }
ic-logger = { path = "../monitoring/logger" }
ic-nns-constants = { path = "../nns/constants" }
ic-registry-routing-table = { path = "../registry/routing_table" }
ic-registry-subnet-type = { path = "../registry/subnet_type" }
ic-replicated-state = { path = "../replicated_state" }
ic-sys = { path = "../sys" }
ic-types = { path = "../types/types" }
ic-wasm-types = { path = "../types/wasm_types" }
ic-utils = { path = "../utils" }
prometheus = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
slog = { workspace = true }

[dev-dependencies]
assert_matches = "1.0.0"
ic-registry-subnet-features = { path = "../registry/subnet_features" }
ic-test-utilities = { path = "../test_utilities" }
maplit = "1.0.2"
ic-nns-constants = { path = "../nns/constants" }
