[package]
name = "certificate-syncer"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
anyhow = "1.0.66"
async-trait = "0.1.59"
axum = { version = "0.6.1", features = ["json"] }
candid = { workspace = true }
clap = { version = "4.0.29", features = ["derive"] }
futures = { workspace = true }
hyper = { version = "0.14.23", features = ["full"] }
hyper-rustls = "0.24.0"
mockall = "0.11.3"
nix = { workspace = true }
opentelemetry = { version = "0.20", features = ["metrics"] }
opentelemetry-prometheus = "0.13.0"
prometheus = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = "3.3.0"
thiserror = "1.0.37"
tokio = { workspace = true }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["json"] }
x509-parser = "0.15.1"
