[package]
name = "certificate-syncer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
async-trait = "0.1.59"
axum = { version = "0.6.1", features = ["json"] }
candid = { workspace = true }
clap = { version = "4.0.29", features = ["derive"] }
futures = { workspace = true }
hyper = { version = "0.14.23", features = ["full"] }
hyper-rustls = "0.24.0"
mockall = "0.11.3"
nix = { version = "0.26.1", features = ["signal"] }
opentelemetry = { version = "0.20", features = ["metrics"] }
opentelemetry-prometheus = "0.13.0"
prometheus = "0.13.3"
serde = { version = "1.0.150", features = ["serde_derive"] }
serde_json = "1.0.89"
tempfile = "3.3.0"
thiserror = "1.0.37"
tokio = { version = "1.32.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["json"] }
x509-parser = "0.15.1"
