[package]
name = "setupos-inject-configuration"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.3", features = ["derive"] }
ipnet = "2.8.0"
tempfile = "3.8.0"
tokio = { version = "1.32.0", features = ["full"] }
