[package]
name = "setupos-inject-configuration"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.3", features = ["derive"] }
ipnet = "2.8.0"
partition_tools = { path = "../partition_tools" }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
tempfile = "3.8.0"
tokio = { workspace = true }
url = { version = "2.1.1", features = ["serde"] }
utils = { path = "../utils"}
