[package]
name = "canary-proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
bytes = "1.5.0"
clap = { version = "4.4.6", features = ["derive"] }
futures-util = "0.3.28"
http = "1.0.0"
http-body = "1.0.0"
http-body-util = "0.1.0"
hyper = { version = "=1.0.1", features = ["full"] }
once_cell = "1.18.0"
pin-project-lite = "0.2.13"
regex = "1.10.2"
tokio = { version = "1.33.0", features = ["full"] }
tracing = "0.1.35"
tracing-subscriber = { version = "0.3.11", features = ["json"] }

[dev-dependencies]
tokio-test = "0.4"
