[package]
name = "ic-protobuf"
version = "0.8.0"
edition = "2021"

[dependencies]
bincode = "1.2.1"
candid = { workspace = true }
erased-serde = "0.3.11"
maplit = "1.0.2"
prost = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
slog = { version = "2.5", features = ["nested-values"] }

[dev-dependencies]
hex = "0.4.2"
ic-protobuf-generator = { path = "./generator" }
ic-test-utilities-compare-dirs = { path = "../test_utilities/compare_dirs" }
tempfile = "3.1.0"
