[package]
name = "ic-recovery"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.13.0"
clap = { version = "3.1.6", features = ["derive"] }
futures = { workspace = true }
hex = "0.4.2"
ic-artifact-pool = { path = "../artifact_pool" }
ic-base-types = { path = "../types/base_types/" }
ic-canister-sandbox-backend-lib = { path = "../canister_sandbox/backend_lib" }
ic-canister-sandbox-launcher = { path = "../canister_sandbox/sandbox_launcher" }
ic-config = { path = "../config" }
ic-crypto-utils-threshold-sig-der = { path = "../crypto/utils/threshold_sig_der" }
ic-cup-explorer = { path = "../cup_explorer" }
ic-logger = { path = "../monitoring/logger" }
ic-http-utils = { path = "../http_utils" }
ic-interfaces = { path = "../interfaces" }
ic-interfaces-registry = { path = "../interfaces/registry" }
ic-metrics = { path = "../monitoring/metrics" }
ic-protobuf = { path = "../protobuf" }
ic-registry-client = { path = "../registry/client" }
ic-registry-client-helpers = { path = "../registry/helpers" }
ic-registry-keys = { path = "../registry/keys" }
ic-registry-local-store = { path = "../registry/local_store" }
ic-registry-nns-data-provider = { path = "../registry/nns_data_provider" }
ic-registry-replicator = { path = "../orchestrator/registry_replicator" }
ic-registry-routing-table = { path = "../registry/routing_table" }
ic-registry-subnet-features = { path = "../registry/subnet_features" }
ic-replay = { path = "../replay" }
ic-state-manager = { path = "../state_manager" }
ic-ic00-types = { path = "../types/ic00_types" }
ic-types = { path = "../types/types" }
prost = { workspace = true }
reqwest = { version = "0.11.1", features = [
    "blocking",
    "json",
    "multipart",
    "native-tls",
] }
serde = { version = "1.0.115", features = ["derive"] }
serde_cbor = "0.11.1"
serde_json = "1.0.54"
slog = { version = "2.5.2", features = ["release_max_level_trace"] }
slog-async = { version = "2.5", features = ["nested-values"] }
slog-term = "2.6.0"
strum = "0.24.1"
strum_macros = "0.24.1"
tokio = { version = "1.32.0", features = ["full"] }
url = { version = "2.1.1", features = ["serde"] }

[dev-dependencies]
tempfile = "3.1.0"
ic-test-utilities = { path = "../test_utilities" }
ic-test-utilities-tmpdir = { path = "../test_utilities/tmpdir" }

[[bin]]
name = "ic-recovery"
path = "src/main.rs"
