[package]
name = "boundary-node-prober"
version = "0.9.0"
edition = "2021"

[[bin]]
name = "boundary-node-prober"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.56"
async-trait = "0.1.53"
axum = "0.6.1"
candid = { workspace = true }
clap = { version = "3.1.8", features = ["derive"] }
futures = "0.3.21"
glob = "0.3.0"
humantime = "2.1.0"
hyper = "0.14.18"
ic-agent = { workspace = true }
ic-utils = { workspace = true }
indoc = "1.0.6"
mockall = "0.11.0"
opentelemetry = { version = "0.20", features = ["metrics"] }
opentelemetry-prometheus = "0.13.0"
prometheus = "0.13.3"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
tempfile = "3.3.0"
tokio = { version = "1.17.0", features = ["full"] }
tracing = "0.1.34"
tracing-subscriber = { version = "0.3.11", features = ["json"] }
wat = "1.0.52"
