[package]
name = "ic-types"
version = "0.8.0"
edition = "2021"

[dependencies]
base64 = "0.11.0"
bincode = "1.2.1"
candid = { workspace = true }
derive_more = { git = "https://github.com/dfinity-lab/derive_more", branch = "master" }
hex = "0.4.2"
ic-base-types = { path = "../base_types" }
ic-btc-types-internal = { path = "../../bitcoin/types/internal" }
ic-constants = { path = "../../constants" }
ic-crypto-internal-types = { path = "../../crypto/internal/crypto_lib/types" }
ic-crypto-sha2 = { path = "../../crypto/sha2" }
ic-crypto-tree-hash = { path = "../../crypto/tree_hash" }
ic-error-types = { path = "../error_types" }
ic-ic00-types = { path = "../ic00_types" }
ic-protobuf = { path = "../../protobuf" }
ic-utils = { path = "../../utils" }
maplit = "1.0.2"
once_cell = "1.8"
phantom_newtype = { path = "../../phantom_newtype" }
prost = "0.11.0"
serde = { version = "1.0.99", features = ["derive"] }
serde_bytes = "0.11"
serde_cbor = "0.11.1"
serde_json = "1.0.40"
serde_with = "1.6.2"
strum = "0.23.0"
strum_macros = "0.23.0"
thiserror = "1.0"
thousands = "0.2.0"

[target.'cfg(not(all(target_arch = "wasm32", target_os = "unknown")))'.dependencies]
chrono = "0.4"

[dev-dependencies]
assert_matches = "1.5.0"
hex-literal = "0.2.1"
ic-crypto-test-utils-canister-threshold-sigs = { path = "../../crypto/test_utils/canister_threshold_sigs" }
ic-exhaustive-derive = { path = "../exhaustive_derive" }
pretty_assertions = "0.6.1"
rand = "0.8"
rusty-fork = "0.3.0"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
proptest = "1.0"
proptest-derive = "0.3.0"
