[package]
name = "pocket-ic-backend"
version = "0.0.1"
edition = "2021"

[dependencies]
axum = "^0.6"
candid = "^0.9"
rand = "^0.8.5"
itertools = "0.11"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "^1.0"
pocket-ic = { path = "../../packages/pocket-ic" }
ic-state-machine-tests = { path = "../state_machine_tests" }
ic-config = { path = "../config" }
ic-registry-subnet-type = { path = "../registry/subnet_type" }
ic-crypto = { path = "../crypto" }
ic-types = { path = "../types/types" }
ic-crypto-iccsa = { path = "../crypto/iccsa" }
ic-cdk = "0.10"
hex = "0.4.2"
ic-crypto-utils-threshold-sig-der = { path = "../crypto/utils/threshold_sig_der" }
clap = { version = "3.1.6", features = ["derive"] }
tempfile = "*"

[dev-dependencies]
reqwest = "*"
