[package]
name = "ic-crypto-sha3"
description = "Library for SHA-3 and Keccak hashing"
version.workspace = true
authors.workspace = true
edition.workspace = true
documentation.workspace = true

[dependencies]
sha3 = "0.9.1"

[dev-dependencies]
hex = "0.4.3"
