
[package]
name = "ic-rosetta-api"
version = "1.7.2"
authors = ["The Internet Computer Project Developers"]
description = "Build Once. Integrate Your Blockchain Everywhere. "
edition = "2021"
default-run = "ic-rosetta-api"

[dependencies]
actix-rt = "2.2.0"
actix-web = { version = "4.0.1", default_features = false, features = ["macros", "compress-brotli", "compress-gzip", "cookies"] }
async-trait = "0.1.41"
base64 = "0.13.0"
candid = "0.8.1"
clap = { version = "3.1.6", features = ["derive"] }
dfn_candid = {path = "../rust_canisters/dfn_candid"}
dfn_macro = {path = "../rust_canisters/dfn_macro"}
dfn_protobuf = {path = "../rust_canisters/dfn_protobuf"}
hex = "0.4.2"
garcon = "0.2"
ic-agent = "0.22.0"
ic-canister-client = { path = "../canister_client" }
ic-canister-client-sender = { path = "../canister_client/sender" }
ic-constants = { path = "../constants" }
ic-crypto-internal-threshold-sig-bls12381 = { path = "../crypto/internal/crypto_lib/threshold_sig/bls12_381" }
ic-crypto-sha = {path = "../crypto/sha/"}
ic-crypto-tree-hash = { path = "../crypto/tree_hash" }
ic-crypto-utils-threshold-sig-der = { path = "../crypto/utils/threshold_sig_der" }
ic-interfaces = { path = "../interfaces" }
ic-ledger-canister-blocks-synchronizer = { path = "ledger_canister_blocks_synchronizer" }
ic-ledger-canister-core = { path = "ledger_canister_core" }
ic-ledger-core = { path = "ledger_core" }
ic-nns-common = { path = "../nns/common" }
ic-nns-constants = { path = "../nns/constants" }
ic-nns-governance = { path = "../nns/governance" }
ic-types = { path = "../types/types" }
lazy_static = "1.4.0"
icp-ledger = { path = "icp_ledger" }
log = "0.4.14"
log4rs = "1.1.1"
on_wire = {path = "../rust_canisters/on_wire"}
prometheus = "0.12.0"
rand = "0.8"
reqwest = "0.11.1"
serde = "1.0"
serde_cbor = "0.11"
serde_derive = "1.0"
serde_json = "1.0"
strum = "0.23"
strum_macros = "0.23"
tempfile = "3.1.0"
tokio = { version = "1.23.1", features = ["full"] }
url = "2.2.1"

[dev-dependencies]
ic-cdk = { version = "0.6.0" }
ic-nns-governance = { path = "../nns/governance" }
ic-ledger-canister-blocks-synchronizer-test-utils = { path = "ledger_canister_blocks_synchronizer/test_utils" }
ic-rosetta-test-utils = { path = "test_utils" }
ic-base-types = { path = "../types/base_types" }
ic-types = { path = "../types/types" }
rand_chacha = "0.3.1"
futures = "0.3.13"

[[test]]
name = "rosetta-api-tests"
path = "test/test_utils.rs"
