[package]
name = "ic-certification"
version = "0.8.0"
edition = "2021"

[dependencies]
ic-crypto-tree-hash = { path = "../crypto/tree_hash" }
ic-crypto-utils-threshold-sig = { path = "../crypto/utils/threshold_sig" }
ic-crypto-utils-threshold-sig-der = { path = "../crypto/utils/threshold_sig_der" }
ic-types = { path = "../types/types" }
hex = "0.4.2"
serde = { version = "1.0.99", features = ["derive"] }
serde_cbor = "0.11.1"
tree-deserializer = { path = "../tree_deserializer" }

[dev-dependencies]
assert_matches = "1.5.0"
criterion = { version = "0.5", features = ["html_reports"] }
ic-base-types = { path = "../types/base_types" }
ic-certification-test-utils = { path = "test-utils" }
ic-crypto-internal-types = { path = "../crypto/internal/crypto_lib/types" }
leb128 = "0.2.4"
rand = "0.8.3"


[[bench]]
name = "certification"
harness = false
