[package]
name = "ic-crypto-test-utils-multi-sigs"
version = "0.8.0"
edition = "2021"

[dependencies]
ic-crypto-temp-crypto = { path = "../../temp_crypto" }
ic-interfaces = { path = "../../../interfaces" }
ic-registry-client-fake = { path = "../../../registry/fake" }
ic-registry-keys = { path = "../../../registry/keys" }
ic-registry-proto-data-provider = { path = "../../../registry/proto_data_provider" }
ic-types = { path = "../../../types/types" }
rand = "0.8"
rand_chacha = "0.3"
