[package]
name = "ic-state-sync-manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.12"
base64 = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
ic-async-utils = { path = "../../async_utils" }
ic-interfaces = { path = "../../interfaces" }
ic-logger = { path = "../../monitoring/logger" }
ic-metrics = { path = "../../monitoring/metrics" }
ic-protobuf = { path = "../../protobuf" }
ic-quic-transport = { path = "../quic_transport" }
ic-types = { path = "../../types/types" }
prometheus = { workspace = true }
prost = { workspace = true }
rand = "0.8.5"
slog = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
tokio = { workspace = true }
tokio-metrics = "0.3.0"
zstd = "0.12.4"

[dev-dependencies]
ic-memory-transport = { path = "../memory_transport" }
ic-p2p-test-utils = { path = "../test_utils" }
ic-test-utilities-logger = { path = "../../test_utilities/logger" }
ic-types-test-utils = { path = "../../types/types_test_utils" }
turmoil = "0.5"
