[package]
name = "ic-state-sync-manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.12"
base64 = "0.11.0"
bytes = "1.0.1"
futures = "0.3.10"
ic-async-utils = { path = "../../async_utils" }
ic-interfaces = { path = "../../interfaces" }
ic-logger = { path = "../../monitoring/logger" }
ic-metrics = { path = "../../monitoring/metrics" }
ic-protobuf = { path = "../../protobuf" }
ic-quic-transport = { path = "../quic_transport" }
ic-types = { path = "../../types/types" }
prometheus = { version = "0.12.0", features = [ "process" ] }
prost = "0.11.0"
rand = "0.8.5"
serde = { version = "1.0.99", features = [ "derive" ] }
slog = { version = "2.5.2", features = ["nested-values", "release_max_level_debug"] }
strum = "0.23.0"
strum_macros = "0.23.0"
tokio = { version = "1.28.0", features = ["full"] }
tokio-metrics = "0.2.2"

[dev-dependencies]
ic-memory-transport = { path = "../memory_transport" }
ic-p2p-test-utils = { path = "../test_utils" }
ic-test-utilities-logger = { path = "../../test_utilities/logger" }
ic-types-test-utils = { path = "../../types/types_test_utils" }
turmoil = "0.5"

