[package]
name = "ic-sns-init"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
base64 = "0.11.0"
candid = { workspace = true }
dfn_candid = { path = "../../rust_canisters/dfn_candid" }
ic-base-types = { path = "../../types/base_types" }
ic-crypto-sha2 = { path = "../../crypto/sha2" }
ic-icrc1 = { path = "../../rosetta-api/icrc1" }
ic-icrc1-index = { path = "../../rosetta-api/icrc1/index" }
ic-icrc1-ledger = { path = "../../rosetta-api/icrc1/ledger" }
ic-ledger-core = { path = "../../rosetta-api/ledger_core" }
ic-ledger-canister-core = { path = "../../rosetta-api/ledger_canister_core" }
ic-nervous-system-common = { path = "../../nervous_system/common" }
ic-nervous-system-proto = { path = "../../nervous_system/proto" }
dfn_core = { path = "../../rust_canisters/dfn_core" }
ic-nns-constants = { path = "../../nns/constants" }
ic-sns-governance = { path = "../governance" }
ic-sns-root = { path = "../root" }
ic-sns-swap = { path = "../swap" }
icrc-ledger-types = { path = "../../../packages/icrc-ledger-types" }
isocountry = "0.3.2"
lazy_static = "1.4.0"
maplit = "1.0.2"
num = "0.4.0"
prost = "0.11.0"
regex = "1.5.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.79"
serde_yaml = "0.8.24"

[dev-dependencies]
assert_approx_eq = "1.1.0"
ic-nervous-system-common-test-keys = { path = "../../nervous_system/common/test_keys" }
ic-sns-init-protobuf-generator = { path = "protobuf_generator" }
ic-test-utilities-compare-dirs = { path = "../../test_utilities/compare_dirs" }
num-traits = "0.2"
tempfile = "3.1.0"

[features]
test = []
