[package]
name = "ic-canister-sandbox-replica-controller"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
ic-canister-sandbox-common = { path = "../common" }
ic-canister-sandbox-backend-lib = { path = "../backend_lib" }
ic-embedders = { path = "../../embedders" }
ic-interfaces = { path = "../../interfaces" }
ic-logger = { path = "../../monitoring/logger" }
ic-metrics = { path = "../../monitoring/metrics" }
ic-config = { path = "../../config" }
ic-replicated-state = { path = "../../replicated_state" }
ic-sys = { path = "../../sys" }
ic-system-api = { path = "../../system_api" }
ic-types = { path = "../../types/types" }
ic-wasm-types = { path = "../../types/wasm_types" }
lazy_static = "1.4.0"
serde_json = { workspace = true }
libc = "0.2.119"
nix = { workspace = true }
once_cell = "1.8"
prometheus = { workspace = true }
regex = "1.5.4"
slog = { workspace = true }
which = "4.2.2"

[dev-dependencies]
ic-config = { path = "../../config" }
ic-test-utilities = { path = "../../test_utilities" }
slog-async = { version = "2.5", features = ["nested-values"] }
slog-term = "2.6.0"
tempfile = "3.1.0"
wat = "1.0.52"

[features]
sigsegv_handler_checksum = []
