[package]
name = "ic-crypto-internal-threshold-sig-ecdsa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fe-derive = { path = "fe-derive" }
ic-crypto-sha2 = { path = "../../../../sha2" }
ic-crypto-internal-seed = { path = "../../seed" }
ic-crypto-internal-types = { path = "../../types" }
ic-crypto-internal-hmac = { path = "../../hmac" }
ic-crypto-secrets-containers = { path = "../../../../secrets_containers" }
ic-types = { path = "../../../../../types/types" }
k256 = { workspace = true }
p256 = { workspace = true }
zeroize = { version = "1.4.3", features = ["zeroize_derive"] }
rand = "0.8"
rand_chacha = "0.3"
hex = "0.4"
hex-literal = "0.3.3"
paste = "1.0.0"
subtle = "2.4"
serde = "1.0.130"
serde_cbor = "0.11.1"
serde_bytes = "0.11"
strum = "0.23.0"
strum_macros = "0.23.0"
lazy_static = "1.4.0"

[dev-dependencies]
assert_matches = "1.5.0"
criterion = { version = "0.5", features = ["html_reports"] }
ic-crypto-test-utils-reproducible-rng = { path = "../../../../test_utils/reproducible_rng" }
bip32 = { version = "0.4", features = ["secp256k1"] }
num-traits = { version = "0.2.15" }

[[bench]]
name = "field_ops"
harness = false

[[bench]]
name = "poly"
harness = false

[[bench]]
name = "hash2curve"
harness = false

[[bench]]
name = "dealings"
harness = false

[[bench]]
name = "zk"
harness = false

[[bench]]
name = "group_ops"
harness = false
