[package]
name = "ic-crypto-internal-bls12-381-vetkd"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
ic-crypto-internal-bls12-381-type = { path = "../type" }
zeroize = { version = "1", features = ["zeroize_derive"] }
rand = "0.8"
ic-crypto-sha3 = { path = "../../../../sha3" }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
ic-crypto-test-utils-reproducible-rng = { path = "../../../../test_utils/reproducible_rng" }
hex = "0.4"

[[bench]]
name = "vetkd"
harness = false
