[package]
name = "ic-canister-sandbox-common"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[lib]
name = "ic_canister_sandbox_common"
path = "src/lib.rs"

[[bin]]
name = "test_controller"
path = "src/test_controller.rs"

[[bin]]
name = "test_sandbox"
path = "src/test_sandbox.rs"

[dependencies]
bincode = "1.3.3"
bytes = { workspace = true }
serde_bytes = { workspace = true }
ic-interfaces = { path = "../../interfaces" }
ic-embedders = { path = "../../embedders" }
ic-replicated-state = { path = "../../replicated_state" }
ic-registry-subnet-type = { path = "../../registry/subnet_type" }
ic-system-api = { path = "../../system_api" }
ic-types = { path = "../../types/types" }
ic-utils = { path = "../../utils" }
ic-sys = { path = "../../sys" }
serde = { workspace = true }
nix = { workspace = true }
libc = "0.2.119"
