[package]
name = "ic-crypto-test-utils-canister-threshold-sigs"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
ic-crypto-internal-csp = { path = "../../internal/crypto_service_provider" }
ic-crypto-internal-threshold-sig-ecdsa = { path = "../../internal/crypto_lib/threshold_sig/tecdsa" }
ic-crypto-temp-crypto = { path = "../../temp_crypto" }
ic-crypto-test-utils-reproducible-rng = { path = "../../test_utils/reproducible_rng" }
ic-interfaces = { path = "../../../interfaces" }
ic-logger = { path = "../../../monitoring/logger" }
ic-protobuf = { path = "../../../protobuf" }
ic-registry-client-fake = { path = "../../../registry/fake" }
ic-registry-keys = { path = "../../../registry/keys" }
ic-registry-proto-data-provider = { path = "../../../registry/proto_data_provider" }
ic-test-utilities-in-memory-logger = { path = "../../../test_utilities/in_memory_logger" }
ic-types = { path = "../../../types/types" }
assert_matches = "1.5.0"
rand = "0.8"
rand_chacha = "0.3"
