[package]
name = "prometheus_config_updater"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.31"
clap = { workspace = true }
crossbeam = "0.8.0"
crossbeam-channel = "0.5.5"
futures-util = "0.3.5"
humantime = "2.0"
ic-async-utils = { path = "../../async_utils" }
ic-metrics = { path = "../../monitoring/metrics" }
ic-types = { path = "../../types/types" }
ic-crypto-utils-threshold-sig-der = { path = "../../crypto/utils/threshold_sig_der" }
base64 = { workspace = true }
regex = "1.7.0"
serde = { workspace = true }
serde_json = { workspace = true }
service-discovery = { path = "../service_discovery" }
slog = { workspace = true }
slog-async = { version = "2.5", features = ["nested-values"] }
slog-term = "2.6.0"
tokio = { workspace = true }
url = { version = "2.1.1", features = ["serde"] }
config_writer_common = { path = "../config_writer_common" }
ic-config = { path = "../../config" }
ic-http-endpoints-metrics = { path = "../../http_endpoints/metrics" }

[[bin]]
name = "prometheus_config_updater"
path = "src/main.rs"
