[package]
name = "ic-p2p"
version = "0.8.0"
edition = "2021"

[dependencies]
async-trait = "0.1.36"
bincode = "1.2.1"
futures = "0.3.10"
ic-config = { path = "../config" }
ic-interfaces = { path = "../interfaces" }
ic-interfaces-p2p = { path = "../interfaces/p2p" }
ic-interfaces-registry = { path = "../interfaces/registry" }
ic-interfaces-transport = { path = "../interfaces/transport" }
ic-types = { path = "../types/types" }
ic-protobuf = { path = "../protobuf" }
ic-logger = { path = "../monitoring/logger" }
ic-metrics = { path = "../monitoring/metrics" }
ic-registry-client-helpers = { path = "../registry/helpers" }
ic-registry-subnet-type = { path = "../registry/subnet_type" }
linked-hash-map = "0.5.3"
lru = { version = "0.7.1", default-features = false }
parking_lot = "0.12.1"
prometheus = { version = "0.12.0", features = [ "process" ] }
serde = { version = "1.0.99", features = [ "derive" ] }
slog = { version = "2.5.2", features = ["nested-values", "release_max_level_debug"] }
strum = "0.23.0"
strum_macros = "0.23.0"
threadpool = "1.8.1"
tokio = { version = "1.24.2", features = ["full"] }
tower = "0.4.12"

[dev-dependencies]
ic-artifact-manager = { path = "../artifact_manager" }
ic-https-outcalls-adapter-client = { path = "../https_outcalls/client" }
ic-cycles-account-manager = { path = "../cycles_account_manager" }
ic-execution-environment = { path = "../execution_environment" }
ic-interfaces-transport-mocks = { path = "../interfaces/transport/mocks" }
ic-logger = { path = "../monitoring/logger" }
ic-registry-client = { path = "../registry/client" }
ic-registry-client-fake = { path = "../registry/fake" }
ic-registry-nns-data-provider = { path = "../registry/nns_data_provider" }
ic-registry-subnet-type = { path = "../registry/subnet_type" }
ic-replica-setup-ic-network = { path = "../replica/setup_ic_network" }
ic-test-utilities = { path = "../test_utilities" }
ic-test-utilities-metrics = { path = "../test_utilities/metrics" }
ic-test-utilities-registry = { path = "../test_utilities/registry" }
mockall = "0.7.2"
tempfile = "3.1.0"
