[package]
name = "ic-crypto-ecdsa-secp256k1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
k256 = { workspace = true }
lazy_static = "1.4"
num-bigint = "0.4"
pem = "1.1.0"
rand = "0.8"
simple_asn1 = "0.6.1"
zeroize = { version = "1.5", features = ["zeroize_derive"] }

[dev-dependencies]
hex = "0.4"
ic-crypto-sha2 = { path = "../sha2" }
ic-crypto-test-utils-reproducible-rng = { path = "../test_utils/reproducible_rng" }
wycheproof = "0.5"
