[package]
name = "ic-crypto-internal-multi-sig-bls12381"
version = "0.8.0"
edition = "2021"

[dependencies]
base64 = "0.11.0"
hex = "0.4.2"
ic-crypto-internal-bls12-381-type = { path = "../../bls12_381/type"}
ic-crypto-internal-types = { path = "../../types" }
ic-crypto-secrets-containers = { path = "../../../../secrets_containers" }
ic-crypto-sha2 = { path= "../../../../sha2" }
ic-protobuf = { path = "../../../../../protobuf" }
ic-types = { path = "../../../../../types/types" }
rand = "0.8"
rand_chacha = "0.3"
serde = { version = "1.0.99", features = [ "derive" ] }
zeroize = { version = "1.4.3", features = ["zeroize_derive"] }

[dev-dependencies]
ic-crypto-internal-test-vectors = { path = "../../../test_vectors" }
proptest = "1.0"
serde_cbor = "0.11"
