[package]
name = "ic-icrc-rosetta"
version = "0.1.0"
authors = ["The Internet Computer Project Developers"]
description = "Build Once. Integrate Your Blockchain Everywhere. "
default-run = "ic-icrc-rosetta"
edition = "2021"


[[bin]]
name = "ic-icrc-rosetta"
path = "src/main.rs"

[dependencies]
rusqlite = { version = "~0.28.0", features = ["bundled"] }
ic-ledger-core = { path = "../../ledger_core" }
ic-ledger-canister-core = { path = "../../ledger_canister_core" }
ic-base-types = { path = "../../../types/base_types" }
anyhow = { version = "1.0", default-features = false }
tempfile = "3.1.0"
candid = { workspace = true }
serde_bytes = "0.11"
serde = "1"
serde_json = "1.0.82"
serde_cbor = "0.11.2"
serde_with = "1.6.2"
num-traits = "0.2.12"
ciborium = { workspace = true }
icrc-ledger-types = { path = "../../../../packages/icrc-ledger-types" }
ic-icrc1-ledger = { path = "../ledger" }
ic-icrc1 = { path = ".." }
ic-icrc1-tokens-u64 = { path = "../tokens_u64" }
proptest = "1.0"
rand = "0.8.4"
axum = "0.6.1"
url = "2.2.1"
clap = { version = "4.0.29", features = ["derive"] }
tokio = { version = "1.32.0", features = ["full"] }
ic-agent = { workspace = true }
icrc-ledger-agent = { path = "../../../../packages/icrc-ledger-agent" }
hex = "0.4.2"
ic-crypto-tree-hash = { path = "../../../crypto/tree_hash" }
lazy_static = "1.4.0"
http = "0.2.9"
tower-http = { version = "0.4.0", features = ["trace"] }
tower-request-id = "0.2.1"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["json"] }
indicatif = "0.17.3"

[lib]
path = "src/lib.rs"

[dev-dependencies]
ic-icrc1-ledger-sm-tests = { path = "../ledger/sm-tests" }
ic-icrc1-test-utils = { path = "../test_utils" }
ic-base-types = { path = "../../../types/base_types" }
ic-ledger-canister-core = { path = "../../ledger_canister_core" }
ic-ic00-types = { path = "../../../types/ic00_types" }
ic-starter-tests = { path = "../../../../packages/ic-starter-tests" }
ic-test-utilities-load-wasm = { path = "../../../test_utilities/load_wasm" }
url = "2.3.1"
once_cell = "1.8.0"
ring = { version = "0.16.11", features = ["std"] }
reqwest = "0.11.1"
futures = { workspace = true }
ic-icrc-rosetta-client = { path = "client" }
ic-icrc-rosetta-runner = { path = "runner" }


[[test]]
name = "integration_tests"
path = "tests/integration_tests.rs"


