[package]
name = "ic-base-types"
version = "0.8.0"
edition = "2021"

[dependencies]
arbitrary = { version = "=1.3.0", optional = true }
base32 = "0.4.0"
bytes = { workspace = true }
byte-unit = "4.0.14"
candid = { workspace = true }
comparable = { version = "0.5.1", features = ["derive"] }
crc32fast = "1.2.0"
ic-crypto-sha2 = { path = "../../crypto/sha2" }
ic-protobuf = { path = "../../protobuf" }
ic-stable-structures = { workspace = true }
phantom_newtype = { path = "../../phantom_newtype" }
prost = { workspace = true }
serde = { version = "1.0.99", features = ["derive"] }
strum = "0.23.0"
strum_macros = "0.23.0"

[dev-dependencies]
assert_matches = "1.3.0"
ic-base-types-protobuf-generator = { path = "./protobuf_generator" }
ic-test-utilities-compare-dirs = { path = "../../test_utilities/compare_dirs" }
proptest = "1.0"
proptest-derive = "0.3.0"
serde_cbor = "0.11.1"
tempfile = "3.1.0"

[features]
fuzzing_code = ["dep:arbitrary"]
