[package]
name = "ic-canister-http-adapter-client"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

candid = "0.8.1"
futures = "0.3.21"
ic-adapter-metrics = { path = "../../monitoring/adapter_metrics" }
ic-async-utils = { path = "../../async_utils" }
ic-canister-http-service = { path = "../service" }
ic-config = { path = "../../config" }
ic-error-types = { path = "../../types/error_types" }
ic-ic00-types = { path = "../../types/ic00_types" }
ic-interfaces = { path = "../../interfaces" }
ic-interfaces-canister-http-adapter-client = { path = "../../interfaces/canister_http_adapter_client" }
ic-logger = { path = "../../monitoring/logger" }
ic-metrics = { path = "../../monitoring/metrics" }
ic-protobuf = { path = "../../protobuf" }
ic-types = { path = "../../types/types" }
prometheus = { version = "0.12.0", features = [ "process" ] }
slog = "2.7.0"
tokio = { version = "1.23.1", features = ["full"] }
tonic = "0.8.2"
tower = { version = "0.4.8", features = ["util"] }

[dev-dependencies]
tower-test = "0.4.0"
ic-test-utilities = { path = "../../test_utilities" }
