[package]
name = "ic-balance-exporter"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ic-balance-exporter"
src = "src/main.rs"

[dependencies]
anyhow = "1.0.56"
async-trait = "0.1.53"
axum = "0.6.1"
candid = "0.8.1"
clap = { version = "3.1.8", features = ["derive"] }
dashmap = "5.3.4"
futures = "0.3.21"
humantime = "2.1.0"
hyper = "0.14.18"
ic-agent = "0.22.0"
indoc = "1.0.6"
mockall = "0.11.1"
opentelemetry = "0.17.0"
opentelemetry-prometheus = "0.10.0"
prometheus = "0.13.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
tempfile = "3.3.0"
tokio = { version = "1.24.2", features = ["full"] }
tracing = "0.1.34"
tracing-subscriber = { version = "0.3.11", features = ["json"] }
