[package]
name = "ic-balance-exporter"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[[bin]]
name = "ic-balance-exporter"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.56"
async-trait = "0.1.53"
axum = "0.6.1"
candid = { workspace = true }
clap = { workspace = true }
dashmap = "5.3.4"
futures = { workspace = true }
humantime = "2.1.0"
hyper = "0.14.18"
ic-agent = { workspace = true }
indoc = "1.0.9"
mockall = "0.11.1"
opentelemetry = { version = "0.20", features = ["metrics"] }
opentelemetry-prometheus = "0.13.0"
prometheus = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = "3.3.0"
tokio = { workspace = true }
tracing = "0.1.34"
tracing-subscriber = { version = "0.3.11", features = ["json"] }
