[package]
name = "ic-registry-nns-data-provider"
version = "0.8.0"
edition = "2021"

[dependencies]
ic-canister-client = { path = "../../canister_client" }
ic-certification = { path = "../../certification" }
ic-crypto-tree-hash = { path = "../../crypto/tree_hash" }
ic-interfaces-registry = { path = "../../interfaces/registry" }
ic-nns-constants = { path = "../../nns/constants" }
ic-registry-transport = { path = "../transport" }
ic-types = { path = "../../types/types" }
chrono = "0.4.19"
prost = { workspace = true }
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
tree-deserializer = { path = "../../tree_deserializer" }
url = { version = "2.1.1", features = ["serde"] }

[dev-dependencies]
ic-certification-test-utils = { path = "../../certification/test-utils" }
leb128 = "0.2.4"
