[package]
name = "ic-icrc1-archive"
version = "0.8.0"
authors = ["The Internet Computer Project Developers"]
description = "An archive canister for the ICRC-1 ledger"
edition = "2021"

[dependencies]
candid = { workspace = true }
ciborium = { workspace = true }
ic-base-types = { path = "../../../types/base_types" }
ic-canisters-http-types = { path = "../../../rust_canisters/http_types" }
ic-cdk = { workspace = true }
ic-cdk-macros = { workspace = true }
ic-icrc1 = { path = "../" }
ic-icrc1-tokens-u64 = { path = "../tokens_u64" }
ic-icrc1-tokens-u256 = { path = "../tokens_u256", optional = true }
ic-ledger-core = { path = "../../ledger_core" }
ic-metrics-encoder = "1"
ic-stable-structures = { workspace = true }
icrc-ledger-types = { path = "../../../../packages/icrc-ledger-types" }
serde = "1.0"

[features]
default = []
u256-tokens = ["dep:ic-icrc1-tokens-u256"]
