[package]
name = "hardware_wallet_tests"
version = "0.1.0"
authors = ["Luc Mercier <luc.mercier@dfinity.org>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ic-rosetta-test-utils = {path="../test_utils"}
ed25519-consensus = "2.0.1"
hex = "0.4.2"
ic-canister-client-sender = { path = "../../canister_client/sender" }
ic-ledger-core = { path = "../ledger_core" }
ic-rosetta-api = {path = "../"}
ic-types = { path = "../../types/types" }
icp-ledger = {path = "../icp_ledger"}
log = "0.4.14"
nix = { workspace = true }
rand = "0.8"
rand_distr = "0.4"
serde = { workspace = true }
serde_json = { workspace = true }
serde_cbor = { workspace = true }
tempfile = "3.1.0"
reqwest = { workspace = true }
tokio = { workspace = true }
url = "2.1.1"
ic-nns-constants = { path = "../../nns/constants" }
