[package]
name = "ic-consensus-manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.12"
backoff = { workspace = true }
bytes = { workspace = true }
crossbeam-channel = "0.5.5"
futures = { workspace = true }
ic-async-utils = { path = "../../async_utils" }
ic-artifact-pool = { path = "../../artifact_pool" }
ic-interfaces = { path = "../../interfaces" }
ic-logger = { path = "../../monitoring/logger" }
ic-peer-manager = { path = "../../p2p/peer_manager" }
ic-protobuf = { path = "../../protobuf" }
ic-metrics = { path = "../../monitoring/metrics" }
ic-quic-transport = { path = "../quic_transport" }
ic-types = { path = "../../types/types" }
phantom_newtype = { path = "../../phantom_newtype" }
prometheus = { workspace = true }
rand = "0.8.5"
slog = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
ic-memory-transport = { path = "../memory_transport" }
ic-p2p-test-utils = { path = "../test_utils" }
ic-test-utilities-logger = { path = "../../test_utilities/logger" }
ic-types-test-utils = { path = "../../types/types_test_utils" }
mockall = "0.11.4"
tokio-util = { version = "0.7.4", features = ["codec", "time"] }
turmoil = "0.5"
