[package]
name = "network"
version = "1.0.0"
edition = "2021"

[target.'cfg(target_os = "linux")'.dependencies]
config = {path = "../config"}
utils = {path = "../utils"}
anyhow = {version = "^1"} 
hex = {version = "^0.4.3"}
ping = {version = "^0.5.0"}
regex = {version = "^1.3.9"}
serde = {version = "^1.0.171"}
serde_json = {version = "^1.0.40"}
serde_with = {version = "^1.6.2"}
sha2 = {version = "^0.10.2"}
