[package]
name = "ic-nns-governance"
version = "0.8.0"
edition = "2021"

[[bin]]
name = "governance-canister"
path = "canister/canister.rs"

[lib]
path = "src/lib.rs"

[[test]]
name = "governance-test"
path = "tests/governance.rs"

[[test]]
name = "governance-interleaving-test"
path = "tests/interleaving_tests.rs"

[[bench]]
name = "scale"
harness = false

[dependencies]
# This MUST be kept in sync with build-info-build in the [build-dependencies] section!
build-info = { version = "0.0.26", default-features = false, features = [] }

async-trait = "0.1.42"
bytes = "1.0.1"
candid = { workspace = true }
cycles-minting-canister = { path = "../cmc" }
dfn_core = { path = "../../rust_canisters/dfn_core" }
dfn_candid = { path = "../../rust_canisters/dfn_candid" }
dfn_http_metrics = { path = "../../rust_canisters/dfn_http_metrics" }
dfn_protobuf = { path = "../../rust_canisters/dfn_protobuf" }
ic-base-types = { path = "../../types/base_types" }
ic-crypto-getrandom-for-wasm = { path = "../../crypto/getrandom_for_wasm" }
ic-crypto-sha2 = { path = "../../crypto/sha2/" }
ic-ledger-core = { path = "../../rosetta-api/ledger_core" }
ic-metrics-encoder = "1"
ic-nervous-system-clients = { path = "../../nervous_system/clients" }
ic-nervous-system-common = { path = "../../nervous_system/common" }
ic-nervous-system-common-build-metadata = { path = "../../nervous_system/common/build_metadata" }
ic-nervous-system-governance = { path = "../../nervous_system/governance" }
ic-nervous-system-root = { path = "../../nervous_system/root" }
ic-nervous-system-runtime = { path = "../../nervous_system/runtime" }
ic-nervous-system-proto = { path = "../../nervous_system/proto" }
ic-nns-common = { path = "../common" }
ic-nns-constants = { path = "../constants" }
ic-protobuf = { path = "../../protobuf" }
ic-sns-init = { path = "../../sns/init" }                                                         # This is just for a couple of PB definitions.
ic-sns-root = { path = "../../sns/root" }                                                         # This is just for a couple of PB definitions.
ic-sns-swap = { path = "../../sns/swap" }                                                         # This is just for a couple of PB definitions.
ic-sns-wasm = { path = "../sns-wasm" }
ic-stable-structures = { workspace = true }
ic-types = { path = "../../types/types" }
icp-ledger = { path = "../../rosetta-api/icp_ledger" }
itertools = "0.10.0"
lazy_static = "1.4.0"
maplit = "1.0.2"
on_wire = { path = "../../rust_canisters/on_wire" }
prost = "0.11.0"
serde = { version = "1.0", features = ["derive"] }
rand = "0.8"
rand_chacha = "0.3"
registry-canister = { path = "../../registry/canister" }
strum_macros = "0.23.0"
strum = "0.23.0"
comparable = { version = "0.5", features = ["derive"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
csv = "1.1"
ic-nervous-system-common-test-keys = { path = "../../nervous_system/common/test_keys" }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
assert_matches = "1.3.0"

[build-dependencies]
# This MUST be kept in sync with build-info in the [dependencies] section!
build-info-build = { version = "0.0.26", default-features = false, features = [
] }

[dev-dependencies]
criterion = "0.5"
futures = "0.3.13"
ic-config = { path = "../../config" }
ic-nervous-system-common-test-utils = { path = "../../nervous_system/common/test_utils" }
ic-nns-governance-protobuf-generator = { path = "./protobuf_generator" }
ic-test-utilities-compare-dirs = { path = "../../test_utilities/compare_dirs" }
pretty_assertions = "1.0"
proptest = "1.0"
tempfile = "3.1.0"
tokio = { version = "1.15.0", features = ["full"] }
tokio-test = "0.4.2"

[features]
test = ["ic-sns-swap/test"]
