[package]
name = "ic-ledger-canister-blocks-synchronizer-test-utils"
version = "0.1.0"
authors = ["The Internet Computer Project Developers"]
edition = "2021"

[dependencies]
ic-canister-client-sender = { path = "../../../canister_client/sender" }
ic-cdk = { version = "0.6.0" }
ic-ledger-canister-blocks-synchronizer = { path = "../" }
ic-ledger-core = { path = "../../ledger_core" }
ic-types = { path = "../../../types/types" }
icp-ledger = {path = "../../icp_ledger"}
log = "0.4.14"
log4rs = "1.1.1"
rand = "0.8"
rand_distr = "0.4"
tempfile = "3.1.0"
tokio = { version = "1.24.2", features = ["full"] }
serde = "1.0"
serde_bytes = "0.11"