[package]
name = "ic-quic-transport"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.36"
axum = "0.6.12"
bincode = "1.2.1"
bytes = { workspace = true }
either = "1.6.0"
futures = { workspace = true }
http = "0.2.9"
http-serde = "1.1.2"
ic-async-utils = { path = "../../async_utils" }
ic-crypto-tls-interfaces = { path = "../../crypto/tls_interfaces" }
ic-crypto-utils-tls = { path = "../../crypto/utils/tls" }
ic-icos-sev-interfaces = { path = "../../ic_os/sev_interfaces" }
ic-interfaces-registry = { path = "../../interfaces/registry" }
ic-base-types = { path = "../../types/base_types" }
ic-logger = { path = "../../monitoring/logger" }
ic-metrics = { path = "../../monitoring/metrics" }
ic-peer-manager = { path = "../../p2p/peer_manager" }
ic-registry-client-helpers = { path = "../../registry/helpers" }
phantom_newtype = { path = "../../phantom_newtype" }
prometheus = { version = "0.12.0", features = ["process"] }
quinn = { version = "0.10.2", features = ["ring"] }
serde = { version = "1.0.99", features = ["derive"] }
serde_bytes = "0.11"
slog = { version = "2.5.2", features = [
    "nested-values",
    "release_max_level_debug",
] }
socket2 = { version = "0.5", features = ["all"] }
tokio = { version = "1.32.0", features = ["full"] }
tokio-metrics = "0.3.0"
tokio-rustls = "0.24.0"
tokio-util = { version = "0.7.4", features = ["codec", "time"] }
tower = { workspace = true }

[dev-dependencies]
criterion = { version = "0.3", features = ["async_tokio"] }
ic-icos-sev = { path = "../../ic_os/sev" }
ic-p2p-test-utils = { path = "../test_utils" }
ic-test-utilities-logger = { path = "../../test_utilities/logger" }
ic-types-test-utils = { path = "../../types/types_test_utils" }
turmoil = "0.5"
