[package]
name = "ic-validator-http-request-test-utils"
version = "0.8.0"
edition = "2021"
description = "Test utility to build HTTP requests"

[dependencies]
ic-canister-client-sender = { path = "../../canister_client/sender" }
ic-certification-test-utils = { path = "../../certification/test-utils" }
ic-crypto-internal-basic-sig-der-utils = { path = "../../crypto/internal/crypto_lib/basic_sig/der_utils" }
ic-crypto-iccsa = { path = "../../crypto/iccsa" }
ic-crypto-internal-basic-sig-iccsa-test-utils = { path = "../../crypto/internal/crypto_lib/basic_sig/iccsa/test_utils" }
ic-crypto-internal-threshold-sig-bls12381 = { path = "../../crypto/internal/crypto_lib/threshold_sig/bls12_381" }
ic-crypto-internal-types = { path = "../../crypto/internal/crypto_lib/types" }
ic-crypto-secrets-containers = { path = "../../crypto/secrets_containers" }
ic-crypto-test-utils = { path = "../../crypto/test_utils" }
ic-crypto-tree-hash = { path = "../../crypto/tree_hash" }
ic-types = { path = "../../types/types" }
rand = "0.8"
simple_asn1 = "0.6.1"
strum = "0.23.0"
strum_macros = "0.23.0"

[dev-dependencies]
assert_matches = "1.5.0"
ic-crypto-internal-basic-sig-ed25519 = { path = "../../crypto/internal/crypto_lib/basic_sig/ed25519" }
ic-crypto-test-utils-reproducible-rng = { path = "../../crypto/test_utils/reproducible_rng" }
