[package]
name = "ic-btc-consensus"
version = "0.1.0"
edition = "2021"

[dependencies]
ic-btc-interface = { workspace = true }
ic-btc-types-internal = { path = "../types/internal" }
ic-interfaces = { path = "../../interfaces" }
ic-interfaces-registry = { path = "../../interfaces/registry" }
ic-interfaces-adapter-client = { path = "../../interfaces/adapter_client" }
ic-interfaces-state-manager = { path = "../../interfaces/state_manager" }
ic-logger = { path = "../../monitoring/logger" }
ic-metrics = { path = "../../monitoring/metrics" }
ic-protobuf = { path = "../../protobuf" }
ic-replicated-state = { path = "../../replicated_state" }
ic-registry-client-helpers = { path = "../../registry/helpers" }
ic-registry-subnet-features = { path = "../../registry/subnet_features" }
ic-types = { path = "../../types/types" }
prometheus = { version = "0.12.0", features = [ "process" ] }
prost = "0.11.0"
slog = { version = "2.5.2", features = ["nested-values", "release_max_level_debug"] }
thiserror = "1.0"

[dev-dependencies]
ic-interfaces-state-manager-mocks = { path = "../../interfaces/state_manager/mocks" }
ic-interfaces-registry-mocks = { path = "../../interfaces/registry/mocks" }
ic-test-utilities = { path = "../../test_utilities" }
ic-test-utilities-logger = { path = "../../test_utilities/logger" }
mockall = "0.11.4"
