[package]
name = "ic-test-artifact-pool"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
ic-artifact-pool = { path = "../../artifact_pool" }
ic-config = { path = "../../config" }
ic-consensus = { path = "../../consensus" }
ic-consensus-utils = { path = "../../consensus/utils" }
ic-crypto = { path = "../../crypto" }
ic-interfaces = { path = "../../interfaces" }
ic-interfaces-registry = { path = "../../interfaces/registry" }
ic-interfaces-state-manager = { path = "../../interfaces/state_manager" }
ic-logger = { path = "../../monitoring/logger" }
ic-metrics = { path = "../../monitoring/metrics" }
ic-replicated-state = { path = "../../replicated_state" }
ic-test-utilities = { path = "../" }
ic-types = { path = "../../types/types" }
tempfile = "3.1.0"
