[package]
name = "ic-canister-client-sender"
version = "0.8.0"
edition = "2021"

[dependencies]
ic-base-types = { path = "../../types/base_types" }
ic-crypto-sha2 = { path = "../../crypto/sha2" }
ic-crypto-ecdsa-secp256k1 = { path = "../../crypto/ecdsa_secp256k1" }
ic-crypto-internal-types = { path = "../../crypto/internal/crypto_lib/types" }
ic-crypto-secrets-containers = { path = "../../crypto/secrets_containers" }
ic-crypto-utils-basic-sig = { path = "../../crypto/utils/basic_sig" }
ic-types = { path = "../../types/types" }
ed25519-consensus = "2.0.1"
rand = "0.8"
rand_chacha = "0.3"
simple_asn1 = "0.6.1"
