[package]
name = "dfn_candid"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
serde = { workspace = true }
candid = { workspace = true }
on_wire = { path = "../on_wire" }
dfn_core = { path = "../dfn_core" }
ic-base-types = {path="../../types/base_types"}

[[bin]]
name = "candid-test-canister"
path = "test/wasm.rs"
test = false
doc = false

[dev-dependencies]
canister-test = { path = "../../rust_canisters/canister_test" }

[[test]]
name = "test"
path = "test/test.rs"
