[package]
name = "ic-async-utils"
version = "0.8.0"
edition = "2021"

[dependencies]
async-stream = "0.3.2"
byte-unit = "4.0.14"
derive_more = "0.99.17"
futures = "0.3.13"
futures-util = "0.3.13"
hyper = { version = "0.14.16", features = ["full"] }
ic-types = { path = "../types/types" }
prometheus = { version = "0.12.0", features = [ "process" ] }
slog = "2.5.2"
tokio = { version = "1.24.2", features = ["full"] }
tonic = "0.8.2"
tower =  { version = "0.4.8", features = ["load-shed", "limit", "steer"] }

[dev-dependencies]
bytes = "1.0.1"
rand = "0.8.3"
