[package]
name = "ic-nervous-system-clients"
version = "0.0.1"
edition = "2021"

[lib]
name = "ic_nervous_system_clients"
path = "src/lib.rs"

[dependencies]
async-trait = "0.1.42"
candid = { workspace = true }
dfn_candid = { path = "../../rust_canisters/dfn_candid" }
dfn_core = { path = "../../rust_canisters/dfn_core" }
ic-base-types = { path = "../../types/base_types" }
ic-nervous-system-proxied-canister-calls-tracker = { path = "../proxied_canister_calls_tracker" }
ic-nervous-system-runtime = { path = "../runtime" }
ic-ic00-types = { path = "../../types/ic00_types" }
num-traits = "0.2.15"
serde = { workspace = true }
serde_bytes = { workspace = true }

[dev-dependencies]
