[package]
name = "ic-interfaces-transport"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
ic-base-types = { path = "../../types/base_types" }
phantom_newtype = { path = "../../phantom_newtype" }
serde = { workspace = true }
serde_bytes = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
tower = { workspace = true }
