[package]
name = "ic-nervous-system-proto-protobuf-generator"
version = "0.0.1"
edition = "2021"

[dependencies]
ic-utils-rustfmt = { path = "../../../utils/rustfmt" }
prost-build = { workspace = true }