# This inventory file can be used together with other testnet inventory files,
# in order to reduce config/code duplication between inventory files.
# This is in line with the DRY principle
# https://en.wikipedia.org/wiki/Don%27t_repeat_yourself
#
# Example use:
# ansible-playbook -i env/${network}/hosts,env/shared

prometheus:
  vars:
    stage: all
  hosts:
    prometheus.testnet.dfinity.network:

data_centers:
  ch1:
    vars:
      ipv6_prefix: "2607:f6f0:3004:1"
      ipv6_subnet: "/64"
  dm1:
    vars:
      ipv6_prefix: "2604:6800:258:1"
      ipv6_subnet: "/64"
  fr1:
    vars:
      ipv6_prefix: "2001:4d78:40d"
      ipv6_subnet: "/64"
  ln1:
    vars:
      ipv6_prefix: "2a0b:21c0:4003:2"
      ipv6_subnet: "/64"
  se1:
    vars:
      ipv6_prefix: "2600:c00:2:100"
      ipv6_subnet: "/64"
  sf1-old:
    vars:
      ipv6_prefix: "2607:fb58:9005:42"
      ipv6_subnet: "/64"
  sf1:
    vars:
      ipv6_prefix: "2602:fb2b:100:10"
      ipv6_subnet: "/64"
  zh1:
    vars:
      ipv6_prefix: "2a00:fb01:400:42"
      ipv6_subnet: "/64"
  localhost:
    vars:
      ipv6_prefix: "2a00:fb01:400:42"
      ipv6_subnet: "/64"


physical_hosts:
  vars:
    become_method: sudo

nodes:
  vars:
    ansible_user: admin
    become_user: root
    become_method: sudo
    p2p_listen_port: 4100
    p2p_listen_ip: "{{ ipv6_address }}"
    p2p_listen_addr: "[{{ p2p_listen_ip }}]:{{ p2p_listen_port }}"

    xnet_listen_port: 2497
    xnet_listen_ip: "{{ ipv6_address }}"
    xnet_listen_addr: "[{{ xnet_listen_ip }}]:{{ xnet_listen_port }}"

    api_listen_port: 8080
    api_listen_ip: "{{ ipv6_address }}"
    api_listen_addr: "[{{ api_listen_ip }}]:{{ api_listen_port }}"
    api_listen_protocol: http
    api_listen_url: "{{ api_listen_protocol }}://{{ api_listen_addr }}"

    metrics_listen_port: 9090
    metrics_listen_ip: "{{ ipv6_address }}"
    metrics_listen_addr: "[{{ metrics_listen_ip }}]:{{ metrics_listen_port }}"

    node_exporter_metrics_listen_ip: "{{ ipv6_address }}"
    node_exporter_metrics_listen_port: 9100
    node_exporter_metrics_listen_addr: "[{{ node_exporter_metrics_listen_ip }}]:{{ node_exporter_metrics_listen_port }}"

    orchestrator_metrics_listen_ip: "{{ ipv6_address }}"
    orchestrator_metrics_listen_port: 9091
    orchestrator_metrics_listen_addr: "[{{ orchestrator_metrics_listen_ip }}]:{{ orchestrator_metrics_listen_port }}"

    journalbeat_hosts:
      - "elasticsearch-node-0.testnet.dfinity.systems:443"
      - "elasticsearch-node-1.testnet.dfinity.systems:443"
      - "elasticsearch-node-2.testnet.dfinity.systems:443"

boundary:
  vars:
    api_listen_port: 443
    api_listen_protocol: https
    elasticsearch_url: "https://elasticsearch.testnet.dfinity.systems"
    ipv4_http_ips:
      - "103.21.244.0/22"
      - "103.22.200.0/22"
      - "103.31.4.0/22"
      - "104.16.0.0/13"
      - "104.24.0.0/14"
      - "108.162.192.0/18"
      - "131.0.72.0/22"
      - "141.101.64.0/18"
      - "149.97.209.182/30"
      - "149.97.209.186/30"
      - "162.158.0.0/15"
      - "172.64.0.0/13"
      - "173.245.48.0/20"
      - "188.114.96.0/20"
      - "190.93.240.0/20"
      - "192.235.122.32/28"
      - "197.234.240.0/22"
      - "198.41.128.0/17"
      - "212.71.124.192/29"
      - "62.209.33.184/29"
    ipv6_http_ips:
      - "2001:4d78:40d::/48"  # FR1
      - "2607:f6f0:3004::/48" # CH1
      - "2607:fb58:9005::/48" # SF1-old
      - "2602:fb2b:100::/48"  # SF1
      - "2a00:fb01:400::/56"  # ZH1
    ipv6_debug_ips:
      - "2001:4d78:40d::/48"  # FR1
      - "2607:f6f0:3004::/48" # CH1
      - "2607:fb58:9005::/48" # SF1-old
      - "2602:fb2b:100::/48"  # SF1
      - "2a00:fb01:400::/56"  # ZH1
    ipv6_monitoring_ips:
      - "2a05:d01c:e2c:a700::/56" # AWS eu-west-2 London Monitoring VPC
      - "2a05:d01c:d9:2b00::/56" # prometheus.mainnet.dfinity.network

    node_exporter_metrics_ip: "{{ ipv6_address }}"
    node_exporter_metrics_port: 9100
    node_exporter_metrics_addr: "[{{ node_exporter_metrics_ip }}]:{{ node_exporter_metrics_port }}"

    control_plane_metrics_ip: "{{ ipv6_address }}"
    control_plane_metrics_port: 9312
    control_plane_metrics_addr: "[{{ control_plane_metrics_ip }}]:{{ control_plane_metrics_port }}"

    icx_proxy_metrics_ip: "{{ ipv6_address }}"
    icx_proxy_metrics_port: 9314
    icx_proxy_metrics_addr: "[{{ icx_proxy_metrics_ip }}]:{{ icx_proxy_metrics_port }}"

    nginx_metrics_ip: "{{ ipv6_address }}"
    nginx_metrics_port: 9316
    nginx_metrics_addr: "[{{ nginx_metrics_ip }}]:{{ nginx_metrics_port }}"

    vector_metrics_ip: "{{ ipv6_address }}"
    vector_metrics_port: 9317
    vector_metrics_addr: "[{{ vector_metrics_ip }}]:{{ vector_metrics_port }}"

    denylist_updater_metrics_ip: "{{ ipv6_address }}"
    denylist_updater_metrics_port: 9318
    denylist_updater_metrics_addr: "[{{ denylist_updater_metrics_ip }}]:{{ denylist_updater_metrics_port }}"

    process_exporter_metrics_ip: "{{ ipv6_address }}"
    process_exporter_metrics_port: 9319
    process_exporter_metrics_addr: "[{{ process_exporter_metrics_ip }}]:{{ process_exporter_metrics_port }}"

    ic_registry_replicator_metrics_ip: "{{ ipv6_address }}"
    ic_registry_replicator_metrics_port: 9320
    ic_registry_replicator_metrics_addr: "[{{ ic_registry_replicator_metrics_ip }}]:{{ ic_registry_replicator_metrics_port }}"

all:
  vars:
    ansible_python_interpreter: python3
    become_method: sudo
