[package]
name = "ic-crypto-internal-basic-sig-iccsa-test-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
ic-certification-test-utils = { path = "../../../../../../certification/test-utils" }
ic-crypto-sha2 = { path = "../../../../../sha2" }
ic-crypto-tree-hash = { path = "../../../../../tree_hash" }
ic-types = { path = "../../../../../../types/types" }
rand = "0.8.3"
