[package]
name = "ic-crypto-tls-interfaces"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
async-trait = "0.1.41"
ic-types = { path = "../../types/types" }
ic-protobuf = { path = "../../protobuf" }
ic-crypto-sha2 = { path = "../sha2" }
serde = { workspace = true }
tokio = { workspace = true }
tokio-rustls = "0.24.0"
x509-parser = "0.15.1"

[dev-dependencies]
assert_matches = "1.5.0"
ic-crypto-test-utils-reproducible-rng = { path = "../test_utils/reproducible_rng" }
ic-crypto-test-utils-tls = { path = "../test_utils/tls" }
maplit = "1.0"
json5 = "0.4.1"
