[package]
name = "ic-crypto-tls-interfaces"
version = "0.8.0"
edition = "2021"

[dependencies]
async-trait = "0.1.41"
ic-types = { path = "../../types/types" }
ic-protobuf = { path = "../../protobuf" }
openssl = "0.10.29"
serde = { version = "1.0.99", features = ["derive"] }
tokio = { version = "1.24.2", features = ["net", "io-util"] }
tokio-rustls = "0.22.0"

[dev-dependencies]
assert_matches = "1.5.0"
ic-crypto-test-utils = { path = "../test_utils" }
maplit = "1.0"
json5 = "0.4.1"
