[package]
name = "ic-btc-adapter-client"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin = "0.28.1"
ic-adapter-metrics = { path = "../../monitoring/adapter_metrics" }
ic-async-utils = { path = "../../async_utils" }
ic-btc-service = { path = "../service" }
ic-btc-types-internal = { path = "../types/internal" }
ic-config = { path = "../../config" }
ic-interfaces-bitcoin-adapter-client = { path = "../../interfaces/bitcoin_adapter_client" }
ic-logger = { path = "../../monitoring/logger" }
ic-metrics = { path = "../../monitoring/metrics" }
prometheus = { version = "0.12.0", features = [ "process" ] }
serde = { version = "1.0.99", features = [ "derive" ] }
serde_bytes = "0.11.5"
slog = { version = "2.5.2", features = ["nested-values", "release_max_level_debug"] }
tokio = { version = "1.23.1", features = ["full"] }
tonic = "0.8.2"
tower = { version = "0.4.11", features = ["util"] }

