[package]
name = "ic-crypto-internal-threshold-sig-bls12381-der"
description = "Internal utils for serializing threshold signatures to DER with minimal dependencies"
version.workspace = true
authors.workspace = true
edition.workspace = true
documentation.workspace = true

[dependencies]
simple_asn1 = { workspace = true }
