[package]
name = "ic-registry-transport"
version = "0.8.0"
edition = "2021"

[dependencies]
candid = { workspace = true }
ic-protobuf = { path = "../../protobuf" }
ic-base-types = { path = "../../types/base_types" }
prost = { workspace = true }
bytes = { workspace = true }
serde = { version = "1.0.99", features = ["derive"] }

[dev-dependencies]
ic-registry-transport-protobuf-generator = { path = "./protobuf_generator" }
ic-test-utilities-compare-dirs = { path = "../../test_utilities/compare_dirs" }
ic-registry-keys = { path = "../keys" }
ic-nervous-system-common-test-keys = { path = "../../nervous_system/common/test_keys" }
tempfile = "3.1.0"
