[package]
name = "ic-canonical-state-tree-hash-test-utils"
version = "0.8.0"
edition = "2021"

[dependencies]
ic-canonical-state-tree-hash = { path = ".." }
ic-crypto-tree-hash = { path = "../../../crypto/tree_hash" }
ic-crypto-tree-hash-test-utils = { path = "../../../crypto/tree_hash/test_utils" }
rand = "0.8"
