[package]
name = "ic-onchain-observability-adapter"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.6", features = ["derive"] }
ic-async-utils = { path = "../../../async_utils" }
ic-config = { path = "../../../config" }
ic-logger = { path = "../../../monitoring/logger" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
slog = "2.7.0"
thiserror = "1.0.26"
tokio = { version = "1.24.2", features = ["full"] }

[dev-dependencies]
