[package]
name = "ic-state-layout"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
hex = "0.4.2"
ic-base-types = { path = "../types/base_types" }
ic-config = { path = "../config" }
ic-ic00-types = { path = "../types/ic00_types" }
ic-logger = { path = "../monitoring/logger" }
ic-metrics = { path = "../monitoring/metrics" }
ic-protobuf = { path = "../protobuf" }
ic-replicated-state = { path = "../replicated_state" }
ic-sys = { path = "../sys" }
ic-types = { path = "../types/types" }
ic-utils = { path = "../utils" }
ic-wasm-types = { path = "../types/wasm_types" }
libc = "0.2.91"
prometheus = { workspace = true }
prost = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
serde_cbor = { workspace = true }
scoped_threadpool = "0.1.*"
slog = { workspace = true }
tempfile = "3.1.0"

[dev-dependencies]
ic-interfaces = { path = "../interfaces" }
ic-test-utilities = { path = "../test_utilities" }
ic-test-utilities-logger = { path = "../test_utilities/logger" }
ic-test-utilities-tmpdir = { path = "../test_utilities/tmpdir" }
itertools = { workspace = true }
proptest = "1.0"
