[package]
name = "ic-state-layout"
version = "0.8.0"
edition = "2021"

[dependencies]
hex = "0.4.2"
ic-base-types = { path = "../types/base_types" }
ic-ic00-types = { path = "../types/ic00_types" }
ic-logger = { path = "../monitoring/logger" }
ic-metrics = { path = "../monitoring/metrics" }
ic-protobuf = { path = "../protobuf" }
ic-replicated-state = { path = "../replicated_state" }
ic-sys = { path = "../sys" }
ic-types = { path = "../types/types" }
ic-utils = { path = "../utils" }
ic-wasm-types = { path = "../types/wasm_types" }
libc = "0.2.91"
prometheus = { version = "0.12.0", features = ["process"] }
prost = { workspace = true }
serde = { version = "1.0.99", features = ["derive"] }
serde_bytes = "0.11"
serde_cbor = "0.11.1"
scoped_threadpool = "0.1.*"
slog = { version = "2.5.2", features = [
    "nested-values",
    "release_max_level_debug",
] }
tempfile = "3.1.0"

[dev-dependencies]
ic-interfaces = { path = "../interfaces" }
ic-test-utilities = { path = "../test_utilities" }
ic-test-utilities-logger = { path = "../test_utilities/logger" }
ic-test-utilities-tmpdir = { path = "../test_utilities/tmpdir" }
