[package]
name = "ic-transport-test-client"
version = "0.8.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.36"
clap = { version = "3.1.6", features = ["derive"] }
crossbeam-channel = "0.5.5"
futures = "0.3.5"
ic-config = { path = "../config" }
ic-crypto-temp-crypto = { path = "../crypto/temp_crypto" }
ic-crypto-tls-interfaces = { path = "../crypto/tls_interfaces" }
ic-interfaces = { path = "../interfaces" }
ic-interfaces-transport = { path = "../interfaces/transport" }
ic-logger = { path = "../monitoring/logger" }
ic-metrics = { path = "../monitoring/metrics" }
ic-registry-client-fake = { path = "../registry/fake" }
ic-registry-keys = { path = "../registry/keys" }
ic-registry-proto-data-provider = { path = "../registry/proto_data_provider" }
ic-transport = { path = "../transport" }
ic-types = { path = "../types/types" }
notify = "4.0.12"
rand = "0.8"
slog = { version = "2.5.2", features = ["nested-values", "release_max_level_debug"] }
tokio = { version = "1.23.1", features = ["full"] }
tokio-openssl = "0.6.1"
tower = "0.4.12"

