[package]
name = "ic-metrics"
version = "0.8.0"
edition = "2021"

[dependencies]
futures = "0.3.21"
ic-adapter-metrics = { path = "../adapter_metrics" }
ic-logger = { path = "../logger" }
libc = "0.2.91"
prometheus = { version = "0.12.0", features = [ "process" ] }
slog = "2.7.0"
slog-async = "2.7.0"
tokio = { version = "1.23.1", features = ["full"] }

[dev-dependencies]
ic-logger = { path = "../logger" }
slog = { version = "2.5.2", features = ["nested-values", "release_max_level_debug"] }

[target.'cfg(target_os = "linux")'.dependencies]
procfs = { version = "^0.9", default-features = false }
