[package]
name = "ic-metrics"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
futures = { workspace = true }
ic-adapter-metrics = { path = "../adapter_metrics" }
ic-logger = { path = "../logger" }
libc = "0.2.91"
prometheus = { workspace = true }
slog = { workspace = true }
slog-async = "2.7.0"
tokio = { workspace = true }
tokio-metrics = "0.3.0"

[dev-dependencies]
ic-logger = { path = "../logger" }
slog = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
procfs = { version = "^0.9", default-features = false }
