[package]
name = "ic-workload-generator"
version = "0.8.0"
edition = "2021"

[dependencies]
backoff = "0.3.0"
ic-canister-client = { path = "../canister_client" }
ic-canister-client-sender = { path = "../canister_client/sender" }
ic-config = { path = "../config" }
ic-ic00-types = { path = "../types/ic00_types" }
ic-metrics = { path = "../monitoring/metrics" }
ic-http-endpoints-metrics = { path = "../http_endpoints/metrics" }
ic-test-identity = { path = "../test_utilities/identity" }
ic-types = { path = "../types/types" }
byte-unit = "4.0.14"
candid = { workspace = true }
chrono = "0.4.19"
clap = { version = "3.1.6", features = ["derive"] }
console = "0.11"
futures = { workspace = true }
hex = "0.4.3"
itertools = "0.10.3"
indicatif = "0.17.3"
lazy_static = "1.4.0"
prometheus = { version = "0.12.0", features = ["process"] }
rand = "0.8.4"
serde = { version = "1.0.99", features = ["derive"] }
serde_json = "1.0.40"
slog = { version = "2.5.2", features = [
    "nested-values",
    "release_max_level_debug",
] }
slog-scope = "4.1.2"
slog-term = "2.6.0"
tokio = { version = "1.32.0", features = ["full"] }
url = "2.1.1"
wat = "1.0.52"

[[bin]]
name = "ic-workload-generator"
path = "src/main.rs"
