[package]
name = "ic-registry-replicator"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.1.6", features = ["derive"] }
ic-config = { path = "../../config" }
ic-crypto-for-verification-only = { path = "../../crypto/for_verification_only" }
ic-crypto-utils-threshold-sig-der = { path = "../../crypto/utils/threshold_sig_der" }
ic-interfaces-registry = { path = "../../interfaces/registry" }
ic-logger = { path = "../../monitoring/logger" }
ic-metrics = { path = "../../monitoring/metrics" }
ic-http-endpoints-metrics = { path = "../../http_endpoints/metrics" }
ic-protobuf = { path = "../../protobuf" }
ic-registry-client = { path = "../../registry/client" }
ic-registry-client-helpers = { path = "../../registry/helpers" }
ic-registry-nns-data-provider = { path = "../../registry/nns_data_provider" }
ic-registry-keys = { path = "../../registry/keys" }
ic-registry-local-store = { path = "../../registry/local_store" }
ic-registry-routing-table = { path = "../../registry/routing_table" }
ic-types = { path = "../../types/types" }
prometheus = { version = "0.12.0", features = [ "process" ] }
prost = "0.11.0"
slog = { version = "2.5.2", features = ["nested-values", "release_max_level_debug"] }
tempfile = "3.1.0"
tokio = { version = "1.24.2", features = ["full"] }
url = "2.1.1"

[[bin]]
name = "ic-registry-replicator"
path = "src/main.rs"
