[package]
name = "ic-ledger-core"
version = "0.8.0"
authors = ["The Internet Computer Project Developers"]
edition = "2021"

[dependencies]
candid = { workspace = true }
ic-ledger-hash-of = { path = "../../../packages/ic-ledger-hash-of" }
num-traits = "0.2.12"
serde = "1.0"
serde_bytes = "0.11"

[dev-dependencies]
