[package]
name = "ic-http-utils"
version = "0.8.0"
edition = "2021"

[dependencies]
flate2 = "1.0.20"
hex = "0.4.2"
http = "0.2.1"
tokio = { version = "1.24.2", features = ["full"] }
hyper = { version = "0.14.18", features = ["full"] }
hyper-tls = "0.5.0"
ic-crypto-sha = { path = "../crypto/sha" }
ic-logger = { path = "../monitoring/logger" }
slog = "2.5.2"
tar = "0.4.38"
