[package]
name = "ic-crypto-ecdsa-secp256r1"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ic-crypto-getrandom-for-wasm = { path = "../getrandom_for_wasm" }
lazy_static = "1.4"
num-bigint = "0.4"
p256 = { workspace = true }
pem = "1.1.0"
rand = "0.8"
rand_chacha = "0.3"
simple_asn1 = { workspace = true }
zeroize = { version = "1.5", features = ["zeroize_derive"] }

[dev-dependencies]
hex = "0.4"
ic-crypto-sha2 = { path = "../sha2" }
ic-crypto-test-utils-reproducible-rng = { path = "../test_utils/reproducible_rng" }
wycheproof = "0.5"
