[package]
name = "ic-validator-ingress-message"
version = "0.8.0"
edition = "2021"
description = "Standalone library to validate ingress messages"

[dependencies]
base64 = "0.13.0"
dfn_core = { path = "../../rust_canisters/dfn_core" }
hex = "0.4.2"
ic-crypto-interfaces-sig-verification = { path = "../../crypto/interfaces/sig_verification" }
ic-crypto-standalone-sig-verifier = { path = "../../crypto/standalone-sig-verifier" }
ic-crypto-utils-threshold-sig-der = { path = "../../crypto/utils/threshold_sig_der" }
ic-types = { path = "../../types/types" }
ic-validator = { path = "../../validator" }

[dev-dependencies]
assert_matches = "1.5.0"
ic-canister-client-sender = { path = "../../canister_client/sender" }
ic-certification-test-utils = { path = "../../certification/test-utils" }
ic-constants = { path = "../../constants" }
ic-crypto-test-utils-canister-sigs = { path = "../../crypto/test_utils/canister_sigs" }
ic-crypto-test-utils-reproducible-rng = { path = "../../crypto/test_utils/reproducible_rng" }
ic-crypto-test-utils-root-of-trust = { path = "../../crypto/test_utils/root_of_trust" }
ic-crypto-tree-hash = { path = "../../crypto/tree_hash" }
ic-registry-client-helpers = { path = "../../registry/helpers" }
ic-validator-http-request-test-utils = { path = "../http_request_test_utils" }
rand = "0.8"
strum = "0.23.0"
