[package]
name = "ic-sns-governance"
version = "0.8.0"
edition = "2021"

[[bin]]
name = "sns-governance-canister"
path = "canister/canister.rs"

[lib]
path = "src/lib.rs"

[[test]]
name = "governance-test"
path = "tests/governance.rs"

[[test]]
name = "governance-interleaving-test"
path = "tests/interleaving_tests.rs"

[dependencies]
# This MUST be kept in sync with build-info-build in the [build-dependencies] section!
build-info = { version = "0.0.26", default-features = false, features = [] }

async-trait = "0.1.42"
base64 = "0.13.0"
bytes = "1.0.1"
candid = "0.8.1"
clap = { version = "3.1.6", features = ["derive", "cargo"] }
comparable = { version = "0.5", features = ["derive"] }
dfn_candid = { path = "../../rust_canisters/dfn_candid" }
dfn_core = { path = "../../rust_canisters/dfn_core" }
dfn_http_metrics = { path = "../../rust_canisters/dfn_http_metrics" }
dfn_protobuf = { path = "../../rust_canisters/dfn_protobuf" }
hex = "0.4.3"
ic-base-types = { path = "../../types/base_types" }
ic-crypto-sha = { path = "../../crypto/sha/" }
ic-ic00-types = { path = "../../types/ic00_types" }
ic-icrc1 = { path = "../../rosetta-api/icrc1" }
ic-icrc1-client = { path = "../../rosetta-api/icrc1/client" }
ic-ledger-core = { path = "../../rosetta-api/ledger_core" }
ic-metrics-encoder = "1"
ic-nervous-system-common = { path = "../../nervous_system/common" }
ic-nervous-system-common-build-metadata = { path = "../../nervous_system/common/build_metadata" }
ic-nervous-system-root = { path = "../../nervous_system/root" }
ic-nns-constants = { path = "../../nns/constants" }
ic-protobuf = { path = "../../protobuf" }
lazy_static = "1.4.0"
icp-ledger = { path = "../../rosetta-api/icp_ledger" }
maplit = "1.0.2"
on_wire = { path = "../../rust_canisters/on_wire" }
prost = "0.11.0"
rand = "0.8"
rand_chacha = "0.3"
registry-canister = { path = "../../registry/canister" }
rust_decimal = "1.25"
rust_decimal_macros = "1.25"
serde = { version = "1.0", features = ["derive"] }
strum = "0.18.0"
strum_macros = "0.18.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
csv = "1.1"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
ic-types = { path = "../../types/types" }

[build-dependencies]
# This MUST be kept in sync with build-info in the [dependencies] section!
build-info-build = { version = "0.0.26", default-features = false, features = [
] }

ic-base-types = { path = "../../types/base_types" }
prost-build = "0.11.0"

[dev-dependencies]
assert_matches = "1.3.0"
criterion = "0.3"
futures = "0.3.13"
ic-canister-client-sender = { path = "../../canister_client/sender" }
ic-config = { path = "../../config" }
ic-crypto-sha = { path = "../../crypto/sha/" }
ic-nervous-system-common-test-keys = { path = "../../nervous_system/common/test_keys" }
ic-nervous-system-common-test-utils = { path = "../../nervous_system/common/test_utils" }
ic-sns-governance = { path = ".", features = ["test"] }
ic-sns-governance-protobuf-generator = { path = "./protobuf_generator" }
ic-sns-test-utils = { path = "../test_utils" }
ic-test-utilities = { path = "../../test_utilities" }
ic-test-utilities-compare-dirs = { path = "../../test_utilities/compare_dirs" }
lazy_static = "1.4.0"
pretty_assertions = "1.0"
proptest = "1.0"
tempfile = "3.1.0"
tokio = { version = "1.23.1", features = ["full"] }
tokio-test = "0.4.2"

[features]
test = []
