[package]
name = "ic-artifact-manager"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
bincode = "1.2.1"
ic-constants = { path = "../constants" }
ic-interfaces = { path = "../interfaces" }
ic-logger = { path = "../monitoring/logger" }
ic-metrics = { path = "../monitoring/metrics" }
ic-types = { path = "../types/types" }
crossbeam-channel = "0.5.5"
slog = { workspace = true }
prometheus = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
ic-config = { path = "../config" }
ic-artifact-pool = { path = "../artifact_pool" }
ic-protobuf = { path = "../protobuf" }
ic-test-utilities = { path = "../test_utilities" }
assert_matches = "1.3.0"

[features]
malicious_code = []
