[package]
name = "ic-error-types"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
ic-utils = { path = "../../utils" }
serde = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
