[package]
name = "ic-error-types"
version = "0.8.0"
edition = "2021"

[dependencies]
ic-utils = { path = "../../utils" }
serde = { version = "1.0.99", features = ["derive"] }
strum = "0.23.0"
strum_macros = "0.23.0"
