[package]
name = "ic-state-machine-tests"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = { workspace = true }
ciborium = { workspace = true }
clap = { workspace = true }
hex = "0.4.2"
ic-config = { path = "../config" }
ic-consensus = { path = "../consensus" }
ic-constants = { path = "../constants" }
ic-crypto = { path = "../crypto" }
ic-crypto-ecdsa-secp256k1 = { path = "../crypto/ecdsa_secp256k1" }
ic-crypto-extended-bip32 = { path = "../crypto/extended_bip32" }
ic-crypto-iccsa = { path = "../crypto/iccsa" }
ic-crypto-interfaces-sig-verification = { path = "../crypto/interfaces/sig_verification" }
ic-crypto-internal-seed = { path = "../crypto/internal/crypto_lib/seed" }
ic-crypto-internal-threshold-sig-bls12381 = { path = "../crypto/internal/crypto_lib/threshold_sig/bls12_381" }
ic-crypto-internal-types = { path = "../crypto/internal/crypto_lib/types" }
ic-crypto-test-utils-keys = { path = "../crypto/test_utils/keys" }
ic-crypto-tree-hash = { path = "../crypto/tree_hash" }
ic-crypto-utils-threshold-sig-der = { path = "../crypto/utils/threshold_sig_der" }
ic-cycles-account-manager = { path = "../cycles_account_manager" }
ic-error-types = { path = "../types/error_types" }
ic-execution-environment = { path = "../execution_environment/" }
ic-ic00-types = { path = "../types/ic00_types" }
ic-ingress-manager = { path = "../ingress_manager" }
ic-interfaces = { path = "../interfaces" }
ic-interfaces-registry = { path = "../interfaces/registry" }
ic-interfaces-state-manager = { path = "../interfaces/state_manager" }
ic-interfaces-certified-stream-store = { path = "../interfaces/certified_stream_store" }
ic-logger = { path = "../monitoring/logger" }
ic-messaging = { path = "../messaging" }
ic-metrics = { path = "../monitoring/metrics" }
ic-protobuf = { path = "../protobuf" }
ic-registry-client-fake = { path = "../registry/fake" }
ic-registry-client-helpers = { path = "../registry/helpers" }
ic-registry-keys = { path = "../registry/keys" }
ic-registry-proto-data-provider = { path = "../registry/proto_data_provider" }
ic-registry-provisional-whitelist = { path = "../registry/provisional_whitelist" }
ic-registry-routing-table = { path = "../registry/routing_table" }
ic-registry-subnet-features = { path = "../registry/subnet_features" }
ic-registry-subnet-type = { path = "../registry/subnet_type" }
ic-replicated-state = { path = "../replicated_state" }
ic-state-layout = { path = "../state_layout" }
ic-state-manager = { path = "../state_manager" }
ic-test-utilities = { path = "../test_utilities" }
ic-test-utilities-metrics = { path = "../test_utilities/metrics" }
ic-test-utilities-registry = { path = "../test_utilities/registry" }
ic-test-state-machine-client = "3.0"
ic-types = { path = "../types/types" }
ic-xnet-payload-builder = { path = "../xnet/payload_builder" }
rand = "0.8"
serde = { workspace = true }
serde_bytes = { workspace = true }
serde_cbor = { workspace = true }
slog = { version = "2.5.2", features = [
    "nested-values",
    "max_level_trace",
    "release_max_level_debug",
] }
slog-term = "2.6.0"
tempfile = "3.1.0"
tokio = { workspace = true }
wat = "1.0.52"
maplit = "1.0.2"

[dev-dependencies]
proptest = "1.0"
ic-crypto-tecdsa = { path = "../crypto/tecdsa" }
ic-test-utilities = { path = "../test_utilities" }
ic-types-test-utils = { path = "../types/types_test_utils" }
ic-universal-canister = { path = "../universal_canister/lib" }
