[package]
name = "obs-canister-clients"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ic-agent =  { workspace = true, features = ["reqwest"] }
candid = { workspace = true }
serde = "1"
rand = "0.8"
url = "2.2.2"
slog = { version = "2.5.2", features = ["nested-values"] }