[package]
name = "ic-crypto-tree-hash"
version = "0.8.0"
edition = "2021"

[dependencies]
assert_matches = "1.5.0"
ic-crypto-internal-types = { path = "../internal/crypto_lib/types" }
ic-crypto-sha2 = { path = "../sha2" }
ic-protobuf = { path = "../../protobuf" }
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
thiserror = "1.0"

[dev-dependencies]
criterion = "0.5"
ic-crypto-test-utils-reproducible-rng = { path = "../test_utils/reproducible_rng" }
ic-crypto-tree-hash-test-utils = { path = "test_utils" }
maplit = "1.0.2"
proptest = "1.0"
prost = { workspace = true }
rand = "0.8.4"
serde_cbor = "0.11.1"

[[bench]]
name = "tree_hash"
harness = false

[[bench]]
name = "flat_map"
harness = false
