name: Main CI

on:
  # Todo: re-enable once github runner resources have been set
  # push:
  merge_group:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AWS_SHARED_CREDENTIALS_FILE: "~/.aws/credentials"
  ROOT_PIPELINE_ID: ""
  CI_JOB_ID: ""
  CI_JOB_NAME: "bazel-test-all"
  CI_JOB_URL: ""

jobs:
  test:
    name: Bazel-Test-All
    runs-on: self-hosted
    timeout-minutes: 80
    container:
      image: docker.io/dfinity/ic-build
      options: --user ubuntu
    if: ${{ vars.RUN_CI == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Bazel Test All
        id: bazel-test-all
        run: ${GITHUB_WORKSPACE}/gitlab-ci/src/bazel-ci/main.sh
        env:
          BAZEL_COMMAND: "test"
          BAZEL_TARGETS: "//..."
          BAZEL_CI_CONFIG: ""
          BAZEL_EXTRA_ARGS: "--test_timeout_filters=short,moderate"
          BAZEL_STARTUP_ARGS: "--output_base=/var/tmp/bazel-output/"
          CI_COMMIT_SHA: ${{ github.sha }}
          CI_COMMIT_REF_PROTECTED: ${{ github.ref_protected }}
      - name: Upload Bazel artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bazel-artifacts
          path: |
            - bazel-build-log*.json*
            - bazel-bep.pb
            - bazel-testlogs-gitlab/**/test.xml
