[package]
name = "ic-nervous-system-governance"
version = "0.0.1"
authors = ["The Internet Computer Project Developers"]
edition = "2021"

[dependencies]
ic-base-types = { path = "../../types/base_types" }
ic-stable-structures = { workspace = true }
maplit = "1.0.2"
num-traits = "0.2.12"
