[package]
name = "ic-crypto-internal-basic-sig-rsa-pkcs1"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
rsa = { version = "0.9.2", features = [ "sha2" ] }
ic-types = { path = "../../../../../types/types" }
ic-crypto-sha2 = { path = "../../../../sha2" }
ic-crypto-internal-basic-sig-der-utils = { path = "../der_utils" }
num-traits = { version= "0.2.9", default-features = false, features = ["libm"] }
pkcs8 = "0.10.2"
sha2 = "0.10.2"
serde = { workspace = true }
simple_asn1 = { workspace = true }
num-bigint = "~0.4.3"
ic-crypto-getrandom-for-wasm = { path = "../../../../getrandom_for_wasm" }

[dev-dependencies]
hex = "0.4.2"
serde = { workspace = true }
serde_json = { workspace = true }
wycheproof = "0.5"
