[package]
name = "ic-crypto-internal-basic-sig-rsa-pkcs1"
version = "0.8.0"
edition = "2021"

[dependencies]
rsa = { version = "0.9.2", features = [ "sha2" ] }
ic-types = { path = "../../../../../types/types" }
ic-crypto-sha2 = { path = "../../../../sha2" }
ic-crypto-internal-basic-sig-der-utils = { path = "../der_utils" }
num-traits = { version= "0.2.9", default-features = false, features = ["libm"] }
pkcs8 = "0.10.2"
sha2 = "0.10.2"
serde = { version = "1.0.99", features = [ "derive" ] }
simple_asn1 = "0.6.1"
num-bigint = "~0.4.3"
ic-crypto-getrandom-for-wasm = { path = "../../../../getrandom_for_wasm" }

[dev-dependencies]
hex = "0.4.2"
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0.54"
wycheproof = "0.5"
