[package]
name = "deterministic_ips"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ic-crypto-sha2 = { path = "../../crypto/sha2" }
thiserror = "1.0"
anyhow = "1.0.71"
clap = { version = "4.3.3", features = ["derive"] }

[[bin]]
name = "deterministic-ips"
path = "src/main.rs"
