[package]
name = "ic-icrc1-ledger-sm-tests"
version = "0.8.0"
authors = ["The Internet Computer Project Developers"]
description = "StateMachines based tests for https://github.com/dfinity/ICRC-1 ledgers"
edition = "2021"

[dependencies]
anyhow = "1.0.72"
async-trait = "0.1.72"
candid = { workspace = true }
ic-base-types = { path = "../../../../types/base_types" }
ic-error-types = { path = "../../../../types/error_types" }
ic-types = { path = "../../../../types/types" }
ic-icrc1 = { path = "../.." }
ic-icrc1-ledger = { path = ".." }
ic-icrc1-tokens-u64 = { path = "../../tokens_u64" }
ic-icrc1-tokens-u256 = { path = "../../tokens_u256", optional = true }
ic-ledger-core = { path = "../../../ledger_core" }
ic-ledger-canister-core = { path = "../../../ledger_canister_core" }
ic-state-machine-tests = { path = "../../../../state_machine_tests" }
icrc-ledger-types = { path = "../../../../../packages/icrc-ledger-types" }
ic-ledger-hash-of = { path = "../../../../../packages/ic-ledger-hash-of" }
num-traits = "0.2.14"
proptest = "1.0"
cddl = "0.9.0-beta.1"
hex = "0.4.2"
serde = "1.0.99"
futures = { workspace = true }
icrc1-test-env = { git = "https://github.com/dfinity/ICRC-1", rev = "bdcf39e32a12185fbcec33897001d93c901d6689" }
icrc1-test-suite = { git = "https://github.com/dfinity/ICRC-1", rev = "bdcf39e32a12185fbcec33897001d93c901d6689" }

[features]
default = []
u256-tokens = ["dep:ic-icrc1-tokens-u256"]
